import {BUILTIN_TEMPLATES,LMN_TEMPLATE} from './templates.js';
import {materializeInstanceDefinition,normalizeInstance} from './model.js';
import {ensureVariableSchemes,ZI_WEI_BASIC_SCHEME} from './variable-schemes.js';
import {parseFormula} from './formula.js';
import {migrateStateContentModels} from '../domain/semantic-container.js';
import {ensureBoardState} from './board.js';

const clone=value=>structuredClone(value);
const mergeById=(a,b)=>[...new Map([...a,...b].map(item=>[item.id,clone(item)])).values()];
const currentTemplates=existing=>{const source=existing??[],custom=source.filter(template=>!template.builtin&&!String(template.id).startsWith('builtin:')),savedBuiltins=new Map(source.filter(template=>template.builtin||String(template.id).startsWith('builtin:')).map(template=>[template.id,template])),builtins=BUILTIN_TEMPLATES.map(template=>{const saved=savedBuiltins.get(template.id);if(!saved)return template;const savedParameters=new Map((saved.parameters??[]).map(parameter=>[parameter.id,parameter]));return{...template,visual:{...(template.visual??{}),...(saved.visual??{}),relationStyle:{...(template.visual?.relationStyle??{}),...(saved.visual?.relationStyle??{})}},parameters:(template.parameters??[]).map(parameter=>({...parameter,...(savedParameters.has(parameter.id)?{defaultValue:savedParameters.get(parameter.id).defaultValue}:{}),defaultStyle:savedParameters.get(parameter.id)?.defaultStyle??parameter.defaultStyle}))}});return mergeById(custom,builtins)};

export function migrateV2ToV3(v2){
  if((v2.schemaVersion??v2.schema_version)===3)return clone(v2);const lmns=v2.lmns??[],existingInstances=v2.structureInstances??[];
  const migrated=lmns.map(lmn=>({id:lmn.id,templateId:LMN_TEMPLATE.id,templateVersion:LMN_TEMPLATE.version,ownerKnowledgeId:lmn.knowledgeId,bindings:Object.values(lmn.positions??{}).filter(position=>position.knowledgeId).map((position,index)=>({id:`migration:${lmn.id}:${position.position}:${index}`,instanceId:lmn.id,slotId:position.position,targetType:'knowledge',targetId:position.knowledgeId,metadata:{migratedFrom:'v2-lmn'},createdAt:lmn.createdAt,updatedAt:lmn.updatedAt})),parameters:{},runtimeState:{variables:{},results:{},errors:{}},layoutState:{visualOffsets:{},collapsedSlots:[]},createdAt:lmn.createdAt,updatedAt:lmn.updatedAt,migration:{source:'v2-lmn'}}));
  return{schemaVersion:3,application:'LMN Knowledge System',knowledge:clone(v2.knowledge??[]),relations:clone(v2.relations??[]),representations:clone(v2.representations??[]),structureTemplates:mergeById(BUILTIN_TEMPLATES,v2.structureTemplates??[]),structureInstances:mergeById(existingInstances,migrated),legacy:{lmns:clone(lmns),structures:clone(v2.structures??[])},migration:{from:Number(v2.schema_version??2),to:3,at:new Date().toISOString()}};
}

export function migrateV3ToV4(v3){
  const source=[3,4].includes(v3?.schemaVersion)?v3:migrateV2ToV3(v3),templates=currentTemplates(source.structureTemplates),templateMap=new Map(templates.map(template=>[template.id,template]));
  const instances=(source.structureInstances??[]).map(raw=>{const instance=normalizeInstance(clone(raw));if(instance.templateId==='builtin:mod-12'){instance.templateId='builtin:mod-n';instance.parameters={...instance.parameters,modulus:instance.parameters.modulus??12};instance.variables=instance.variables?.length?instance.variables:clone(ZI_WEI_BASIC_SCHEME.variables);instance.variableScheme={id:ZI_WEI_BASIC_SCHEME.id,name:ZI_WEI_BASIC_SCHEME.name,migratedFrom:'builtin:mod-12'};for(const variable of instance.variables??[])if(variable.formula){variable.formula=variable.formula.replace(/,\s*12\s*\)/g,', modulus)');try{variable.expression=parseFormula(variable.formula)}catch{}}}if(instance.templateId==='builtin:poset-hasse'&&instance.parameters.starter==null)instance.parameters.starter='diamond';const template=templateMap.get(instance.templateId);if(!instance.variables.length&&template?.variables)instance.variables=clone(template.variables);instance.templateVersion=template?.version??instance.templateVersion;return instance});
  const migrated={...clone(source),schemaVersion:4,application:'LMN Knowledge System',structureTemplates:templates,structureInstances:instances,variableSchemes:ensureVariableSchemes(source.variableSchemes??[]),boards:clone(source.boards??[]),placements:clone(source.placements??[]),settings:clone(source.settings??[]),migration:{from:source.schemaVersion??3,to:4,at:new Date().toISOString(),preservedIds:true,contentModel:'semantic-container-v1',boardModel:'board-frame-v1'}};ensureBoardState(migrated);migrateStateContentModels(migrated,instance=>{const template=templateMap.get(instance.templateId);return template?materializeInstanceDefinition(template,instance):null});return migrated;
}

export function migrateAnyToV4(value){return migrateV3ToV4(value)}

export function validateV3Bundle(bundle){const copy=bundle?.schemaVersion===4?{...bundle,schemaVersion:3}:bundle;const errors=[];if(copy?.schemaVersion!==3)errors.push('schemaVersion must be 3');for(const key of['knowledge','relations','structureTemplates','structureInstances'])if(!Array.isArray(copy?.[key]))errors.push(`${key} must be an array`);return finishValidation(copy,errors)}
export function validateV4Bundle(bundle){const errors=[];if(bundle?.schemaVersion!==4)errors.push('schemaVersion must be 4');for(const key of['knowledge','relations','structureTemplates','structureInstances'])if(!Array.isArray(bundle?.[key]))errors.push(`${key} must be an array`);if(bundle?.boards!=null&&!Array.isArray(bundle.boards))errors.push('boards must be an array');if(bundle?.placements!=null&&!Array.isArray(bundle.placements))errors.push('placements must be an array');return finishValidation(bundle,errors)}
function finishValidation(bundle,errors){const knowledge=new Set((bundle?.knowledge??[]).map(item=>item.id)),templates=new Set((bundle?.structureTemplates??[]).map(item=>item.id)),instances=new Set((bundle?.structureInstances??[]).map(item=>item.id));for(const relation of bundle?.relations??[])if(!knowledge.has(relation.sourceId)||!knowledge.has(relation.targetId))errors.push(`dangling relation ${relation.id}`);for(const instance of bundle?.structureInstances??[]){if(!templates.has(instance.templateId))errors.push(`instance ${instance.id} has missing template`);for(const binding of instance.bindings??[]){if(binding.targetType==='knowledge'&&!knowledge.has(binding.targetId))errors.push(`binding ${binding.id} has missing Knowledge`);if(binding.targetType==='structure'&&!instances.has(binding.targetId))errors.push(`binding ${binding.id} has missing Structure`)}}for(const board of bundle?.boards??[]){if(!knowledge.has(board.ownerKnowledgeId))errors.push(`board ${board.id} has missing owner Knowledge`);for(const frame of board.frames??[])if(!instances.has(frame.instanceId))errors.push(`frame ${frame.id} has missing Structure`)}return{valid:!errors.length,errors}}
