import {materializeTemplate} from './templates.js';
const uid=()=>globalThis.crypto?.randomUUID?.()??`v4-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now=()=>new Date().toISOString();
const defaults=()=>({addedSlots:[],removedSlotIds:[],addedEdges:[],removedEdgeIds:[],slotPatches:{},edgePatches:{}});

export function normalizeInstance(instance){
  instance.bindings??=[];instance.parameters??={};instance.variables??=[];instance.runtimeState??={variables:{},results:{},errors:{}};instance.runtimeState.variables??={};instance.runtimeState.results??={};instance.runtimeState.errors??={};instance.overrides={...defaults(),...(instance.overrides??{})};instance.layoutState={visualOffsets:{},nodePositions:{},collapsedSlots:[],...(instance.layoutState??{})};instance.objectHistory??=[];return instance;
}

export function createStructureInstance(template,ownerKnowledgeId=null,parameters={}){
  const resolved=materializeTemplate(template,parameters),values=Object.fromEntries(resolved.parameters.map(parameter=>[parameter.id,parameters[parameter.id]??parameter.defaultValue]));
  const variables=structuredClone(resolved.variables??[]),runtimeVariables={};for(const variable of variables)if(variable.kind!=='derived'&&variable.value!=null)runtimeVariables[variable.id]=variable.value;
  return{id:uid(),templateId:template.id,templateVersion:template.version,ownerKnowledgeId,bindings:[],parameters:values,variables,runtimeState:{variables:runtimeVariables,results:{},errors:{}},overrides:defaults(),layoutState:{visualOffsets:{},nodePositions:{},collapsedSlots:[]},objectHistory:[],createdAt:now(),updatedAt:now()};
}

export function materializeInstanceDefinition(template,instance){
  normalizeInstance(instance);const base=materializeTemplate(template,instance.parameters),overrides=instance.overrides,removedSlots=new Set(overrides.removedSlotIds),removedEdges=new Set(overrides.removedEdgeIds);
  const slots=[...base.slots.filter(slot=>!removedSlots.has(slot.id)),...overrides.addedSlots.filter(slot=>!removedSlots.has(slot.id))].map(slot=>({...slot,...overrides.slotPatches[slot.id],semanticCoordinate:{...slot.semanticCoordinate,...overrides.slotPatches[slot.id]?.semanticCoordinate}}));
  const slotIds=new Set(slots.map(slot=>slot.id));const edges=[...base.edges.filter(edge=>!removedEdges.has(edge.id)),...overrides.addedEdges.filter(edge=>!removedEdges.has(edge.id))].filter(edge=>slotIds.has(edge.sourceSlotId)&&slotIds.has(edge.targetSlotId)).map(edge=>({...edge,...overrides.edgePatches[edge.id]}));
  return{...base,slots,edges,variables:instance.variables};
}

export function createBinding(instanceId,slotId,targetType,targetId,metadata={}){return{id:uid(),instanceId,slotId,targetType,targetId,metadata,createdAt:now(),updatedAt:now()}}
export function validateTemplate(template){
  const errors=[];if(!template?.id)errors.push('template.id is required');if(!template?.name)errors.push('template.name is required');if(!Array.isArray(template?.slots))errors.push('slots must be an array');if(!Array.isArray(template?.edges))errors.push('edges must be an array');
  const ids=new Set();for(const slot of template?.slots??[]){if(!slot.id)errors.push('slot.id is required');if(ids.has(slot.id))errors.push(`duplicate slot ${slot.id}`);ids.add(slot.id);if(!Array.isArray(slot.accepts)||!slot.accepts.length)errors.push(`slot ${slot.id} has no accepted target type`);if(!['one','many'].includes(slot.cardinality))errors.push(`slot ${slot.id} has invalid cardinality`)}
  for(const edge of template?.edges??[]){if(!ids.has(edge.sourceSlotId)||!ids.has(edge.targetSlotId))errors.push(`edge ${edge.id} has dangling slot`);if(!['undirected','directed','bidirectional','cyclic','conditional','derived'].includes(edge.direction))errors.push(`edge ${edge.id} has invalid direction`)}return{valid:!errors.length,errors};
}

export function validateInstance(instance,templates,allInstances=[],knowledge=[]){
  const errors=[],template=templates.find(item=>item.id===instance?.templateId);if(!template)return{valid:false,errors:[`missing template ${instance?.templateId}`]};const resolved=materializeInstanceDefinition(template,instance),slots=new Map(resolved.slots.map(slot=>[slot.id,slot])),knowledgeIds=new Set(knowledge.map(item=>item.id)),instanceIds=new Set(allInstances.map(item=>item.id));
  for(const binding of instance.bindings??[]){const slot=slots.get(binding.slotId);if(!slot){errors.push(`binding ${binding.id} references missing slot ${binding.slotId}`);continue}if(!slot.accepts.includes(binding.targetType))errors.push(`slot ${binding.slotId} does not accept ${binding.targetType}`);if(binding.targetType==='knowledge'&&!knowledgeIds.has(binding.targetId))errors.push(`binding ${binding.id} references missing Knowledge`);if(binding.targetType==='structure'&&!instanceIds.has(binding.targetId))errors.push(`binding ${binding.id} references missing Structure`)}
  for(const slot of resolved.slots.filter(item=>item.cardinality==='one'))if((instance.bindings??[]).filter(binding=>binding.slotId===slot.id).length>1)errors.push(`slot ${slot.id} accepts only one binding`);return{valid:!errors.length,errors};
}

export function bindTarget(instance,template,slotId,targetType,targetId,metadata={}){const resolved=materializeInstanceDefinition(template,instance),slot=resolved.slots.find(item=>item.id===slotId);if(!slot)throw new Error(`Unknown slot ${slotId}`);if(!slot.accepts.includes(targetType))throw new Error(`${slotId} does not accept ${targetType}`);if(slot.cardinality==='one')instance.bindings=instance.bindings.filter(binding=>binding.slotId!==slotId);const binding=createBinding(instance.id,slotId,targetType,targetId,metadata);instance.bindings.push(binding);touch(instance,'binding:add',{slotId,targetType,targetId});return binding}
export function removeBinding(instance,bindingId){instance.bindings=instance.bindings.filter(binding=>binding.id!==bindingId);touch(instance,'binding:remove',{bindingId})}

export function addInstanceSlot(instance,slot={}){normalizeInstance(instance);const id=slot.id??`slot-${uid().slice(-8)}`,created={id,label:slot.label??'New node',role:slot.role??'custom',semanticCoordinate:slot.semanticCoordinate??{order:instance.overrides.addedSlots.length},accepts:slot.accepts??['knowledge','value','variable','structure'],cardinality:slot.cardinality??'many',visual:slot.visual??{}};instance.overrides.addedSlots.push(created);touch(instance,'slot:add',{slotId:id});return created}
export function updateInstanceSlot(instance,slotId,patch){normalizeInstance(instance);instance.overrides.slotPatches[slotId]={...(instance.overrides.slotPatches[slotId]??{}),...structuredClone(patch)};touch(instance,'slot:update',{slotId,patch});return instance.overrides.slotPatches[slotId]}
export function removeInstanceSlot(instance,slotId){normalizeInstance(instance);instance.overrides.addedSlots=instance.overrides.addedSlots.filter(slot=>slot.id!==slotId);if(!instance.overrides.removedSlotIds.includes(slotId))instance.overrides.removedSlotIds.push(slotId);instance.overrides.addedEdges=instance.overrides.addedEdges.filter(edge=>edge.sourceSlotId!==slotId&&edge.targetSlotId!==slotId);instance.bindings=instance.bindings.filter(binding=>binding.slotId!==slotId);touch(instance,'slot:remove',{slotId})}
export function addInstanceEdge(instance,sourceSlotId,targetSlotId,properties={}){normalizeInstance(instance);const created={id:properties.id??`edge-${uid().slice(-8)}`,sourceSlotId,targetSlotId,direction:properties.direction??'directed',relationType:properties.relationType??'related',label:properties.label??'',routing:properties.routing??'bezier',semanticAxis:properties.semanticAxis??null};instance.overrides.addedEdges.push(created);touch(instance,'edge:add',{edgeId:created.id});return created}
export function updateInstanceEdge(instance,edgeId,patch){normalizeInstance(instance);instance.overrides.edgePatches[edgeId]={...(instance.overrides.edgePatches[edgeId]??{}),...structuredClone(patch)};touch(instance,'edge:update',{edgeId,patch});return instance.overrides.edgePatches[edgeId]}
export function removeInstanceEdge(instance,edgeId){normalizeInstance(instance);instance.overrides.addedEdges=instance.overrides.addedEdges.filter(edge=>edge.id!==edgeId);if(!instance.overrides.removedEdgeIds.includes(edgeId))instance.overrides.removedEdgeIds.push(edgeId);touch(instance,'edge:remove',{edgeId})}

export function upsertVariable(instance,variable){normalizeInstance(instance);const normalized={id:variable.id,label:variable.label??variable.id,type:variable.type??'number',kind:variable.kind??(variable.formula?'derived':'input'),value:variable.value,formula:variable.formula??'',expression:variable.expression??null,color:variable.color};const index=instance.variables.findIndex(item=>item.id===normalized.id);if(index<0)instance.variables.push(normalized);else instance.variables[index]={...instance.variables[index],...normalized};if(normalized.kind!=='derived'&&normalized.value!=null)instance.runtimeState.variables[normalized.id]=normalized.value;touch(instance,'variable:upsert',{variableId:normalized.id});return normalized}
export function removeVariable(instance,variableId){normalizeInstance(instance);instance.variables=instance.variables.filter(item=>item.id!==variableId);delete instance.runtimeState.variables[variableId];delete instance.runtimeState.results[variableId];touch(instance,'variable:remove',{variableId})}
export function setNodePosition(instance,slotId,position){normalizeInstance(instance);instance.layoutState.nodePositions[slotId]={...(instance.layoutState.nodePositions[slotId]??{}),...position};touch(instance,'layout:move',{slotId,position},{history:false})}
export function recordObjectHistory(instance,type,detail={}){normalizeInstance(instance);instance.objectHistory.push({id:uid(),type,detail:structuredClone(detail),at:now()});if(instance.objectHistory.length>250)instance.objectHistory.splice(0,instance.objectHistory.length-250)}
export function touch(instance,type,detail={},options={}){instance.updatedAt=now();if(options.history!==false)recordObjectHistory(instance,type,detail)}
export function nestedStructureCycle(instances,rootId,targetId){const byId=new Map(instances.map(item=>[item.id,item]));const seen=new Set();function visit(id){if(id===rootId)return true;if(seen.has(id))return false;seen.add(id);const current=byId.get(id);return(current?.bindings??[]).filter(binding=>binding.targetType==='structure').some(binding=>visit(binding.targetId))}return visit(targetId)}
export function cloneInstance(instance,ownerKnowledgeId=instance.ownerKnowledgeId){const clone=structuredClone(normalizeInstance(instance));return{...clone,id:uid(),ownerKnowledgeId,bindings:clone.bindings.map(binding=>({...binding,id:uid()})),objectHistory:[],createdAt:now(),updatedAt:now()}}
