import {generateBooleanAlgebra} from './boolean-algebra.js';

const slot=(id,label,role,coordinate={},accepts=['knowledge','structure'],cardinality='one')=>({id,label,role,semanticCoordinate:coordinate,accepts,cardinality});
const edge=(id,sourceSlotId,targetSlotId,direction='directed',relationType='relates',label='')=>({id,sourceSlotId,targetSlotId,direction,relationType,label});
const parameter=(id,label,type,defaultValue,extra={})=>({id,label,type,defaultValue,...extra});

export const LMN_TEMPLATE=Object.freeze({
  id:'builtin:lmn-432',name:'LMN 4–3–2',description:'Layer–Mediation–Nexus 理论结构',version:1,category:'lmn',builtin:true,nestable:true,computable:false,
  slots:[
    slot('L1','本质 / Essence','essence',{column:'L',layer:1,order:1}),slot('L2','存在 / Existence','existence',{column:'L',layer:2,order:2}),slot('L3','存在者 / Existential','existential',{column:'L',layer:3,order:3}),slot('L4','语言 / Language','language',{column:'L',layer:4,order:4}),
    slot('M1','定义 / Definition','definition',{column:'M',layer:1,order:1}),slot('M2','构成 / Constitution','constitution',{column:'M',layer:2,order:2}),slot('M3','实现 / Realization','realization',{column:'M',layer:3,order:3}),
    slot('N1','内涵 / Intension','intension',{column:'N',layer:1,order:1}),slot('N2','结构 / Structure','structure',{column:'N',layer:2,order:2})
  ],
  edges:[
    edge('e1','L1','M1','directed','defines','定义化'),edge('e2','L2','M1','directed','grounds','奠基'),edge('e3','L2','M2','directed','constitutes','构成'),edge('e4','L3','M2','directed','instantiates','实例化'),edge('e5','L3','M3','directed','realizes','实现'),edge('e6','L4','M3','directed','expresses','表达'),
    edge('e7','M1','N1','bidirectional','intensional-feedback','内涵反馈'),edge('e8','M2','N1','bidirectional','organizes','组织'),edge('e9','M2','N2','bidirectional','structural-feedback','结构反馈'),edge('e10','M3','N2','cyclic','restructures','再结构化')
  ],parameters:[],constraints:[{type:'slot-ids-exact',value:['L1','L2','L3','L4','M1','M2','M3','N1','N2']}],rules:[],layout:{type:'columns',columns:['L','M','N']},visual:{accentByColumn:{L:'#2F7658',M:'#C8922E',N:'#7657A8'}}
});

const graphTemplate=(directed=true)=>({id:`builtin:${directed?'directed':'undirected'}-graph`,name:directed?'Directed Graph':'Undirected Graph',description:'可扩展语义图',version:1,category:'graph',builtin:true,nestable:true,computable:false,slots:[slot('A','Node A','node',{order:1}),slot('B','Node B','node',{order:2}),slot('C','Node C','node',{order:3})],edges:[edge('ab','A','B',directed?'directed':'undirected','related'),edge('bc','B','C',directed?'directed':'undirected','related')],parameters:[],constraints:[],rules:[],layout:{type:'force'},visual:{accent:'#527C8B'}});

const skeleton=(id,name,category,layout='grid',roles=['source','process','target'])=>({id:`builtin:${id}`,name,description:'可编辑的结构骨架；高级计算规则可在实例中继续扩展。',version:1,category,builtin:true,nestable:true,computable:false,slots:roles.map((role,index)=>slot(`${id}-${index+1}`,role.replaceAll('-',' '),role,{layer:index,order:index},['knowledge','structure','value','variable'],'many')),edges:roles.slice(1).map((_,index)=>({...edge(`${id}-edge-${index+1}`,`${id}-${index+1}`,`${id}-${index+2}`,'directed','related'),routing:layout==='radial'?'radial-arc':layout==='tree'?'orthogonal':'bezier'})),parameters:[],variables:[],constraints:[],rules:[],layout:{type:layout},visual:{accent:'#60776d'}});

const EXTENDED_TEMPLATES=[
  skeleton('matrix-grid','Matrix / Grid','algebra','grid',['row-1','row-2','row-3']),skeleton('function-mapping','Function Mapping','algebra','columns',['domain','mapping','codomain']),skeleton('commutative-diagram','Commutative Diagram','algebra','grid',['object-a','object-b','object-c','object-d']),skeleton('dependency-dag','Dependency DAG','graph','layered',['input','dependency','output']),skeleton('state-machine','State Machine','graph','grid',['initial','state','terminal']),skeleton('timeline','Timeline','graph','timeline',['past','present','future']),skeleton('equivalence-classes','Equivalence Classes','set','grid',['class-a','class-b','class-c']),skeleton('set-partition','Set Partition','set','grid',['part-a','part-b','part-c']),skeleton('lattice','Lattice','poset','hasse',['bottom','element','top']),skeleton('proof-tree','Proof Tree','logic','tree',['premise','inference','conclusion']),skeleton('decision-tree','Decision Tree','logic','tree',['question','branch','outcome']),skeleton('cartesian-product','Cartesian Product','set','grid',['factor-a','pair','factor-b']),skeleton('permutation','Permutation','algebra','radial',['one','two','three','four']),skeleton('transformation-group','Transformation Group','algebra','radial',['identity','rotation','reflection']),skeleton('dynamical-system','Dynamical System','analysis','timeline',['state-t','evolution','state-next']),skeleton('flow-network','Flow Network','graph','layered',['source','flow','sink'])
];

export const BUILTIN_TEMPLATES=Object.freeze([
  LMN_TEMPLATE,
  graphTemplate(true),graphTemplate(false),
  {id:'builtin:poset-hasse',name:'Poset / Hasse',description:'具有偏序语义与传递约简的结构',version:1,category:'poset',builtin:true,nestable:true,computable:true,slots:[slot('bottom','Bottom','least',{layer:0,order:0}),slot('a','A','element',{layer:1,order:1}),slot('b','B','element',{layer:1,order:2}),slot('top','Top','greatest',{layer:2,order:0})],edges:[edge('ba','bottom','a','directed','precedes','≤'),edge('bb','bottom','b','directed','precedes','≤'),edge('at','a','top','directed','precedes','≤'),edge('bt','b','top','directed','precedes','≤')],parameters:[parameter('relation','Relation','string','precedes')],constraints:[{type:'acyclic'}],rules:[{type:'transitive-reduction'}],layout:{type:'hasse'},visual:{accent:'#446D82'}},
  {id:'builtin:tree',name:'Tree',description:'有根层级与父子语义',version:1,category:'graph',builtin:true,nestable:true,computable:false,slots:[slot('root','Root','root',{layer:0,order:0}),slot('left','Left','child',{layer:1,order:1}),slot('right','Right','child',{layer:1,order:2})],edges:[edge('rl','root','left','directed','parent-of'),edge('rr','root','right','directed','parent-of')],parameters:[parameter('direction','Direction','enum','top-bottom',{options:['top-bottom','left-right']})],constraints:[{type:'single-parent'}],rules:[],layout:{type:'tree'},visual:{accent:'#587B55'}},
  {id:'builtin:mod-n',name:'Modular Ring · ℤ/nℤ',description:'参数化模 N 圆环，可添加任意输入与派生变量',version:1,category:'modular',builtin:true,nestable:true,computable:true,slotFactory:'mod-n',slots:[],edges:[],parameters:[parameter('modulus','Modulus n','number',12,{min:2,max:64})],variables:[],constraints:[{type:'modulus-positive'}],rules:[],layout:{type:'radial'},visual:{accent:'#7657A8',edgeRouting:'radial-arc'}},
  {id:'builtin:mod-12',name:'Zi Wei · Mod-12',description:'紫微斗数时辰演示：文昌、文曲位置由安全公式驱动',version:2,category:'modular',builtin:true,nestable:true,computable:true,slotFactory:'mod-n',slots:[],edges:[],parameters:[parameter('modulus','Modulus','number',12,{min:2,max:64}),parameter('hour','时辰 hour','number',7,{min:0,max:11})],variables:[{id:'wenchang',label:'文昌',type:'number',kind:'derived',formula:'mod(-(hour + 2), 12)',expression:{op:'mod',args:[{op:'negate',args:[{op:'add',args:[{var:'hour'},{value:2}]}]},{value:12}]},color:'#C8922E'},{id:'wenqu',label:'文曲',type:'number',kind:'derived',formula:'mod(hour + 4, 12)',expression:{op:'mod',args:[{op:'add',args:[{var:'hour'},{value:4}]},{value:12}]},color:'#7657A8'}],constraints:[{type:'modulus-positive'}],rules:[],layout:{type:'radial'},visual:{accent:'#7657A8',edgeRouting:'radial-arc'}},
  {id:'builtin:boolean-algebra',name:'Boolean Algebra Bₙ',description:'动态生成 2ⁿ 个元素、Hasse 覆盖边与格运算',version:1,category:'algebra',builtin:true,nestable:true,computable:true,slotFactory:'boolean-algebra',slots:[],edges:[],parameters:[parameter('rank','Rank n','number',4,{min:1,max:8}),parameter('displayMode','Labels','enum','subset',{options:['subset','bitset']}),parameter('atomLabels','Atom labels','string','a,b,c,d')],variables:[],constraints:[{type:'parameter-range',parameter:'rank',min:1,max:8}],rules:[],layout:{type:'hasse'},visual:{accent:'#446D82',edgeRouting:'straight'}},
  {id:'builtin:venn-2',name:'Venn Diagram · 2 Sets',description:'保存集合区域语义而非像素位置',version:1,category:'venn',builtin:true,nestable:true,computable:false,slots:[slot('A-only','A∖B','set-region',{sets:['A'],excludes:['B']}),slot('intersection','A∩B','set-region',{sets:['A','B']}),slot('B-only','B∖A','set-region',{sets:['B'],excludes:['A']})],edges:[],parameters:[parameter('setA','Set A','string','A'),parameter('setB','Set B','string','B')],constraints:[],rules:[],layout:{type:'venn',sets:2},visual:{accent:'#687DA7'}},
  {id:'builtin:venn-3',name:'Venn Diagram · 3 Sets',description:'三集合及交集语义区域',version:1,category:'venn',builtin:true,nestable:true,computable:false,slots:[slot('A','A only','set-region',{sets:['A']}),slot('B','B only','set-region',{sets:['B']}),slot('C','C only','set-region',{sets:['C']}),slot('AB','A∩B','set-region',{sets:['A','B']}),slot('AC','A∩C','set-region',{sets:['A','C']}),slot('BC','B∩C','set-region',{sets:['B','C']}),slot('ABC','A∩B∩C','set-region',{sets:['A','B','C']})],edges:[],parameters:[],constraints:[],rules:[],layout:{type:'venn',sets:3},visual:{accent:'#687DA7'}},
  {id:'builtin:regular-polygon',name:'Regular n-gon',description:'具有顶点、边与循环顺序语义的正 n 边形',version:1,category:'geometry',builtin:true,nestable:true,computable:true,slotFactory:'regular-polygon',slots:[],edges:[],parameters:[parameter('n','边数 n','number',6,{min:3,max:24}),parameter('radius','半径','number',180)],constraints:[{type:'parameter-range',parameter:'n',min:3,max:24}],rules:[],layout:{type:'radial'},visual:{accent:'#2F7658'}},
  {id:'builtin:coordinate-plane',name:'Cartesian Coordinate Plane',description:'点具有真实 (x,y) 语义坐标',version:1,category:'coordinate',builtin:true,nestable:true,computable:true,slots:[slot('origin','Origin','origin',{x:0,y:0}),slot('P','Point P','point',{x:2,y:3}),slot('Q','Point Q','point',{x:-2,y:1})],edges:[edge('vector-op','origin','P','directed','vector','OP'),edge('vector-oq','origin','Q','directed','vector','OQ')],parameters:[parameter('scale','Scale','number',40)],constraints:[],rules:[],layout:{type:'coordinate'},visual:{accent:'#477C84'}},
  {id:'builtin:cyclic-group',name:'Cyclic Group Zₙ',description:'循环群元素与生成元作用',version:1,category:'algebra',builtin:true,nestable:true,computable:true,slotFactory:'cyclic-group',slots:[],edges:[],parameters:[parameter('n','阶 n','number',8,{min:2,max:24}),parameter('generator','生成元','number',1)],constraints:[{type:'parameter-range',parameter:'n',min:2,max:24}],rules:[],layout:{type:'radial'},visual:{accent:'#C8922E'}},
  {id:'builtin:operation-table',name:'Group Operation Table',description:'有限代数结构的 Cayley 运算表',version:1,category:'algebra',builtin:true,nestable:true,computable:true,slotFactory:'operation-table',slots:[],edges:[],parameters:[parameter('n','阶 n','number',4,{min:2,max:12}),parameter('operation','运算','enum','add-mod-n',{options:['add-mod-n','multiply-mod-n']})],constraints:[],rules:[],layout:{type:'table'},visual:{accent:'#C8922E'}},
  {id:'builtin:vector-space',name:'Vector Space Basis',description:'基、向量与线性组合结构',version:1,category:'algebra',builtin:true,nestable:true,computable:true,slots:[slot('e1','e₁','basis',{basisIndex:1}),slot('e2','e₂','basis',{basisIndex:2}),slot('v','v','vector',{coefficients:['a','b']}),slot('span','span{e₁,e₂}','subspace',{dimension:2})],edges:[edge('e1v','e1','v','directed','spans'),edge('e2v','e2','v','directed','spans'),edge('vs','v','span','directed','belongs-to')],parameters:[parameter('a','a','number',1),parameter('b','b','number',1)],constraints:[{type:'linearly-independent',slots:['e1','e2']}],rules:[],layout:{type:'coordinate'},visual:{accent:'#8B6239'}},
  {id:'builtin:free-coordinate',name:'Free Coordinate Structure',description:'带可定义语义坐标的自由结构',version:1,category:'coordinate',builtin:true,nestable:true,computable:false,slots:[slot('slot-1','Slot 1','custom',{x:0,y:0})],edges:[],parameters:[],constraints:[],rules:[],layout:{type:'manual'},visual:{accent:'#596B63'}},
  {id:'builtin:empty-custom',name:'Empty Custom Structure',description:'从 Slot、Edge、Parameter 与 Rule 开始创建模板',version:1,category:'custom',builtin:true,nestable:true,computable:false,slots:[],edges:[],parameters:[],variables:[],constraints:[],rules:[],layout:{type:'manual'},visual:{accent:'#596B63'}},
  ...EXTENDED_TEMPLATES
]);

export function materializeTemplate(template,parameters={}){
  const p=Object.fromEntries(template.parameters.map(x=>[x.id,parameters[x.id]??x.defaultValue]));
  if(template.slotFactory==='regular-polygon'){
    const n=clampInt(p.n,3,24);return{...template,slots:Array.from({length:n},(_,i)=>slot(`v${i}`,`V${i}`,'vertex',{polygonOrder:i,angle:360*i/n},['knowledge','value','variable','structure'])),edges:Array.from({length:n},(_,i)=>edge(`side-${i}`,`v${i}`,`v${(i+1)%n}`,'undirected','polygon-side','side'))};
  }
  if(template.slotFactory==='cyclic-group'){
    const n=clampInt(p.n,2,24),g=((Number(p.generator)%n)+n)%n;return{...template,slots:Array.from({length:n},(_,i)=>slot(`g${i}`,String(i),'group-element',{groupIndex:i,modularIndex:i})),edges:Array.from({length:n},(_,i)=>edge(`act-${i}`,`g${i}`,`g${(i+g)%n}`,'directed','generator-action',`+${g}`))};
  }
  if(template.slotFactory==='operation-table'){
    const n=clampInt(p.n,2,12);return{...template,slots:Array.from({length:n*n},(_,i)=>{const row=Math.floor(i/n),col=i%n,val=p.operation==='multiply-mod-n'?(row*col)%n:(row+col)%n;return slot(`cell-${row}-${col}`,String(val),'operation-result',{row,col,value:val},['knowledge','value'])}),edges:[]};
  }
  if(template.slotFactory==='mod-n'){
    const modulus=clampInt(p.modulus,2,64);return{...template,slots:Array.from({length:modulus},(_,i)=>slot(`mod-${i}`,String(i),'residue',{modularIndex:i,angle:i*360/modulus},['knowledge','value','variable','structure'],'many')),edges:Array.from({length:modulus},(_,i)=>({...edge(`cycle-${i}`,`mod-${i}`,`mod-${(i+1)%modulus}`,'cyclic','successor','+1'),routing:'radial-arc',semanticAxis:'cyclic-order'}))};
  }
  if(template.slotFactory==='boolean-algebra'){
    const generated=generateBooleanAlgebra(p.rank,{displayMode:p.displayMode,atomLabels:String(p.atomLabels??'').split(',').map(value=>value.trim()).filter(Boolean)});return{...template,slots:generated.slots,edges:generated.edges,runtimeMetadata:{warning:generated.warning,rank:generated.rank}};
  }
  return template;
}
function clampInt(value,min,max){return Math.max(min,Math.min(max,Math.round(Number(value)||min)))}
export function getBuiltinTemplate(id){return BUILTIN_TEMPLATES.find(t=>t.id===id)}
export function duplicateTemplate(template,name=`${template.name} Copy`){return{...structuredClone(template),id:crypto.randomUUID(),name,builtin:false,version:1}}
