import {generateBooleanAlgebra} from './boolean-algebra.js';
import {analyzeCyclicElement} from './cyclic-group.js';
import {analyzePoset,createPosetStarter,serializePosetRelationText} from './poset.js';
import {ensureLocalizedRecord} from '../ui/localization.js';

const slot=(id,label,role,coordinate={},accepts=['knowledge','structure'],cardinality='many')=>({id,label,role,semanticCoordinate:coordinate,accepts,cardinality});
const lmnSlot=(id,label,role,coordinate={})=>slot(id,label,role,coordinate,['knowledge','structure'],'many');
const edge=(id,sourceSlotId,targetSlotId,direction='directed',relationType='relates',label='')=>({id,sourceSlotId,targetSlotId,direction,relationType,label});
const parameter=(id,label,type,defaultValue,extra={})=>({id,label,type,defaultValue,...extra});

export const LMN_TEMPLATE=Object.freeze({
  id:'builtin:lmn-432',name:'LMN 4–3–2',description:'Layer–Mediation–Feedback 理论结构',version:2,category:'lmn',maturity:'ready',builtin:true,nestable:true,computable:false,viewCapability:{mode:'arrange',label:'可排列',defaultArrangement:'horizontal-forward',options:['horizontal-forward','horizontal-reverse','vertical-forward','vertical-reverse']},
  slots:[
    lmnSlot('L1','本质 / Essence','essence',{column:'L',layer:1,order:1}),lmnSlot('L2','存在 / Existence','existence',{column:'L',layer:2,order:2}),lmnSlot('L3','存在者 / Existential','existential',{column:'L',layer:3,order:3}),lmnSlot('L4','语言 / Language','language',{column:'L',layer:4,order:4}),
    lmnSlot('M1','定义论 / Definition','definition',{column:'M',layer:1,order:1}),lmnSlot('M2','构造论 / Construction','construction',{column:'M',layer:2,order:2}),lmnSlot('M3','实现论 / Realization','realization',{column:'M',layer:3,order:3}),
    lmnSlot('N1','符号论 / Symbolization','symbolization',{column:'N',layer:1,order:1}),lmnSlot('N2','结构论 / Structuring','structuring',{column:'N',layer:2,order:2})
  ],
  edges:[
    {...edge('e1','L1','M1','directed','mediates','定义化'),semanticAxis:'mediation-1'},{...edge('e2','M1','L2','directed','mediates','到存在'),semanticAxis:'mediation-1'},
    {...edge('e3','L2','M2','directed','mediates','构造化'),semanticAxis:'mediation-2'},{...edge('e4','M2','L3','directed','mediates','到存在者'),semanticAxis:'mediation-2'},
    {...edge('e5','L3','M3','directed','mediates','实现化'),semanticAxis:'mediation-3'},{...edge('e6','M3','L4','directed','mediates','到语言'),semanticAxis:'mediation-3'},
    {...edge('e7','N1','M1','directed','symbolic-feedback','符号化'),semanticAxis:'feedback-symbol'},{...edge('e8','N1','M2','directed','desymbolic-feedback','去符号化'),semanticAxis:'feedback-symbol'},
    {...edge('e9','N2','M2','directed','structural-feedback','结构化'),semanticAxis:'feedback-structure'},{...edge('e10','N2','M3','directed','destructural-feedback','去结构化'),semanticAxis:'feedback-structure'}
  ],parameters:[],constraints:[{type:'slot-ids-exact',value:['L1','L2','L3','L4','M1','M2','M3','N1','N2']}],rules:[],layout:{type:'lmn-semantic',columns:['L','M','N'],startY:170,gapY:132},visual:{accentByColumn:{L:'#2F7658',M:'#C8922E',N:'#7657A8'}}
});

const graphTemplate=(directed=true)=>({id:`builtin:${directed?'directed':'undirected'}-graph`,name:directed?'有向图 · Directed Graph':'无向图 · Undirected Graph',description:'稳定力导向布局的可扩展语义图',version:2,category:'graph',maturity:'ready',builtin:true,nestable:true,computable:false,slots:[slot('A','节点 A / Node A','node',{order:1}),slot('B','节点 B / Node B','node',{order:2}),slot('C','节点 C / Node C','node',{order:3})],edges:[edge('ab','A','B',directed?'directed':'undirected','related'),edge('bc','B','C',directed?'directed':'undirected','related')],parameters:[],constraints:[],rules:[],layout:{type:'force'},visual:{accent:'#527C8B'}});

const capabilityForLayout=layout=>['radial'].includes(layout)?{mode:'rotate',label:'可旋转'}:['columns','timeline','tree','hasse','layered'].includes(layout)?{mode:'arrange',label:'可排列',defaultArrangement:layout==='hasse'?'vertical-reverse':['tree','layered'].includes(layout)?'vertical-forward':'horizontal-forward',options:['horizontal-forward','horizontal-reverse','vertical-forward','vertical-reverse']}:{mode:'fixed',label:'固定视角'};
const skeleton=(id,name,category,layout='grid',roles=['source','process','target'])=>({id:`builtin:${id}`,name,description:`可直接创建、编辑节点与关系的 ${name} 工作台。`,version:2,category,maturity:'ready',builtin:true,nestable:true,computable:false,viewCapability:capabilityForLayout(layout),slots:roles.map((role,index)=>slot(`${id}-${index+1}`,role.replaceAll('-',' '),role,{layer:['layered','tree'].includes(layout)?roles.length-1-index:index,order:index},['knowledge','structure','value','variable'],'many')),edges:roles.slice(1).map((_,index)=>({...edge(`${id}-edge-${index+1}`,`${id}-${index+1}`,`${id}-${index+2}`,'directed',id,roleRelationLabel(id)),routing:layout==='radial'?'radial-arc':layout==='tree'?'orthogonal':'straight',visual:{labelPosition:'center'}})),parameters:[],variables:[],constraints:[],rules:[],layout:{type:layout},visual:{accent:'#60776d',nodeFill:'#fffefa',nodeStroke:'#91a49a',relationStyle:{color:'#71837a',width:1.7,routing:layout==='tree'?'orthogonal':'straight',labelPosition:'center'}}});
const roleRelationLabel=id=>({"function-mapping":'映射',"commutative-diagram":'态射',"dependency-dag":'依赖',"state-machine":'转移',timeline:'演化',lattice:'覆盖',"proof-tree":'推出',"decision-tree":'分支',"cartesian-product":'配对',permutation:'置换',"transformation-group":'作用',"dynamical-system":'演化',"flow-network":'流'}[id]??'关系');

const MATRIX_GRID_TEMPLATE={id:'builtin:matrix-grid',name:'矩阵 / 网格 · Matrix / Grid',nameI18n:{'zh-CN':'矩阵 / 网格',en:'Matrix / Grid'},description:'可调行列、可编辑单元格内容并保持行列坐标的交互式矩阵与网格。',version:3,category:'algebra',maturity:'ready',builtin:true,nestable:true,computable:true,parameterized:true,slotFactory:'matrix-grid',slots:[],edges:[],parameters:[parameter('rows','行数','number',3,{min:1,max:20}),parameter('columns','列数','number',3,{min:1,max:20}),parameter('cellPrefix','单元格前缀','string','a')],variables:[],constraints:[],rules:[],layout:{type:'matrix'},visual:{accent:'#527C8B',nodeFill:'#fffefa',nodeStroke:'#799187'}};

const EXTENDED_TEMPLATES=[
  MATRIX_GRID_TEMPLATE,skeleton('function-mapping','函数映射 · Function Mapping','algebra','columns',['domain','mapping','codomain']),skeleton('commutative-diagram','交换图 · Commutative Diagram','algebra','grid',['object-a','object-b','object-c','object-d']),skeleton('dependency-dag','依赖有向无环图 · Dependency DAG','graph','layered',['input','dependency','output']),skeleton('state-machine','状态机 · State Machine','graph','grid',['initial','state','terminal']),skeleton('timeline','时间线 · Timeline','graph','timeline',['past','present','future']),skeleton('equivalence-classes','等价类 · Equivalence Classes','set','grid',['class-a','class-b','class-c']),skeleton('set-partition','集合划分 · Set Partition','set','grid',['part-a','part-b','part-c']),skeleton('lattice','格 · Lattice','poset','hasse',['bottom','element','top']),skeleton('proof-tree','证明树 · Proof Tree','logic','tree',['premise','inference','conclusion']),skeleton('decision-tree','决策树 · Decision Tree','logic','tree',['question','branch','outcome']),skeleton('cartesian-product','笛卡尔积 · Cartesian Product','set','grid',['factor-a','pair','factor-b']),skeleton('permutation','置换 · Permutation','algebra','radial',['one','two','three','four']),skeleton('transformation-group','变换群 · Transformation Group','algebra','radial',['identity','rotation','reflection']),skeleton('dynamical-system','动力系统 · Dynamical System','analysis','timeline',['state-t','evolution','state-next']),skeleton('flow-network','流网络 · Flow Network','graph','layered',['source','flow','sink'])
];

export const BUILTIN_TEMPLATES=Object.freeze([
  LMN_TEMPLATE,
  graphTemplate(true),graphTemplate(false),
  {id:'builtin:poset-hasse',name:'偏序 Poset / Hasse',description:'专用偏序工作台：关系文本、覆盖关系、有效性、传递约简与格的基础检测。',version:3,category:'poset',parameterized:true,builtin:true,nestable:true,computable:true,viewCapability:{mode:'arrange',label:'可排列',defaultArrangement:'vertical-reverse',options:['horizontal-forward','horizontal-reverse','vertical-forward','vertical-reverse']},slotFactory:'poset',slots:[],edges:[],parameters:[parameter('starter','初始模型','enum','blank',{options:[{value:'blank',label:'空白偏序'},{value:'diamond',label:'四元素菱形示例'},{value:'subset',label:'集合包含'},{value:'divisibility',label:'整除关系'},{value:'numeric',label:'数值 ≤'},{value:'relation-text',label:'从关系文本导入'}]}),parameter('relationText','关系文本','textarea','a < b < c')],constraints:[{type:'acyclic'},{type:'antisymmetric'}],rules:[{type:'transitive-reduction'}],layout:{type:'hasse'},visual:{accent:'#446D82',edgeRouting:'straight'}},
  {id:'builtin:tree',name:'树 · Tree',description:'有根层级与父子语义',version:1,category:'graph',builtin:true,nestable:true,computable:false,viewCapability:{mode:'arrange',label:'可排列',defaultArrangement:'vertical-forward',options:['horizontal-forward','horizontal-reverse','vertical-forward','vertical-reverse']},slots:[slot('root','根 / Root','root',{layer:0,order:0}),slot('left','左 / Left','child',{layer:1,order:1}),slot('right','右 / Right','child',{layer:1,order:2})],edges:[edge('rl','root','left','directed','parent-of'),edge('rr','root','right','directed','parent-of')],parameters:[],constraints:[{type:'single-parent'}],rules:[],layout:{type:'tree'},visual:{accent:'#587B55'}},
  {id:'builtin:mod-n',name:'模结构 Modular Ring · ℤ/nℤ',description:'模 n 位置空间：用于周期参数、变量映射与位置计算。',version:3,category:'modular',parameterized:true,builtin:true,nestable:true,computable:true,slotFactory:'mod-n',slots:[],edges:[],parameters:[parameter('modulus','模数 n','number',12,{min:2,max:64})],variables:[],resultSpace:{type:'modular',modulusParameter:'modulus'},constraints:[{type:'modulus-positive'}],rules:[],layout:{type:'radial'},visual:{accent:'#7657A8',edgeRouting:'radial-arc'}},
  {id:'builtin:mod-12',name:'Legacy Zi Wei · Mod-12',description:'兼容旧实例；新建时请使用 Modular Ring + 紫微基础变量方案。',version:4,category:'legacy',maturity:'experimental',hidden:true,deprecated:true,replacementTemplateId:'builtin:mod-n',builtin:true,nestable:true,computable:true,slotFactory:'mod-n',slots:[],edges:[],parameters:[parameter('modulus','模数 n','number',12,{min:2,max:64}),parameter('hour','旧版时辰参数','number',7,{min:0,max:11})],variables:[{id:'wenchang',label:'文昌',type:'integer',kind:'derived',formula:'mod(-(hour + 2), modulus)',expression:{op:'mod',args:[{op:'negate',args:[{op:'add',args:[{var:'hour'},{value:2}]}]},{var:'modulus'}]},color:'#C8922E',showOnCanvas:true},{id:'wenqu',label:'文曲',type:'integer',kind:'derived',formula:'mod(hour + 4, modulus)',expression:{op:'mod',args:[{op:'add',args:[{var:'hour'},{value:4}]},{var:'modulus'}]},color:'#7657A8',showOnCanvas:true}],resultSpace:{type:'modular',modulusParameter:'modulus'},constraints:[{type:'modulus-positive'}],rules:[],layout:{type:'radial'},visual:{accent:'#7657A8',edgeRouting:'radial-arc'}},
  {id:'builtin:boolean-algebra',name:'布尔代数 Boolean Algebra Bₙ',description:'动态生成 2ⁿ 个元素、Hasse 覆盖边与格运算',version:2,category:'algebra',parameterized:true,builtin:true,nestable:true,computable:true,slotFactory:'boolean-algebra',slots:[],edges:[],parameters:[parameter('rank','维数 n','number',4,{min:1,max:8}),parameter('displayMode','标签形式','enum','subset',{options:[{value:'subset',label:'子集'},{value:'bitset',label:'位串'}]}),parameter('atomLabels','原子标签','string','a,b,c,d')],variables:[],constraints:[{type:'parameter-range',parameter:'rank',min:1,max:8}],rules:[],layout:{type:'hasse'},visual:{accent:'#446D82',edgeRouting:'straight'}},
  {id:'builtin:venn-2',name:'韦恩图 · Venn Diagram · 2 Sets',description:'保存集合区域语义而非像素位置',version:1,category:'venn',builtin:true,nestable:true,computable:false,slots:[slot('A-only','A∖B','set-region',{sets:['A'],excludes:['B']}),slot('intersection','A∩B','set-region',{sets:['A','B']}),slot('B-only','B∖A','set-region',{sets:['B'],excludes:['A']})],edges:[],parameters:[parameter('setA','集合 A / Set A','string','A'),parameter('setB','集合 B / Set B','string','B')],constraints:[],rules:[],layout:{type:'venn',sets:2},visual:{accent:'#687DA7'}},
  {id:'builtin:venn-3',name:'韦恩图 · Venn Diagram · 3 Sets',description:'三集合及交集语义区域',version:1,category:'venn',builtin:true,nestable:true,computable:false,slots:[slot('A','A only','set-region',{sets:['A']}),slot('B','B only','set-region',{sets:['B']}),slot('C','C only','set-region',{sets:['C']}),slot('AB','A∩B','set-region',{sets:['A','B']}),slot('AC','A∩C','set-region',{sets:['A','C']}),slot('BC','B∩C','set-region',{sets:['B','C']}),slot('ABC','A∩B∩C','set-region',{sets:['A','B','C']})],edges:[],parameters:[],constraints:[],rules:[],layout:{type:'venn',sets:3},visual:{accent:'#687DA7'}},
  {id:'builtin:regular-polygon',name:'正 n 边形 Regular n-gon',description:'具有顶点、边与循环顺序语义的正 n 边形',version:1,category:'geometry',parameterized:true,builtin:true,nestable:true,computable:true,slotFactory:'regular-polygon',slots:[],edges:[],parameters:[parameter('n','边数 n','number',6,{min:3,max:24}),parameter('radius','半径','number',180,{min:80,max:360})],constraints:[{type:'parameter-range',parameter:'n',min:3,max:24}],rules:[],layout:{type:'radial'},visual:{accent:'#2F7658'}},
  {id:'builtin:coordinate-plane',name:'向量空间 Vector Space',description:'统一二维/三维向量、点、参数曲线、动态点与曲面的无限作图工作台。',version:5,category:'coordinate',parameterized:true,builtin:true,nestable:true,computable:true,viewCapability:{mode:'fixed',label:'坐标视角'},slots:[slot('origin','O','origin',{x:0,y:0,z:0}),slot('P','P','point',{x:2,y:3,z:0}),slot('Q','Q','point',{x:-2,y:1,z:0})],edges:[edge('vector-op','origin','P','directed','vector','OP'),edge('vector-oq','origin','Q','directed','vector','OQ')],parameters:[parameter('dimension','维数','enum','2d',{options:[{value:'2d',label:'二维平面'},{value:'3d',label:'三维空间'}]}),parameter('scale','单位缩放','number',40,{min:16,max:120})],constraints:[],rules:[],layout:{type:'coordinate'},visual:{accent:'#477C84',nodeFill:'#929895',nodeStroke:'#1e2723',relationStyle:{color:'#5f7168',width:1.8,routing:'straight',labelPosition:'center'}}},
  {id:'builtin:cyclic-group',name:'循环群 Cyclic Group · Cₙ',description:'群元素、选定元素的作用、元素阶、生成子群与 Cayley 图解释。',version:3,category:'algebra',parameterized:true,builtin:true,nestable:true,computable:true,slotFactory:'cyclic-group',slots:[],edges:[],parameters:[parameter('n','阶 n','number',8,{min:2,max:64}),parameter('generator','选定元素 / 作用步长','number',1,{min:0,max:63}),parameter('notation','显示记号','enum','cyclic',{options:[{value:'cyclic',label:'Cₙ'},{value:'quotient',label:'ℤ/nℤ'}]})],constraints:[{type:'parameter-range',parameter:'n',min:2,max:64}],rules:[],layout:{type:'radial'},visual:{accent:'#C8922E'}},
  {id:'builtin:operation-table',name:'有限运算表 Finite Operation Table',description:'有限集合上的运算表；不预设该运算一定构成群。',version:2,category:'algebra',parameterized:true,builtin:true,nestable:true,computable:true,slotFactory:'operation-table',slots:[],edges:[],parameters:[parameter('n','元素数量 n','number',4,{min:2,max:12}),parameter('operation','运算','enum','add-mod-n',{options:[{value:'add-mod-n',label:'模 n 加法'},{value:'multiply-mod-n',label:'模 n 乘法'}]})],constraints:[],rules:[],layout:{type:'table'},visual:{accent:'#C8922E'}},
  {id:'builtin:vector-space',name:'向量空间基 · Vector Space Basis · Legacy',description:'已合并到“向量空间 Vector Space”；旧实例继续兼容。',version:2,category:'legacy',maturity:'experimental',hidden:true,deprecated:true,replacementTemplateId:'builtin:coordinate-plane',builtin:true,nestable:true,computable:true,slots:[slot('e1','e₁','basis',{x:1,y:0,z:0,basisIndex:1}),slot('e2','e₂','basis',{x:0,y:1,z:0,basisIndex:2}),slot('v','v','vector',{x:1,y:1,z:0}),slot('span','span{e₁,e₂}','subspace',{x:0,y:0,z:0,dimension:2})],edges:[edge('e1v','e1','v','directed','spans'),edge('e2v','e2','v','directed','spans'),edge('vs','v','span','directed','belongs-to')],parameters:[parameter('dimension','维数','enum','2d',{options:[{value:'2d',label:'二维平面'},{value:'3d',label:'三维空间'}]}),parameter('scale','单位缩放','number',40,{min:24,max:80})],constraints:[{type:'linearly-independent',slots:['e1','e2']}],rules:[],layout:{type:'coordinate'},visual:{accent:'#8B6239'}},
  {id:'builtin:free-coordinate',name:'自由坐标结构 · Free Coordinate Structure',description:'带可定义语义坐标的自由结构',version:1,category:'coordinate',builtin:true,nestable:true,computable:false,slots:[slot('slot-1','位置 1 / Slot 1','custom',{x:0,y:0})],edges:[],parameters:[],constraints:[],rules:[],layout:{type:'manual'},visual:{accent:'#596B63'}},
  {id:'builtin:empty-custom',name:'空白自定义结构 · Empty Custom Structure',description:'从 Slot、Edge、Parameter 与 Rule 开始创建模板',version:1,category:'custom',builtin:true,nestable:true,computable:false,slots:[],edges:[],parameters:[],variables:[],constraints:[],rules:[],layout:{type:'manual'},visual:{accent:'#596B63'}},
  ...EXTENDED_TEMPLATES
].map(template=>Object.freeze(ensureLocalizedRecord({...template,maturity:template.maturity??'ready'}))));

export function materializeTemplate(template,parameters={}){
  const p=Object.fromEntries(template.parameters.map(x=>[x.id,parameters[x.id]??x.defaultValue]));
  if(template.slotFactory==='matrix-grid'){
    const rows=clampInt(p.rows,1,20),columns=clampInt(p.columns,1,20),prefix=String(p.cellPrefix??'a').trim()||'a';return{...template,slots:Array.from({length:rows*columns},(_,index)=>{const row=Math.floor(index/columns),col=index%columns;return slot(`cell-${row+1}-${col+1}`,`${prefix}${row+1}${col+1}`,'matrix-cell',{row:row+1,col:col+1,matrixIndex:index},['knowledge','structure','value','variable'],'many')}),edges:[],runtimeMetadata:{matrix:{rows,columns}}};
  }
  if(template.slotFactory==='regular-polygon'){
    const n=clampInt(p.n,3,24);return{...template,slots:Array.from({length:n},(_,i)=>slot(`v${i}`,`V${i}`,'vertex',{polygonOrder:i,angle:360*i/n},['knowledge','value','variable','structure'])),edges:Array.from({length:n},(_,i)=>edge(`side-${i}`,`v${i}`,`v${(i+1)%n}`,'directed','polygon-side','side'))};
  }
  if(template.slotFactory==='cyclic-group'){
    const n=clampInt(p.n,2,64),g=((Number(p.generator)%n)+n)%n,analysis=analyzeCyclicElement(n,g);return{...template,slots:Array.from({length:n},(_,i)=>slot(`g${i}`,String(i),'group-element',{groupIndex:i,modularIndex:i})),edges:Array.from({length:n},(_,i)=>edge(`act-${i}`,`g${i}`,`g${(i+g)%n}`,'directed','action-step',`+${g}`)),runtimeMetadata:{cyclic:analysis,notation:p.notation??'cyclic'}};
  }
  if(template.slotFactory==='operation-table'){
    const n=clampInt(p.n,2,12);return{...template,slots:Array.from({length:n*n},(_,i)=>{const row=Math.floor(i/n),col=i%n,val=p.operation==='multiply-mod-n'?(row*col)%n:(row+col)%n;return slot(`cell-${row}-${col}`,String(val),'operation-result',{row,col,value:val},['knowledge','value'])}),edges:[]};
  }
  if(template.slotFactory==='mod-n'){
    const modulus=clampInt(p.modulus,2,64);return{...template,slots:Array.from({length:modulus},(_,i)=>slot(`mod-${i}`,String(i),'residue',{modularIndex:i,angle:i*360/modulus},['knowledge','value','variable','structure'],'many')),edges:Array.from({length:modulus},(_,i)=>({...edge(`cycle-${i}`,`mod-${i}`,`mod-${(i+1)%modulus}`,'cyclic','successor','+1'),routing:'radial-arc',semanticAxis:'cyclic-order'}))};
  }
  if(template.slotFactory==='poset'){
    const generated=createPosetStarter(p.starter,p.relationText),analysis=analyzePoset(generated.slots,generated.edges);return{...template,slots:generated.slots,edges:analysis.reduction,runtimeMetadata:{poset:analysis,relationText:serializePosetRelationText(generated.slots,analysis.reduction)}};
  }
  if(template.slotFactory==='boolean-algebra'){
    const generated=generateBooleanAlgebra(p.rank,{displayMode:p.displayMode,atomLabels:String(p.atomLabels??'').split(',').map(value=>value.trim()).filter(Boolean)});return{...template,slots:generated.slots,edges:generated.edges,runtimeMetadata:{warning:generated.warning,rank:generated.rank}};
  }
  return template;
}
function clampInt(value,min,max){return Math.max(min,Math.min(max,Math.round(Number(value)||min)))}
export function getBuiltinTemplate(id){return BUILTIN_TEMPLATES.find(t=>t.id===id)}
export function duplicateTemplate(template,name=`${template.name} Copy`){return{...structuredClone(template),id:crypto.randomUUID(),name,builtin:false,version:1}}
