import {createKnowledge,createNamedKnowledge,createRelation,createLMN,validateLMN,neighborhood,transitiveReduction,exportBundle,validateImport,mergeImport,deletionImpact,LMN_POSITIONS} from '../../packages/domain/core.js';
import * as db from './db.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const POS_META={L1:['本质','Essence'],L2:['存在','Existence'],L3:['存在者','Existential'],L4:['语言','Language'],M1:['定义','Definition'],M2:['构成','Constitution'],M3:['实现','Realization'],N1:['内涵','Intension'],N2:['结构','Structure']};
const THEORY_EDGES=[['L1','M1','lm'],['L2','M1','lm'],['L2','M2','lm'],['L3','M2','lm'],['L3','M3','lm'],['L4','M3','lm'],['M1','N1','mn'],['M2','N1','mn'],['M2','N2','mn'],['M3','N2','mn']];
const semantic={knowledge:[],relations:[],representations:[],lmns:[],structures:[]};
const ui={selectedPosition:null,selectedRelation:null,selectedIds:new Set(),inspectorTab:'info',zoom:1,pan:{x:0,y:0},presentation:'lmn',showAxis:true,showRelations:true,showSummary:true,showLabels:true,focus:false,explorerHidden:false,inspectorHidden:false,path:[],back:[],forward:[],recent:[],favorites:[],expanded:[],offsets:{},connect:null,undo:[],redo:[],saving:false};
let currentId=null,saveTimer=null,relationRAF=null,drag=null,box=null,pendingImport=null;
const knowledge=id=>semantic.knowledge.find(k=>k.id===id),current=()=>knowledge(currentId),lmnFor=id=>semantic.lmns.find(l=>l.knowledgeId===id);

async function boot(){
  for(const key of Object.keys(semantic))semantic[key]=await db.list(key);
  const saved=(await db.list('settings')).find(x=>x.id==='workspace-v2');if(saved)Object.assign(ui,saved.data,{selectedIds:new Set(),undo:[],redo:[],connect:null});
  for(const k of semantic.knowledge)if(!lmnFor(k.id)){const l=createLMN(k.id);semantic.lmns.push(l);await db.put('lmns',l)}
  currentId=ui.recent.find(id=>knowledge(id))||semantic.knowledge[0]?.id||null;if(currentId&&!ui.path.length)ui.path=[{knowledgeId:currentId,position:null}];
  if(matchMedia('(max-width:1100px)').matches){ui.explorerHidden=true;ui.inspectorHidden=true}
  bind();render();if(!localStorage.getItem('lmn-v2-welcome')&&currentId){setTimeout(()=>{status('提示：点击 Position 创建或引用 Knowledge；双击进入；Space 原位展开。');localStorage.setItem('lmn-v2-welcome','1')},500)}
  if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
}

function bind(){
  $('#newKnowledge').onclick=$('#welcomeCreate').onclick=quickCreate;$('#search').oninput=renderExplorer;$('#globalSearch').onclick=openPalette;
  $('#toggleExplorer').onclick=$('#collapseExplorer').onclick=()=>{ui.explorerHidden=!ui.explorerHidden;renderShell();saveUI()};$('#toggleInspector').onclick=()=>{ui.inspectorHidden=!ui.inspectorHidden;renderShell();saveUI()};
  $('#backBtn').onclick=goBack;$('#forwardBtn').onclick=goForward;$('#connectBtn').onclick=startConnect;$('#cancelConnect').onclick=cancelConnect;
  $('#viewBtn').onclick=e=>showViewMenu(e.currentTarget);$('#presentationButton').onclick=e=>showViewMenu(e.currentTarget);$('#exportBtn').onclick=exportData;
  $('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#fitBtn').onclick=fitView;$('#focusBtn').onclick=toggleFocus;
  $('#zoomIn').onclick=()=>setZoom(ui.zoom+.15);$('#zoomOut').onclick=()=>setZoom(ui.zoom-.15);$('#zoomReset').onclick=()=>setZoom(1);
  $$('.inspector-tabs button').forEach(b=>b.onclick=()=>{ui.inspectorTab=b.dataset.tab;renderInspector()});
  $$('.section-toggle').forEach(b=>b.onclick=()=>{const list=$(`#${b.dataset.section}List`);list.classList.toggle('collapsed');b.querySelector('span').textContent=(list.classList.contains('collapsed')?'› ':'⌄ ')+b.querySelector('span').textContent.slice(2)});
  $('#fileInput').onchange=readImport;$('#importDialog').addEventListener('close',()=>{if($('#importDialog').returnValue==='confirm')applyImport()});
  $('#commandInput').oninput=renderCommands;$('#commandPalette').addEventListener('close',()=>{$('#commandInput').value=''});
  matchMedia('(max-width:1100px)').addEventListener('change',e=>{if(e.matches){ui.explorerHidden=true;ui.inspectorHidden=true}renderShell();setTimeout(scheduleEdges,220)});
  const vp=$('#canvasViewport');vp.addEventListener('wheel',onWheel,{passive:false});vp.addEventListener('pointerdown',onCanvasDown);vp.addEventListener('dblclick',e=>{if(e.target===vp||e.target===$('#canvasStage'))toggleFocus()});
  document.addEventListener('pointermove',onPointerMove);document.addEventListener('pointerup',onPointerUp);document.addEventListener('click',e=>{if(!e.target.closest('.popover')&&!e.target.closest('.position-card'))hide('#inlinePicker');if(!e.target.closest('.context-menu'))hide('#contextMenu')});
  document.addEventListener('keydown',keys);window.addEventListener('resize',()=>scheduleEdges());
}

function render(){renderShell();renderExplorer();renderBreadcrumb();renderWorkspace();renderInspector();renderStatus();}
function renderShell(){const shell=$('#appShell');shell.classList.toggle('explorer-hidden',ui.explorerHidden);shell.classList.toggle('inspector-hidden',ui.inspectorHidden);shell.classList.toggle('focus-mode',ui.focus);$('#backBtn').disabled=!ui.back.length;$('#forwardBtn').disabled=!ui.forward.length}
function relationCount(id){return semantic.relations.filter(r=>r.sourceId===id||r.targetId===id).length}
function isOrphan(k){const l=lmnFor(k.id);return relationCount(k.id)===0&&(!l||Object.values(l.positions).every(p=>!p.knowledgeId))}
function renderExplorer(){const q=$('#search').value.trim().toLowerCase(),filter=list=>list.map(knowledge).filter(Boolean).filter(k=>(k.title+' '+k.content).toLowerCase().includes(q));const all=semantic.knowledge.filter(k=>(k.title+' '+k.content).toLowerCase().includes(q)),recent=filter(ui.recent).slice(0,6),fav=filter(ui.favorites),orph=all.filter(isOrphan);fillList('#recentList',recent);fillList('#favoriteList',fav);fillList('#orphanList',orph);fillList('#allList',all);$('#recentCount').textContent=recent.length;$('#favoriteCount').textContent=fav.length;$('#orphanCount').textContent=orph.length;$('#allCount').textContent=all.length}
function fillList(selector,items){$(selector).innerHTML=items.map(k=>`<div class="knowledge-item ${k.id===currentId?'active':''}" data-id="${k.id}"><span>${esc(k.title)}</span><small>${relationCount(k.id)} relations · ${relativeTime(k.updatedAt)}</small><button class="knowledge-more" title="更多">⋯</button></div>`).join('');$(selector).querySelectorAll('.knowledge-item').forEach(el=>{el.onclick=e=>{if(e.target.closest('.knowledge-more'))return showKnowledgeMenu(el,e);navigate(el.dataset.id,null)};el.oncontextmenu=e=>{e.preventDefault();showKnowledgeMenu(el,e)}})}
function renderBreadcrumb(){$('#breadcrumbs').innerHTML=ui.path.map((p,i)=>`${p.position?`<span class="crumb-position">› ${p.position} ${POS_META[p.position][0]} ›</span>`:''}<button class="crumb" data-i="${i}">${esc(knowledge(p.knowledgeId)?.title||'Missing')}</button>`).join('');$$('.crumb').forEach(b=>b.onclick=()=>jumpPath(Number(b.dataset.i)))}
function navigate(id,position,track=true){if(!knowledge(id))return;if(track&&currentId){ui.back.push({id:currentId,path:structuredClone(ui.path)});ui.forward=[]}currentId=id;ui.path=position?[...ui.path,{knowledgeId:id,position}]:[{knowledgeId:id,position:null}];ui.recent=[id,...ui.recent.filter(x=>x!==id)].slice(0,20);ui.selectedPosition=null;ui.selectedRelation=null;ui.selectedIds.clear();ui.expanded=[];render();saveUI()}
function jumpPath(i){const target=ui.path[i];if(!target)return;ui.back.push({id:currentId,path:structuredClone(ui.path)});currentId=target.knowledgeId;ui.path=ui.path.slice(0,i+1);ui.forward=[];ui.selectedPosition=null;render();saveUI()}
function goBack(){const x=ui.back.pop();if(!x)return;ui.forward.push({id:currentId,path:structuredClone(ui.path)});currentId=x.id;ui.path=x.path;ui.selectedPosition=null;render();saveUI()}
function goForward(){const x=ui.forward.pop();if(!x)return;ui.back.push({id:currentId,path:structuredClone(ui.path)});currentId=x.id;ui.path=x.path;ui.selectedPosition=null;render();saveUI()}

function renderWorkspace(){const k=current();$('#welcome').classList.toggle('hidden',!!k);$('#canvasViewport').classList.toggle('hidden',!k);$('#workspaceTitle').textContent=k?`${k.title} · LMN 4–3–2`:'LMN 4–3–2';$('#presentationButton').textContent=labelPresentation(ui.presentation)+'⌄';if(!k)return;if(ui.presentation==='lmn')renderLMN();else renderAlternative();applyTransform();scheduleEdges()}
function renderLMN(){const l=lmnFor(currentId);if(!l||!validateLMN(l).valid)return;const columns=$('#lmnColumns');columns.innerHTML=['L','M','N'].map(g=>`<section class="lmn-column" data-group="${g}"><header class="column-heading"><b>${g}</b><span>${g==='L'?'Layer · 存在的维度':g==='M'?'Mediation · 中介的维度':'Nexus · 内涵的维度'}</span></header>${LMN_POSITIONS.filter(p=>p.group===g).map(p=>positionCard(p,l.positions[p.id])).join('')}</section>`).join('');columns.classList.toggle('axis-hidden',!ui.showAxis);columns.classList.toggle('summary-hidden',!ui.showSummary);columns.classList.toggle('labels-hidden',!ui.showLabels);$('#expandedLMNs').innerHTML=ui.expanded.map(expandedCard).join('');bindCards();$$('[data-enter]').forEach(b=>b.onclick=()=>navigate(b.dataset.enter,null));$$('[data-collapse]').forEach(b=>b.onclick=()=>{ui.expanded=ui.expanded.filter(x=>x.knowledgeId!==b.dataset.collapse);renderWorkspace()});setDensity()}
function positionCard(p,slot){const k=knowledge(slot.knowledgeId),count=k?relationCount(k.id):0,recursive=k&&lmnFor(k.id)&&Object.values(lmnFor(k.id).positions).some(x=>x.knowledgeId);const selected=ui.selectedPosition===p.id?'selected':'',offset=ui.offsets[`${currentId}:${p.id}`]||{x:0,y:0};return `<article class="position-card ${k?'referenced':'empty'} ${selected}" data-position="${p.id}" data-id="${k?.id||''}" data-group="${p.group}" style="translate:${offset.x}px ${offset.y}px"><div class="card-top"><span class="position-code">${p.id}</span><span class="position-name">${POS_META[p.id][0]} / ${POS_META[p.id][1]}</span></div>${k?`<div class="knowledge-name">${esc(k.title)}</div><div class="knowledge-summary">${esc(summary(k))}</div><div class="card-meta"><span>⌘ ${count} ${recursive?' · 递归':''}</span><span class="card-actions"><button data-action="expand" title="原位展开">⊞</button><button data-action="enter" title="进入 Knowledge">↗</button></span></div>`:`<div class="empty-action">＋ 添加 Knowledge</div><div class="knowledge-summary">引用已有或立即创建</div>`}</article>`}
function bindCards(){$$('.position-card').forEach(card=>{card.onclick=e=>cardClick(card,e);card.ondblclick=e=>{e.stopPropagation();const id=card.dataset.id;if(id)navigate(id,card.dataset.position);else showPicker(card)};card.oncontextmenu=e=>{e.preventDefault();showPositionMenu(card,e)};card.onmouseenter=()=>highlightPosition(card.dataset.position,true);card.onmouseleave=()=>highlightPosition(card.dataset.position,false);card.onpointerdown=e=>{if(e.button===0&&!e.target.closest('button'))startCardDrag(card,e)};card.querySelector('[data-action=enter]')?.addEventListener('click',e=>{e.stopPropagation();navigate(card.dataset.id,card.dataset.position)});card.querySelector('[data-action=expand]')?.addEventListener('click',e=>{e.stopPropagation();expandPosition(card.dataset.position)})})}
function cardClick(card,e){const position=card.dataset.position,id=card.dataset.id;if(ui.connect){completeConnect(id||currentId);return}if(e.shiftKey&&id){ui.selectedIds.has(id)?ui.selectedIds.delete(id):ui.selectedIds.add(id)}else{ui.selectedIds.clear();if(id)ui.selectedIds.add(id)}ui.selectedPosition=position;ui.selectedRelation=null;renderLMN();renderInspector();renderStatus();if(!id)showPicker(card)}
function showPicker(card){const position=card.dataset.position,p=$('#inlinePicker'),rect=card.getBoundingClientRect(),vp=$('#canvasViewport').getBoundingClientRect();p.style.left=Math.min(vp.width-275,rect.right-vp.left+8)+'px';p.style.top=Math.max(8,rect.top-vp.top)+'px';p.innerHTML=`<input id="pickerSearch" placeholder="搜索已有 Knowledge…"><div class="picker-list"><button class="picker-item picker-create" data-create>＋ 新建 Knowledge</button>${semantic.knowledge.filter(k=>k.id!==currentId).slice(0,12).map(k=>`<button class="picker-item" data-id="${k.id}">${esc(k.title)}</button>`).join('')}</div>`;p.classList.remove('hidden');p.querySelector('[data-create]').onclick=()=>inlineCreate(position);p.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>assignPosition(position,b.dataset.id));p.querySelector('input').oninput=e=>{const q=e.target.value.toLowerCase();p.querySelectorAll('[data-id]').forEach(b=>b.classList.toggle('hidden',!knowledge(b.dataset.id).title.toLowerCase().includes(q)))};p.querySelector('input').focus()}
async function inlineCreate(position){const input=$('#pickerSearch'),title=input.value.trim()||prompt('Knowledge 名称');if(!title)return;checkpoint();const {knowledge:k,lmn:l}=createNamedKnowledge(title);semantic.knowledge.push(k);semantic.lmns.push(l);await Promise.all([db.put('knowledge',k),db.put('lmns',l)]);await assignPosition(position,k.id,false)}
async function assignPosition(position,id,history=true){if(history)checkpoint();const l=lmnFor(currentId);l.positions[position].knowledgeId=id;l.updatedAt=new Date().toISOString();await db.put('lmns',l);hide('#inlinePicker');saved();render()}
async function clearPosition(position){checkpoint();const l=lmnFor(currentId);l.positions[position].knowledgeId=null;l.updatedAt=new Date().toISOString();await db.put('lmns',l);ui.selectedPosition=null;saved();render()}
function expandPosition(position){const id=lmnFor(currentId)?.positions[position]?.knowledgeId;if(!id)return;const cycle=ui.expanded.some(x=>x.knowledgeId===id)||ui.path.some(x=>x.knowledgeId===id);if(cycle)return status('检测到递归循环：已阻止重复原位展开。');ui.expanded.push({knowledgeId:id,from:position,depth:ui.path.length});renderWorkspace();renderStatus();saveUI()}
function expandedCard(x){const k=knowledge(x.knowledgeId),l=lmnFor(x.knowledgeId);return `<div class="child-lmn" data-id="${x.knowledgeId}"><div class="child-head"><b>${esc(k?.title||'Missing')}</b><span><button data-enter="${x.knowledgeId}">进入</button><button data-collapse="${x.knowledgeId}">×</button></span></div><div class="child-grid">${['L','M','N'].map(g=>`<div class="child-col">${LMN_POSITIONS.filter(p=>p.group===g).map(p=>`<div class="child-node" style="--accent:var(--${g.toLowerCase()})">${p.id} ${esc(knowledge(l?.positions[p.id]?.knowledgeId)?.title||'')}</div>`).join('')}</div>`).join('')}</div></div>`}

function renderAlternative(){const p=neighborhood(semantic.knowledge,semantic.relations,currentId,2);$('#expandedLMNs').innerHTML='';if(ui.presentation==='hasse'){const r=transitiveReduction(p.nodes.map(n=>n.id),p.edges),remaining=new Set(p.nodes.map(n=>n.id)),levels=[];while(remaining.size){const level=[...remaining].filter(id=>!r.edges.some(e=>e.targetId===id&&remaining.has(e.sourceId)));if(!level.length)break;levels.push(level);level.forEach(id=>remaining.delete(id))}$('#lmnColumns').innerHTML=`<section class="representation-canvas"><h2>Hasse Representation</h2>${r.warning?`<p class="danger">${r.warning}</p>`:''}${levels.reverse().map(level=>`<div class="hasse-level">${level.map(id=>`<button class="rep-node" data-id="${id}">${esc(knowledge(id)?.title)}</button>`).join('')}</div>`).join('')}</section>`}else{$('#lmnColumns').innerHTML=`<section class="representation-canvas"><h2>${labelPresentation(ui.presentation)}</h2><div class="rep-network">${p.nodes.map((n,i)=>`<button class="rep-node" data-id="${n.id}" style="--i:${i}">${esc(n.title)}</button>`).join('')}</div></section>`}$$('.rep-node').forEach(n=>n.onclick=()=>navigate(n.dataset.id,null));setDensity()}
function labelPresentation(x){return({lmn:'默认 LMN',free:'自由图',tree:'树状图',mind:'思维导图',hasse:'偏序 / Hasse',hierarchy:'层级图',timeline:'时间轴'})[x]||x}
function setPresentation(value){checkpoint();ui.presentation=value;semantic.representations.push({id:crypto.randomUUID(),knowledgeId:currentId,kind:value==='lmn'?'lmn':'structure',data:{layout:value,zoom:ui.zoom},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});db.put('representations',semantic.representations.at(-1));renderWorkspace();renderInspector();saveUI()}

function scheduleEdges(){cancelAnimationFrame(relationRAF);relationRAF=requestAnimationFrame(drawEdges)}
function drawEdges(){const svg=$('#relationLayer');if(ui.presentation!=='lmn'){svg.innerHTML='';return}const stage=$('#canvasStage'),sr=stage.getBoundingClientRect(),paths=[];for(const [a,b,type] of THEORY_EDGES){const A=$(`.position-card[data-position=${a}]`),B=$(`.position-card[data-position=${b}]`);if(!A||!B)continue;paths.push(edgePath(A,B,type,`${a}-${b}`))}if(ui.showRelations){const slots=Object.fromEntries(Object.entries(lmnFor(currentId)?.positions||{}).map(([p,x])=>[x.knowledgeId,p]).filter(x=>x[0]));for(const r of semantic.relations){const a=slots[r.sourceId],b=slots[r.targetId];if(a&&b){const A=$(`.position-card[data-position=${a}]`),B=$(`.position-card[data-position=${b}]`);paths.push(edgePath(A,B,'free',r.id,true))}}}svg.setAttribute('viewBox',`0 0 ${sr.width} ${Math.max(sr.height,650)}`);svg.innerHTML=`<defs><marker id="arrow-lm" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="var(--l)"/></marker><marker id="arrow-mn" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="var(--m)"/></marker><marker id="arrow-free" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="#7d8790"/></marker></defs>${paths.join('')}`;svg.querySelectorAll('.edge-hit').forEach(hit=>{hit.onmouseenter=()=>highlightEdge(hit.dataset.key,true);hit.onmouseleave=()=>highlightEdge(hit.dataset.key,false);hit.onclick=()=>selectEdge(hit.dataset.key)})}
function edgePath(A,B,type,key,free=false){const sr=$('#canvasStage').getBoundingClientRect(),a=A.getBoundingClientRect(),b=B.getBoundingClientRect(),x1=a.right-sr.left,y1=a.top+a.height/2-sr.top,x2=b.left-sr.left,y2=b.top+b.height/2-sr.top,mid=(x1+x2)/2,d=`M${x1},${y1} C${mid},${y1} ${mid},${y2} ${x2},${y2}`;return `<path class="relation-edge ${type} ${ui.selectedRelation===key?'selected':''}" data-key="${key}" d="${d}" marker-end="url(#arrow-${type})"/><path class="edge-hit" data-key="${key}" d="${d}" data-free="${free}"/>`}
function highlightPosition(p,on){const related=new Set(THEORY_EDGES.filter(e=>e[0]===p||e[1]===p).flatMap(e=>[e[0],e[1]]));$$('.position-card').forEach(c=>{c.classList.toggle('related-hot',on&&related.has(c.dataset.position));c.classList.toggle('related-dim',on&&!related.has(c.dataset.position))});$$('.relation-edge').forEach(e=>{const hot=related.size&&[...related].some(x=>e.dataset.key.includes(x));e.classList.toggle('hot',on&&hot);e.classList.toggle('dim',on&&!hot)})}
function highlightEdge(key,on){$(`.relation-edge[data-key="${key}"]`)?.classList.toggle('hot',on)}
function selectEdge(key){ui.selectedRelation=key;ui.selectedPosition=null;ui.inspectorTab='relations';renderInspector();drawEdges()}

function renderInspector(){const k=current(),position=ui.selectedPosition,slot=position?lmnFor(currentId)?.positions[position]:null,target=knowledge(slot?.knowledgeId)||k;$$('.inspector-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===ui.inspectorTab));if(!k){$('#inspectorContent').innerHTML='<p class="muted">创建或选择 Knowledge。</p>';return}if(ui.selectedIds.size>1){renderMultiInspector();return}if(ui.inspectorTab==='info')renderInfo(target,position);if(ui.inspectorTab==='relations')renderRelations(target,position);if(ui.inspectorTab==='presentation')renderPresentation();if(ui.inspectorTab==='notes')renderNotes(target)}
function renderInfo(k,position){if(!k&&position){$('#inspectorContent').innerHTML=`<span class="eyebrow">Empty Position</span><h2>${position} ${POS_META[position][0]} / ${POS_META[position][1]}</h2><p class="muted">此位置尚未引用 Knowledge。</p><button id="infoAssign">＋ 创建或引用</button>`;$('#infoAssign').onclick=()=>showPicker($(`.position-card[data-position=${position}]`));return}const impact=deletionImpact(semantic,k.id),fav=ui.favorites.includes(k.id);$('#inspectorContent').innerHTML=`<span class="eyebrow">${position?`${position} · ${POS_META[position][1]}`:'Knowledge'}</span><h2>${esc(k.title)} <button id="favoriteBtn" class="icon-button">${fav?'★':'☆'}</button></h2><div class="field"><label>名称</label><input id="infoTitle" value="${esc(k.title)}"></div><div class="field"><label>摘要</label><textarea id="infoSummary">${esc(k.summary||summary(k))}</textarea></div><div class="info-grid"><dt>关系</dt><dd>${relationCount(k.id)}</dd><dt>LMN 引用</dt><dd>${impact.lmnReferences.length}</dd><dt>递归深度</dt><dd>${ui.path.length-1}</dd><dt>更新时间</dt><dd>${new Date(k.updatedAt).toLocaleString()}</dd><dt>UUID</dt><dd>${k.id.slice(0,8)}…</dd></div><div class="field"><button id="openKnowledge">打开 Knowledge</button> ${position?'<button id="expandKnowledge">展开 LMN</button>':''}</div>${position?'<button id="removeReference" class="danger">移除引用</button>':'<button id="deleteKnowledge" class="danger">删除 Knowledge…</button>'}`;$('#favoriteBtn').onclick=()=>{ui.favorites=fav?ui.favorites.filter(x=>x!==k.id):[...ui.favorites,k.id];renderExplorer();renderInfo(k,position);saveUI()};$('#infoTitle').oninput=e=>saveKnowledgeField(k,'title',e.target.value);$('#infoSummary').oninput=e=>saveKnowledgeField(k,'summary',e.target.value);$('#openKnowledge').onclick=()=>navigate(k.id,position);$('#expandKnowledge')?.addEventListener('click',()=>expandPosition(position));$('#removeReference')?.addEventListener('click',()=>clearPosition(position));$('#deleteKnowledge')?.addEventListener('click',()=>confirmDelete(k))}
function renderRelations(k,position){if(!k){$('#inspectorContent').innerHTML='<p class="muted">空 Position 没有关系。</p>';return}const incoming=semantic.relations.filter(r=>r.targetId===k.id),outgoing=semantic.relations.filter(r=>r.sourceId===k.id),refs=semantic.lmns.flatMap(l=>Object.values(l.positions).filter(p=>p.knowledgeId===k.id).map(p=>({owner:knowledge(l.knowledgeId),position:p.position})));$('#inspectorContent').innerHTML=`<span class="eyebrow">Relations</span><h2>${esc(k.title)}</h2><button id="relationConnect">＋ 创建 Relation</button><h3>Outgoing · ${outgoing.length}</h3>${outgoing.map(r=>relationRow(r,knowledge(r.targetId),'→')).join('')||'<p class="muted">无</p>'}<h3>Incoming · ${incoming.length}</h3>${incoming.map(r=>relationRow(r,knowledge(r.sourceId),'←')).join('')||'<p class="muted">无</p>'}<h3>LMN References · ${refs.length}</h3>${refs.map(x=>`<div class="relation-row" data-id="${x.owner?.id}"><span>${esc(x.owner?.title)} · ${x.position}</span><small>打开</small></div>`).join('')||'<p class="muted">无</p>'}`;$('#relationConnect').onclick=()=>startConnect(k.id);$$('.relation-row[data-id]').forEach(r=>r.onclick=()=>navigate(r.dataset.id,null));$$('[data-relation]').forEach(r=>r.oncontextmenu=e=>{e.preventDefault();showRelationMenu(r.dataset.relation,e)})}
function relationRow(r,other,arrow){return `<div class="relation-row" data-relation="${r.id}" data-id="${other?.id}"><span>${arrow} ${esc(other?.title||'Missing')}</span><small>${esc(r.label||r.type)}</small></div>`}
function renderPresentation(){const options=['lmn','free','tree','mind','hasse','hierarchy','timeline'];$('#inspectorContent').innerHTML=`<span class="eyebrow">Representation</span><h2>呈现方式</h2><div class="field"><label>Layout</label><select id="presentationSelect">${options.map(x=>`<option value="${x}" ${ui.presentation===x?'selected':''}>${labelPresentation(x)}</option>`).join('')}</select></div><div class="field"><label>缩放行为</label><select id="zoomBehavior"><option>Semantic Zoom</option><option>Fixed Density</option></select></div>${toggle('axis','显示列 Axis',ui.showAxis)}${toggle('relations','Relation Overlay',ui.showRelations)}${toggle('summary','显示摘要',ui.showSummary)}${toggle('labels','显示标签',ui.showLabels)}<h3>Layout 参数</h3><div class="field"><label>节点间距</label><input id="nodeSpacing" type="range" min="24" max="120" value="72"></div><div class="field"><label>连接样式</label><select><option>柔和曲线</option><option>直线</option><option>正交线</option></select></div><p class="muted">这些设置只改变 Presentation，不修改 Knowledge、Relation 或 LMN 引用。</p>`;$('#presentationSelect').onchange=e=>setPresentation(e.target.value);$$('[data-toggle]').forEach(b=>b.onclick=()=>{const key=b.dataset.toggle==='axis'?'showAxis':b.dataset.toggle==='relations'?'showRelations':b.dataset.toggle==='summary'?'showSummary':'showLabels';ui[key]=!ui[key];renderWorkspace();renderInspector();saveUI()});$('#nodeSpacing').oninput=e=>{$('#lmnColumns').style.gap=e.target.value+'px';scheduleEdges()}}
function toggle(key,label,on){return `<div class="toggle-row"><span>${label}</span><button class="switch ${on?'on':''}" data-toggle="${key}" aria-pressed="${on}"></button></div>`}
function renderNotes(k){if(!k){$('#inspectorContent').innerHTML='<p class="muted">先为 Position 指定 Knowledge。</p>';return}const mode=k.noteMode||'edit';$('#inspectorContent').innerHTML=`<span class="eyebrow">Notes</span><h2>${esc(k.title)}</h2><div class="segmented"><button data-mode="edit" class="${mode==='edit'?'active':''}">Edit</button><button data-mode="preview" class="${mode==='preview'?'active':''}">Preview</button><button data-mode="split" class="${mode==='split'?'active':''}">Split</button></div><div id="noteArea">${mode==='preview'?`<article class="note-preview">${markdown(k.content)}</article>`:`<div class="field"><textarea id="noteEditor" class="note-editor" placeholder="Markdown 与 $LaTeX$…">${esc(k.content)}</textarea></div>${mode==='split'?`<article class="note-preview">${markdown(k.content)}</article>`:''}`}</div>`;$$('[data-mode]').forEach(b=>b.onclick=()=>{k.noteMode=b.dataset.mode;renderNotes(k)});$('#noteEditor')?.addEventListener('input',e=>{k.content=e.target.value;k.updatedAt=new Date().toISOString();scheduleKnowledgeSave(k);if(mode==='split')$('.note-preview').innerHTML=markdown(k.content)})}
function renderMultiInspector(){$('#inspectorContent').innerHTML=`<span class="eyebrow">Multi-select</span><h2>${ui.selectedIds.size} Knowledge selected</h2><button data-align="left">左对齐</button> <button data-align="center">居中</button><div class="field"><button id="multiPresentation">选择呈现方式</button> <button id="multiExport">导出所选</button></div><p class="muted">移动与对齐只修改当前 Presentation 坐标。</p>`;$$('[data-align]').forEach(b=>b.onclick=()=>status(`已应用${b.textContent}（Presentation only）`));$('#multiPresentation').onclick=()=>{ui.inspectorTab='presentation';renderInspector()};$('#multiExport').onclick=()=>exportData([...ui.selectedIds])}

function saveKnowledgeField(k,key,value){k[key]=value;k.updatedAt=new Date().toISOString();scheduleKnowledgeSave(k)}
function scheduleKnowledgeSave(k){clearTimeout(saveTimer);saving();saveTimer=setTimeout(async()=>{await db.put('knowledge',k);saved();renderExplorer();if(ui.presentation==='lmn')renderLMN()},350)}
function saving(){ui.saving=true;$('#saveStatus').classList.add('saving');$('#saveStatus').innerHTML='<i></i> 正在保存…'}
function saved(){ui.saving=false;$('#saveStatus').classList.remove('saving');$('#saveStatus').innerHTML=`<i></i> 已保存 ${new Date().toLocaleTimeString()}`}
function renderStatus(){$('#pathStatus').textContent=`Recursive Depth: ${Math.max(0,ui.path.length-1)} · Zoom ${Math.round(ui.zoom*100)}%`;$('#selectionStatus').textContent=ui.selectedIds.size>1?`${ui.selectedIds.size} Knowledge selected`:ui.selectedPosition?`Position ${ui.selectedPosition}`:'未选择 Position';$('#uuidStatus').textContent=current()?`UUID: ${currentId.slice(0,8)}…`:''}

function startConnect(source=currentId){ui.connect={source:source||null};$('#connectPanel').classList.remove('hidden');$('#connectHint').textContent=ui.connect.source?`起点：${knowledge(ui.connect.source)?.title}，请选择目标`:'选择起点 Knowledge';$('#connectBtn').classList.add('active')}
function cancelConnect(){ui.connect=null;hide('#connectPanel');$('#connectBtn').classList.remove('active')}
async function completeConnect(target){if(!target)return status('空 Position 不能作为连接端点。');if(!ui.connect.source){ui.connect.source=target;$('#connectHint').textContent=`起点：${knowledge(target)?.title}，请选择目标`;return}if(target===ui.connect.source)return status('请选择不同的目标 Knowledge。');const label=prompt('关系名称（可留空）','')??'';checkpoint();const r=createRelation(ui.connect.source,target,'related',label);semantic.relations.push(r);await db.put('relations',r);cancelConnect();saved();render()}

function startCardDrag(card,e){drag={card,startX:e.clientX,startY:e.clientY,base:ui.offsets[`${currentId}:${card.dataset.position}`]||{x:0,y:0},moved:false};card.classList.add('dragging');card.setPointerCapture?.(e.pointerId)}
function onCanvasDown(e){if(e.target.closest('.position-card')||e.target.closest('button')||e.button!==0)return;const vp=$('#canvasViewport'),r=vp.getBoundingClientRect();if(e.shiftKey){box={x:e.clientX-r.left,y:e.clientY-r.top};$('#selectionBox').style.cssText=`left:${box.x}px;top:${box.y}px;width:0;height:0`;$('#selectionBox').classList.remove('hidden')}else{drag={pan:true,startX:e.clientX,startY:e.clientY,base:{...ui.pan}};vp.classList.add('panning')}}
function onPointerMove(e){if(box){const r=$('#canvasViewport').getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,left=Math.min(x,box.x),top=Math.min(y,box.y);Object.assign($('#selectionBox').style,{left:left+'px',top:top+'px',width:Math.abs(x-box.x)+'px',height:Math.abs(y-box.y)+'px'});return}if(!drag)return;if(drag.pan){ui.pan={x:drag.base.x+e.clientX-drag.startX,y:drag.base.y+e.clientY-drag.startY};applyTransform();return}const dx=(e.clientX-drag.startX)/ui.zoom,dy=(e.clientY-drag.startY)/ui.zoom;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;drag.card.style.translate=`${drag.base.x+dx}px ${drag.base.y+dy}px`;scheduleEdges()}
function onPointerUp(){if(box){const s=$('#selectionBox').getBoundingClientRect();ui.selectedIds.clear();$$('.position-card[data-id]').forEach(c=>{const r=c.getBoundingClientRect();if(r.right>s.left&&r.left<s.right&&r.bottom>s.top&&r.top<s.bottom)ui.selectedIds.add(c.dataset.id)});box=null;hide('#selectionBox');renderInspector();renderStatus();return}if(!drag)return;if(drag.pan){$('#canvasViewport').classList.remove('panning');saveUI()}else{drag.card.classList.remove('dragging');if(drag.moved){checkpoint();const key=`${currentId}:${drag.card.dataset.position}`,parts=drag.card.style.translate.split(' ');ui.offsets[key]={x:parseFloat(parts[0]),y:parseFloat(parts[1])};saveUI();saved()}}drag=null}
function onWheel(e){if(!e.ctrlKey&&!e.metaKey){ui.pan.x-=e.deltaX;ui.pan.y-=e.deltaY;applyTransform();return}e.preventDefault();setZoom(ui.zoom+(e.deltaY<0?.1:-.1))}
function setZoom(value){ui.zoom=Math.max(.2,Math.min(2.5,Math.round(value*20)/20));applyTransform();setDensity();renderStatus();saveUI();scheduleEdges()}
function setDensity(){const z=ui.zoom,stage=$('#canvasStage');stage.dataset.density=z<.25?'overview':z<.5?'compact':z<1?'normal':z<=2?'detail':'deep'}
function applyTransform(){$('#canvasStage').style.transform=`translate(${ui.pan.x}px,${ui.pan.y}px) scale(${ui.zoom})`;$('#zoomReset').textContent=Math.round(ui.zoom*100)+'%'}
function fitView(){ui.zoom=1;ui.pan={x:0,y:0};applyTransform();setDensity();renderStatus();saveUI()}
function toggleFocus(){ui.focus=!ui.focus;renderShell();$('#focusBtn').textContent=ui.focus?'退出专注':'专注';setTimeout(scheduleEdges,220);saveUI()}

function showViewMenu(anchor){const r=anchor.getBoundingClientRect(),p=$('#contextMenu');p.style.left=Math.min(innerWidth-220,r.left)+'px';p.style.top=r.bottom+6+'px';p.innerHTML=`<button data-view="lmn">默认 LMN</button><button data-view="free">自由图</button><button data-view="tree">树状图</button><button data-view="hasse">偏序 / Hasse</button><hr><button data-action="relations">${ui.showRelations?'✓ ':''}Show Relations</button><button data-action="fit">适应视图</button><button data-action="focus">专注模式</button><button data-action="import">导入…</button>`;p.classList.remove('hidden');p.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setPresentation(b.dataset.view);hide('#contextMenu')});p.querySelector('[data-action=relations]').onclick=()=>{ui.showRelations=!ui.showRelations;renderWorkspace();hide('#contextMenu')};p.querySelector('[data-action=fit]').onclick=fitView;p.querySelector('[data-action=focus]').onclick=toggleFocus;p.querySelector('[data-action=import]').onclick=()=>$('#fileInput').click()}
function showPositionMenu(card,e){ui.selectedPosition=card.dataset.position;renderInspector();showMenu(e.clientX,e.clientY,[['打开 Knowledge',()=>card.dataset.id&&navigate(card.dataset.id,card.dataset.position)],['原位展开',()=>expandPosition(card.dataset.position)],['指定已有 Knowledge',()=>showPicker(card)],['新建 Knowledge',()=>inlineCreate(card.dataset.position)],['复制路径',()=>navigator.clipboard?.writeText(pathText(card.dataset.position))],['清除 Reference',()=>clearPosition(card.dataset.position),'danger']])}
function showKnowledgeMenu(el,e){const id=el.dataset.id;showMenu(e.clientX,e.clientY,[['打开',()=>navigate(id,null)],['展开 LMN',()=>navigate(id,null)],['连接',()=>startConnect(id)],['添加笔记',()=>{navigate(id,null);ui.inspectorTab='notes';renderInspector()}],[ui.favorites.includes(id)?'取消收藏':'收藏',()=>{ui.favorites=ui.favorites.includes(id)?ui.favorites.filter(x=>x!==id):[...ui.favorites,id];renderExplorer();saveUI()}],['删除…',()=>confirmDelete(knowledge(id)),'danger']])}
function showRelationMenu(id,e){const r=semantic.relations.find(x=>x.id===id);showMenu(e.clientX,e.clientY,[['查看 Relation',()=>{ui.selectedRelation=id;renderInspector()}],['编辑名称',async()=>{const label=prompt('Relation 名称',r.label||'');if(label!==null){checkpoint();r.label=label;await db.put('relations',r);render()}}],['反转方向',async()=>{checkpoint();[r.sourceId,r.targetId]=[r.targetId,r.sourceId];await db.put('relations',r);render()}],['删除 Relation',()=>deleteRelation(r),'danger']])}
function showMenu(x,y,items){const p=$('#contextMenu');p.style.left=Math.min(innerWidth-210,x)+'px';p.style.top=Math.min(innerHeight-280,y)+'px';p.innerHTML=items.map((it,i)=>`<button data-i="${i}" class="${it[2]||''}">${it[0]}</button>`).join('');p.classList.remove('hidden');items.forEach((it,i)=>p.querySelector(`[data-i="${i}"]`).onclick=()=>{hide('#contextMenu');it[1]()})}

function openPalette(){$('#commandPalette').showModal();renderCommands();setTimeout(()=>$('#commandInput').focus(),20)}
function renderCommands(){const q=$('#commandInput').value.trim().toLowerCase(),commands=[{label:'新建 Knowledge',meta:'N',run:quickCreate},{label:'进入连接模式',meta:'C',run:startConnect},{label:'切换专注模式',meta:'Focus',run:toggleFocus},{label:'导入数据',meta:'Import',run:()=>$('#fileInput').click()},{label:'导出当前 Knowledge',meta:'Export',run:exportData},...semantic.knowledge.map(k=>({label:k.title,meta:'Knowledge',run:()=>navigate(k.id,null)})),...semantic.relations.map(r=>({label:r.label||`${knowledge(r.sourceId)?.title} → ${knowledge(r.targetId)?.title}`,meta:'Relation',run:()=>{ui.selectedRelation=r.id;ui.inspectorTab='relations';renderInspector()}}))].filter(x=>!q||(x.label+' '+x.meta).toLowerCase().includes(q)).slice(0,14);$('#commandResults').innerHTML=commands.map((x,i)=>`<button class="command-result" data-i="${i}"><span>${esc(x.label)}</span><small>${x.meta}</small></button>`).join('');commands.forEach((x,i)=>$('#commandResults').querySelector(`[data-i="${i}"]`).onclick=()=>{$('#commandPalette').close();x.run()})}
async function quickCreate(){const title=prompt('Knowledge 名称');if(!title?.trim())return;checkpoint();const {knowledge:k,lmn:l}=createNamedKnowledge(title.trim());semantic.knowledge.push(k);semantic.lmns.push(l);await Promise.all([db.put('knowledge',k),db.put('lmns',l)]);navigate(k.id,null);saved()}
async function confirmDelete(k){const i=deletionImpact(semantic,k.id);$('#riskTitle').textContent=`删除「${k.title}」？`;$('#riskBody').innerHTML=`<p>Referenced by <b>${i.lmnReferences.length}</b> places<br>Used by <b>${i.structureReferences.length}</b> Structures<br>Connected by <b>${i.relations.length}</b> Relations</p><p class="danger">此操作删除 Knowledge；移除 Position 引用请使用“清除 Reference”。</p>`;const d=$('#riskDialog');d.showModal();d.onclose=async()=>{if(d.returnValue!=='confirm')return;checkpoint();semantic.knowledge=semantic.knowledge.filter(x=>x.id!==k.id);await db.remove('knowledge',k.id);for(const r of i.relations){semantic.relations=semantic.relations.filter(x=>x.id!==r.id);await db.remove('relations',r.id)}for(const l of semantic.lmns){let changed=false;for(const p of Object.values(l.positions))if(p.knowledgeId===k.id){p.knowledgeId=null;changed=true}if(changed)await db.put('lmns',l)}currentId=semantic.knowledge[0]?.id||null;ui.path=currentId?[{knowledgeId:currentId,position:null}]:[];render();saved()}}
async function deleteRelation(r){checkpoint();semantic.relations=semantic.relations.filter(x=>x.id!==r.id);await db.remove('relations',r.id);ui.selectedRelation=null;render();saved()}

function snapshot(){return structuredClone(semantic)}function checkpoint(){ui.undo.push(snapshot());if(ui.undo.length>30)ui.undo.shift();ui.redo=[];updateUndoButtons()}async function restore(s){Object.assign(semantic,structuredClone(s));await db.replaceAll(semantic);render();saved()}async function undo(){const s=ui.undo.pop();if(!s)return;ui.redo.push(snapshot());await restore(s);updateUndoButtons()}async function redo(){const s=ui.redo.pop();if(!s)return;ui.undo.push(snapshot());await restore(s);updateUndoButtons()}function updateUndoButtons(){$('#undoBtn').disabled=!ui.undo.length;$('#redoBtn').disabled=!ui.redo.length}
function exportData(ids=null){const data=ids?{...semantic,knowledge:semantic.knowledge.filter(k=>ids.includes(k.id)),relations:semantic.relations.filter(r=>ids.includes(r.sourceId)&&ids.includes(r.targetId))}:semantic,b=new Blob([JSON.stringify(exportBundle(data),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`lmn-v2-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function readImport(e){const f=e.target.files[0];if(!f)return;try{if(f.name.endsWith('.md')){const k=createKnowledge(f.name.replace(/\.md$/i,''),await f.text());pendingImport={schema_version:1,...semantic,knowledge:[k],relations:[],representations:[],lmns:[createLMN(k.id)],structures:[]}}else pendingImport=JSON.parse(await f.text());const v=validateImport(pendingImport);if(!v.valid)throw new Error(v.errors.join('\n'));$('#importPreview').innerHTML=`<p>${pendingImport.knowledge.length} Knowledge · ${pendingImport.relations.length} Relations · ${pendingImport.lmns.length} LMN Graphs</p><p>相同 UUID 将更新；现有其他实体保留。</p>`;$('#importDialog').showModal()}catch(err){status(`导入失败：${err.message}`)}finally{e.target.value=''}}
async function applyImport(){if(!pendingImport)return;checkpoint();const merged=mergeImport(semantic,pendingImport);await db.replaceAll(merged);Object.assign(semantic,merged);pendingImport=null;render();saved()}
function saveUI(){const data={zoom:ui.zoom,pan:ui.pan,presentation:ui.presentation,showAxis:ui.showAxis,showRelations:ui.showRelations,showSummary:ui.showSummary,showLabels:ui.showLabels,explorerHidden:ui.explorerHidden,inspectorHidden:ui.inspectorHidden,path:ui.path,recent:ui.recent,favorites:ui.favorites,offsets:ui.offsets};db.put('settings',{id:'workspace-v2',data}).catch(()=>{})}
function keys(e){const tag=e.target.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag)&&!(e.ctrlKey&&e.key.toLowerCase()==='k'))return;if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}else if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='z'){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.altKey&&e.key==='ArrowLeft')goBack();else if(e.altKey&&e.key==='ArrowRight')goForward();else if(e.key.toLowerCase()==='n')quickCreate();else if(e.key.toLowerCase()==='c')startConnect();else if(e.key==='Enter'&&ui.selectedPosition){const id=lmnFor(currentId)?.positions[ui.selectedPosition]?.knowledgeId;if(id)navigate(id,ui.selectedPosition)}else if(e.code==='Space'&&ui.selectedPosition){e.preventDefault();expandPosition(ui.selectedPosition)}else if(e.key==='Delete'&&ui.selectedPosition)clearPosition(ui.selectedPosition);else if(e.key==='Tab'){e.preventDefault();const tabs=['info','relations','presentation','notes'],i=tabs.indexOf(ui.inspectorTab);ui.inspectorTab=tabs[(i+1)%tabs.length];renderInspector()}else if(e.key==='Escape'){if(ui.focus)toggleFocus();else if(ui.connect)cancelConnect();else if(ui.back.length)goBack()} }
function summary(k){return k.summary||k.content.replace(/[#*_`$>\[\]]/g,'').trim().slice(0,90)||'暂无摘要'}function markdown(s=''){return esc(s).replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\$(.*?)\$/g,'<span class="math">$1</span>').replace(/^- (.*)$/gm,'<div>• $1</div>').replace(/\n/g,'<br>')}function relativeTime(t){const d=Date.now()-new Date(t).getTime();return d<60000?'刚刚':d<3600000?`${Math.floor(d/60000)} 分钟前`:d<86400000?`${Math.floor(d/3600000)} 小时前`:new Date(t).toLocaleDateString()}function pathText(position){return [...ui.path.map(p=>knowledge(p.knowledgeId)?.title),position].filter(Boolean).join(' > ')}function hide(s){$(s)?.classList.add('hidden')}function status(text){$('#selectionStatus').textContent=text;setTimeout(renderStatus,3500)}
boot().then(updateUndoButtons).catch(e=>{console.error(e);alert(`LMN V2 启动失败：${e.message}`)});
