import {createKnowledge,createRelation,createLMN,validateLMN,neighborhood,transitiveReduction,exportBundle,validateImport,mergeImport,deletionImpact,LMN_POSITIONS} from '../../packages/domain/core.js';
import * as db from './db.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={knowledge:[],relations:[],representations:[],lmns:[],structures:[]};let selectedId=null,view='text',history=[],timer;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const current=()=>state.knowledge.find(k=>k.id===selectedId),byId=id=>state.knowledge.find(k=>k.id===id);
async function boot(){for(const k of Object.keys(state))state[k]=await db.list(k);bind();render();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function bind(){ $('#newKnowledge').onclick=$('#emptyCreate').onclick=promptNew;$('#search').oninput=renderList;$$('.tabs button').forEach(b=>b.onclick=()=>{view=b.dataset.view;renderView()});$('#title').oninput=saveSoon;$('#content').oninput=()=>{markdown();saveSoon()};$('#depth').onchange=renderGraph;$('#connectBtn').onclick=connect;$('#createStructure').onclick=createStructure;$('#exportBtn').onclick=exportData;$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=importData;document.onkeydown=e=>{if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();promptNew()}if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}if(e.key==='Escape'&&history.length)select(history.pop(),false)}}
function render(){renderList();renderView();$('#footerCount').textContent=`${state.knowledge.length} Knowledge · ${state.relations.length} Relations`}
function renderList(){const q=$('#search').value.trim().toLowerCase();$('#knowledgeList').innerHTML=state.knowledge.filter(k=>(k.title+k.content).toLowerCase().includes(q)).map(k=>`<div class="knowledge-item ${k.id===selectedId?'active':''}" data-id="${k.id}"><span>${esc(k.title)}</span><small>${new Date(k.updatedAt).toLocaleDateString()}</small></div>`).join('');$$('.knowledge-item').forEach(x=>x.onclick=()=>select(x.dataset.id))}
function select(id,remember=true){if(remember&&selectedId&&selectedId!==id)history.push(selectedId);selectedId=id;render()}
function renderView(){const k=current();$('#empty').classList.toggle('hidden',!!k);$$('.view').forEach(x=>x.classList.add('hidden'));$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(!k){$('#breadcrumbs').textContent='Workspace';inspector();return}$(`#${view}View`).classList.remove('hidden');$('#breadcrumbs').textContent=`${k.title} / ${view.toUpperCase()}`;if(view==='text')text();if(view==='graph')renderGraph();if(view==='lmn')renderLMN();if(view==='structure')renderStructure();inspector()}
function ask(title,body,get=()=>$('#askTitle')?.value?.trim()){return new Promise(resolve=>{$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;const d=$('#dialog');d.showModal();setTimeout(()=>$('#askTitle')?.focus(),10);d.onclose=()=>resolve(d.returnValue==='default'?get():null)})}
async function promptNew(){const title=await ask('新建 Knowledge','<input id="askTitle" autofocus placeholder="一个词或简短标题" style="width:100%;padding:9px">');if(!title)return;const k=createKnowledge(title);state.knowledge.push(k);await db.put('knowledge',k);select(k.id)}
function text(){const k=current();$('#title').value=k.title;$('#content').value=k.content;markdown()}
function saveSoon(){clearTimeout(timer);$('#status').textContent='正在保存…';timer=setTimeout(async()=>{const k=current();if(!k)return;k.title=$('#title').value.trim()||k.title;k.content=$('#content').value;k.updatedAt=new Date().toISOString();await db.put('knowledge',k);$('#status').textContent='已保存到本地';renderList()},300)}
function markdown(){let s=esc($('#content').value);s=s.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/\$\$(.*?)\$\$/gs,'<div class="math">$1</div>').replace(/\$(.*?)\$/g,'<span class="math">$1</span>').replace(/^- (.*)$/gm,'<div>• $1</div>').replace(/\n/g,'<br>');$('#preview').innerHTML=s||'<span class="muted">预览</span>'}
async function connect(){const options=state.knowledge.filter(k=>k.id!==selectedId);if(!options.length)return alert('请先创建另一个 Knowledge。');const body=`<input id="relationLabel" placeholder="关系标签（可选）" style="width:100%;padding:8px"><div class="dialog-list">${options.map((k,i)=>`<label><input type="radio" name="target" value="${k.id}" ${i?'':'checked'}> ${esc(k.title)}</label>`).join('')}</div>`;const x=await ask('连接已有 Knowledge',body,()=>({targetId:document.querySelector('[name=target]:checked')?.value,label:$('#relationLabel').value.trim()}));if(!x?.targetId)return;if(state.relations.some(r=>r.sourceId===selectedId&&r.targetId===x.targetId&&r.label===x.label))return alert('该关系已经存在。');const r=createRelation(selectedId,x.targetId,'related',x.label);state.relations.push(r);await db.put('relations',r);render()}
function renderGraph(){const root=current();if(!root)return;const p=neighborhood(state.knowledge,state.relations,root.id,Number($('#depth').value));const cx=450,cy=280,rad=Math.min(220,75+p.nodes.length*15),pos=new Map(p.nodes.map((n,i)=>[n.id,n.id===root.id?{x:cx,y:cy}:{x:cx+Math.cos((i-1)*Math.PI*2/Math.max(1,p.nodes.length-1))*rad,y:cy+Math.sin((i-1)*Math.PI*2/Math.max(1,p.nodes.length-1))*rad}]));$('#graph').innerHTML=p.edges.map(e=>{const a=pos.get(e.sourceId),b=pos.get(e.targetId);return`<g><line class="edge" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><text class="edge-label" x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2}">${esc(e.label||e.type)}</text></g>`}).join('')+p.nodes.map(n=>{const x=pos.get(n.id);return`<g class="node ${n.id===root.id?'root':''}" data-id="${n.id}" transform="translate(${x.x},${x.y})"><circle r="38"/><text y="4">${esc(n.title.slice(0,12))}</text></g>`}).join('');[...$('#graph').querySelectorAll('.node')].forEach(n=>n.onclick=()=>select(n.dataset.id))}
async function getLMN(){let l=state.lmns.find(x=>x.knowledgeId===selectedId);if(!l){l=createLMN(selectedId);state.lmns.push(l);await db.put('lmns',l)}return l}
async function renderLMN(){const l=await getLMN(),check=validateLMN(l);$('#lmnGrid').innerHTML=['L','M','N'].map(g=>`<div class="lmn-group ${g}">${LMN_POSITIONS.filter(p=>p.group===g).map(p=>{const r=byId(l.positions[p.id].knowledgeId);return`<div class="lmn-cell ${r?'filled':''}" data-position="${p.id}"><b>${p.id}</b><span>${p.name}</span><small>${r?esc(r.title):'未指定 · 点击连接'}</small></div>`}).join('')}</div>`).join('')+(check.valid?'':`<p class="danger">${check.errors.join('; ')}</p>`);$$('.lmn-cell').forEach(c=>c.onclick=()=>setPosition(l,c.dataset.position))}
async function setPosition(l,p){const ref=l.positions[p].knowledgeId,body=`<div class="dialog-list"><label><input type="radio" name="target" value="" ${ref?'':'checked'}> 清空</label>${state.knowledge.map(k=>`<label><input type="radio" name="target" value="${k.id}" ${ref===k.id?'checked':''}> ${esc(k.title)}</label>`).join('')}</div><input id="newPositionKnowledge" placeholder="或创建新 Knowledge" style="width:100%;padding:8px;margin-top:10px">`;const x=await ask(`${p} · 指定 Knowledge`,body,()=>({id:document.querySelector('[name=target]:checked')?.value||null,title:$('#newPositionKnowledge').value.trim()}));if(!x)return;if(x.title){const k=createKnowledge(x.title);state.knowledge.push(k);await db.put('knowledge',k);x.id=k.id}l.positions[p].knowledgeId=x.id;l.updatedAt=new Date().toISOString();await db.put('lmns',l);render()}
async function createStructure(){const p=neighborhood(state.knowledge,state.relations,selectedId,2),type=$('#structureType').value,s={id:crypto.randomUUID(),name:`${current().title} · ${type}`,type,knowledgeId:selectedId,nodes:p.nodes.map(n=>({id:n.id,knowledgeId:n.id})),edges:p.edges.map(e=>({...e})),createdAt:new Date().toISOString()};state.structures.push(s);await db.put('structures',s);renderStructure(s)}
function renderStructure(g){const s=g||[...state.structures].reverse().find(x=>x.knowledgeId===selectedId);if(!s){$('#structureResult').innerHTML='<p class="muted">从当前局部关系生成独立、可复用的 Structure。</p>';return}$('#structureType').value=s.type;if(s.type==='poset'){const r=transitiveReduction(s.nodes.map(n=>n.id),s.edges),remaining=new Set(s.nodes.map(n=>n.id)),levels=[];while(remaining.size){const level=[...remaining].filter(id=>!r.edges.some(e=>e.targetId===id&&remaining.has(e.sourceId)));if(!level.length)break;levels.push(level);level.forEach(x=>remaining.delete(x))}$('#structureResult').innerHTML=`<h2>Hasse Diagram</h2>${r.warning?`<p class="danger">${r.warning}</p>`:''}${levels.reverse().map(l=>`<div class="hasse-level">${l.map(id=>`<div class="hasse-node">${esc(byId(id)?.title||id)}</div>`).join('')}</div>`).join('')}<p class="muted">已应用传递约简；原 Relation 未修改。</p>`}else $('#structureResult').innerHTML=`<h2>${esc(s.name)}</h2><p>${s.nodes.length} objects · ${s.edges.length} relations</p><ul>${s.nodes.map(n=>`<li>${esc(byId(n.knowledgeId)?.title||n.id)}</li>`).join('')}</ul>`}
function inspector(){const k=current();if(!k){$('#inspector').innerHTML='<p class="muted">选择一个 Knowledge。</p>';return}const i=deletionImpact(state,k.id);$('#inspector').innerHTML=`<dl><dt>UUID</dt><dd>${k.id}</dd><dt>关系</dt><dd>${i.relations.length}</dd><dt>LMN 引用</dt><dd>${i.lmnReferences.length}</dd><dt>结构引用</dt><dd>${i.structureReferences.length}</dd></dl><button id="deleteKnowledge" class="danger">依赖审查后删除</button>`;$('#deleteKnowledge').onclick=async()=>{if(!confirm(`影响：${i.relations.length} 关系，${i.lmnReferences.length} LMN 引用。确认删除并清理直接引用？`))return;state.knowledge=state.knowledge.filter(x=>x.id!==k.id);await db.remove('knowledge',k.id);for(const r of i.relations){state.relations=state.relations.filter(x=>x.id!==r.id);await db.remove('relations',r.id)}for(const l of state.lmns){let c=false;for(const p of Object.values(l.positions))if(p.knowledgeId===k.id){p.knowledgeId=null;c=true}if(c)await db.put('lmns',l)}selectedId=null;render()}}
function exportData(){const b=new Blob([JSON.stringify(exportBundle(state),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`lmn-export-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importData(e){const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text()),v=validateImport(x);if(!v.valid)throw new Error(v.errors.join('\n'));if(!confirm(`导入预览：${x.knowledge.length} Knowledge，${x.relations.length} Relations。继续？`))return;const m=mergeImport(state,x);await db.replaceAll(m);Object.assign(state,m);render()}catch(x){alert(`导入失败：${x.message}`)}finally{e.target.value=''}}
boot().catch(e=>alert(`启动失败：${e.message}`));
