const CACHE='lmn-v4.3.0-stable-20260901-4';
const KATEX_FONTS=['AMS-Regular','Caligraphic-Bold','Caligraphic-Regular','Fraktur-Bold','Fraktur-Regular','Main-Bold','Main-BoldItalic','Main-Italic','Main-Regular','Math-BoldItalic','Math-Italic','SansSerif-Bold','SansSerif-Italic','SansSerif-Regular','Script-Regular','Size1-Regular','Size2-Regular','Size3-Regular','Size4-Regular','Typewriter-Regular'].map(name=>`./vendor/katex/fonts/KaTeX_${name}.woff2`);
const ASSETS=[
  './','./index.html','./styles.css','./app.js','./db.js','./manifest.webmanifest','./vendor/katex/katex.min.css','./vendor/katex/katex.mjs',
  '../../packages/domain/core.js','../../packages/domain/object-management.js','../../packages/domain/semantic-container.js','../../packages/domain/identity.js',
  '../../packages/app-metadata.js','../../packages/ui/workspace-controller.js','../../packages/ui/structure-renderer.js','../../packages/ui/math-markup.js','../../packages/ui/library-model.js','../../packages/ui/object-interaction-contract.js','../../packages/ui/content-preview.js','../../packages/ui/transient-overlay-manager.js','../../packages/ui/document-editor.js','../../packages/ui/localization.js','../../packages/ui/command-registry.js',
  '../../packages/geometry/scene-geometry.js','../../packages/geometry/animation-coordinator.js','../../packages/navigation/path.js','../../packages/navigation/navigator-model.js',
  '../../packages/structure-engine/templates.js','../../packages/structure-engine/model.js','../../packages/structure-engine/structure-view.js','../../packages/structure-engine/knowledge-workflow.js','../../packages/structure-engine/cyclic-group.js','../../packages/structure-engine/variable-schemes.js','../../packages/structure-engine/variable-result-normalizer.js','../../packages/structure-engine/relation-style-resolver.js','../../packages/structure-engine/interaction-adapters.js','../../packages/structure-engine/presentation-adapters.js','../../packages/structure-engine/poset.js','../../packages/structure-engine/plotting.js','../../packages/structure-engine/evaluator.js','../../packages/structure-engine/formula.js','../../packages/structure-engine/relation-library.js','../../packages/structure-engine/boolean-algebra.js','../../packages/structure-engine/migration.js','../../packages/structure-engine/bundle.js','../../packages/structure-engine/board.js','../../packages/search-engine/search.js','../../packages/search-engine/query-engine.js',
  '../../packages/lkl/index.js','../../packages/lkl/lexer.js','../../packages/lkl/parser.js','../../packages/lkl/semantic.js','../../packages/lkl/serializer.js','../../packages/lkl2/index.js','../../packages/lkl2/lexer.js','../../packages/lkl2/parser.js','../../packages/lkl2/ast.js','../../packages/lkl2/validator.js','../../packages/lkl2/serializer.js','../../packages/lkl2/importer.js','../../packages/lkl2/exporter.js','../../packages/lkl2/structure-source.js','../../packages/lkl2/variable-scheme-codec.js','../../packages/lkl2/schema.js',...KATEX_FONTS
];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith(fetch(event.request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response}).catch(()=>caches.match(event.request)))});
