import {createRequire} from 'node:module';
import fs from 'node:fs';

const require=createRequire(import.meta.url),{chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('outputs',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),context=await browser.newContext({viewport:{width:1536,height:960},serviceWorkers:'block'}),page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.stack||error.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))errors.push(message.text())});
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});await page.evaluate(()=>new Promise(resolve=>{localStorage.clear();const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=resolve;request.onblocked=resolve}));await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.lmnWorkspace);

await page.evaluate(async()=>{const[{createKnowledge},{createStructureInstance}]=await Promise.all([import('/packages/domain/core.js'),import('/packages/structure-engine/model.js')]),app=lmnWorkspace,alpha=createKnowledge('Alpha Knowledge'),beta=createKnowledge('Beta Knowledge');app.state.knowledge.push(alpha,beta);const create=(id,parameters={})=>{const template=app.state.structureTemplates.find(item=>item.id===id),instance=createStructureInstance(template,alpha.id,parameters);app.state.structureInstances.push(instance);return instance},graph=create('builtin:directed-graph'),coordinate=create('builtin:coordinate-plane',{dimension:'3d',scale:40}),lmn=create('builtin:lmn-432');app.__qa={alpha:alpha.id,beta:beta.id,graph:graph.id,coordinate:coordinate.id,lmn:lmn.id};app.currentKnowledgeId=alpha.id;app.currentInstanceId=graph.id;app.document=`structure:${graph.id}`;app.dismissedEmpty.add(alpha.id);app.renderAll()});await page.waitForTimeout(180);

const result={version:await page.locator('.brand em').textContent(),errors};
result.navigation={modes:await page.locator('[data-navigator]').count(),knowledgeOptionCount:await page.locator('.nav-knowledge-switcher option').count()};await page.locator('.nav-knowledge-switcher select').selectOption(await page.evaluate(()=>lmnWorkspace.__qa.beta));await page.waitForTimeout(100);result.navigation.switched=await page.evaluate(()=>lmnWorkspace.currentKnowledgeId===lmnWorkspace.__qa.beta);await page.evaluate(()=>lmnWorkspace.openKnowledge(lmnWorkspace.__qa.alpha));

await page.evaluate(()=>lmnWorkspace.openStructureSource(lmnWorkspace.__qa.graph));await page.waitForTimeout(80);await page.evaluate(()=>{const editor=document.querySelector('#structureSourceEditor');editor.value=['needle',...Array.from({length:180},(_,index)=>`line-${index}`),'needle'].join('\n');editor.dispatchEvent(new Event('input'))});await page.locator('#sourceFind').click();await page.locator('#sourceSearchInput').fill('needle');await page.locator('#sourceFindNext').click();await page.waitForTimeout(80);result.source=await page.evaluate(()=>({top:structureSourceEditor.scrollTop,lineTop:sourceLineNumbers.scrollTop,syntaxTop:sourceSyntaxHighlight.scrollTop,selection:structureSourceEditor.value.slice(structureSourceEditor.selectionStart,structureSourceEditor.selectionEnd)}));

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.coordinate);app.openPanel('structure',app.__qa.coordinate,'plot');app.addPlotExpression('circle(cx=1, cy=-1, r=2)')});await page.waitForTimeout(120);result.coordinate={tabs:await page.locator('#panelTabs button').allTextContents(),curves:await page.locator('.coordinate-curve').count(),grid:await page.locator('.coordinate-grid').count()};const point=page.locator('.visual-coordinate-point').first();result.coordinate.point=await point.evaluate(element=>({width:parseFloat(element.style.width),fill:getComputedStyle(element).backgroundColor,stroke:getComputedStyle(element).borderColor}));await page.locator('.coordinate-curve').first().dispatchEvent('click');await page.waitForTimeout(80);result.coordinate.curveEditor=await page.locator('.plot-selected-curve').count();result.coordinate.curveVisibility=await page.evaluate(()=>({panelHidden:floatingPanel.classList.contains('hidden'),panelRect:floatingPanel.getBoundingClientRect().toJSON(),editorRect:document.querySelector('.plot-selected-curve')?.getBoundingClientRect().toJSON()}));await page.locator('.plot-selected-curve textarea[name="source"]').fill('circle(cx=2, cy=0, r=3)');await page.locator('.plot-selected-curve button.primary').click();await page.waitForTimeout(100);result.coordinate.curveSource=await page.evaluate(()=>lmnWorkspace.instance.plotExpressions[0].source);

await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.lmn));await page.waitForTimeout(80);result.lmn=await page.evaluate(()=>{const nodes=new Map(lmnWorkspace.currentScene.nodes.map(node=>[node.id,node]));return lmnWorkspace.currentDefinition.edges.filter(edge=>['e7','e8','e9','e10'].includes(edge.id)).map(edge=>({id:edge.id,direction:edge.direction,up:nodes.get(edge.sourceSlotId).y>nodes.get(edge.targetSlotId).y}))});

await page.evaluate(()=>lmnWorkspace.openLibrary());await page.waitForTimeout(100);const templateMenu=page.locator('.template-card:not(.variable-scheme-card) .scheme-card-menu').first();await templateMenu.click({force:true});result.library={menuVisible:await page.locator('#contextMenu:not(.hidden)').count(),menuParent:await page.locator('#contextMenu').evaluate(element=>element.parentElement?.id)};await page.getByRole('button',{name:'编辑默认参数与样式'}).click({force:true});await page.waitForTimeout(80);result.library.defaultStyle={dialog:await page.locator('#structureConfigDialog').isVisible(),colors:await page.locator('#configParameters input[type="color"]').count(),confirm:await page.locator('#confirmStructureInsert').textContent()};await page.locator('#structureConfigDialog .dialog-close').first().click();

await page.evaluate(()=>{lmnWorkspace.libraryFilter='variables';lmnWorkspace.openLibrary();lmnWorkspace.renderLibrary()});await page.waitForTimeout(100);await page.locator('.variable-scheme-card .scheme-card-menu').first().click({force:true});result.scheme={menuVisible:await page.locator('#contextMenu:not(.hidden)').count(),menuText:await page.locator('#contextMenu').innerText()};await page.evaluate(()=>{const scheme=lmnWorkspace.state.variableSchemes.find(item=>!item.hidden&&!item.deleted);lmnWorkspace.openSchemeConfiguration(scheme.id,true)});await page.waitForTimeout(80);result.scheme.editor={dialog:await page.locator('#structureConfigDialog').isVisible(),open:await page.locator('#structureConfigDialog').evaluate(element=>element.open),confirm:await page.locator('#confirmStructureInsert').textContent(),fields:await page.locator('#configParameters input,#configParameters textarea').count()};await page.evaluate(()=>{if(structureConfigDialog.open)structureConfigDialog.close()});

await page.evaluate(()=>{lmnWorkspace.openStructureConfiguration('builtin:function-mapping');});await page.waitForTimeout(80);result.experimental={dialog:await page.locator('#structureConfigDialog').isVisible(),previewNodes:await page.locator('#configPreview .mini-node').count(),experimentalBadges:await page.locator('.template-maturity',{hasText:'实验性'}).count()};await page.evaluate(()=>{if(structureConfigDialog.open)structureConfigDialog.close()});
await page.evaluate(()=>{lmnWorkspace.openInstance(lmnWorkspace.__qa.coordinate);lmnWorkspace.openPanel('structure',lmnWorkspace.__qa.coordinate,'plot')});await page.waitForTimeout(100);await page.screenshot({path:'outputs/v4.2.3-coordinate.png',fullPage:true});

console.log(JSON.stringify(result,null,2));
const failed=errors.length||result.version!=='V4.2.3 RC'||result.navigation.modes!==3||result.navigation.knowledgeOptionCount!==2||!result.navigation.switched||result.source.top<500||result.source.top!==result.source.lineTop||result.source.top!==result.source.syntaxTop||result.source.selection!=='needle'||!result.coordinate.tabs.includes('呈现与参数')||result.coordinate.tabs.includes('参数')||result.coordinate.curves<1||result.coordinate.grid<200||result.coordinate.point.width>11||result.coordinate.point.fill==='rgb(255, 255, 255)'||result.coordinate.curveEditor!==1||result.coordinate.curveVisibility.panelHidden||result.coordinate.curveVisibility.panelRect.width<200||result.coordinate.curveVisibility.editorRect.height<80||result.coordinate.curveSource!=='circle(cx=2, cy=0, r=3)'||result.lmn.some(edge=>edge.direction!=='directed'||!edge.up)||!result.library.menuVisible||result.library.menuParent!=='structureLibrary'||result.library.defaultStyle.colors<4||result.library.defaultStyle.confirm!=='保存默认设置'||!result.scheme.menuText.includes('编辑默认参数')||result.scheme.editor.confirm!=='保存默认参数'||result.scheme.editor.fields<2||!result.experimental.dialog||result.experimental.previewNodes<3||result.experimental.experimentalBadges!==0;if(failed)process.exitCode=1;
await browser.close();
