import {createRequire} from 'node:module';
import fs from 'node:fs';

const require=createRequire(import.meta.url),{chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('outputs',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
page.on('pageerror',error=>errors.push(error.stack||error.message));
page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))errors.push(message.text())});
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});
await page.evaluate(()=>new Promise(resolve=>{localStorage.clear();const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=resolve;request.onblocked=resolve}));
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.lmnWorkspace);

await page.locator('[data-welcome="knowledge"]').click();await page.locator('[data-create-mode="lmn"]').click();await page.locator('#quickCreateInput').fill('V4.2 交互验收');await page.locator('#quickCreateInput').press('Enter');await page.waitForTimeout(180);
const baseline={version:await page.locator('.brand em').textContent(),nodes:await page.locator('.scene-node').count(),edges:await page.locator('.scene-edge').count(),oldSystems:await page.locator('#containerPeek,#contextToolbar,.container-expand,.container-child-node').count()};

await page.evaluate(async()=>{
  const[{addContainerContent},{bindTarget,createStructureInstance},{createKnowledge}]=await Promise.all([import('/packages/domain/semantic-container.js'),import('/packages/structure-engine/model.js'),import('/packages/domain/core.js')]),app=lmnWorkspace,instance=app.instance,definition=app.currentDefinition;
  const reference=createKnowledge('有限群');app.state.knowledge.push(reference);bindTarget(instance,app.template,'L2','knowledge',reference.id);
  const nestedTemplate=app.state.structureTemplates.find(item=>item.id==='builtin:regular-polygon'),nested=createStructureInstance(nestedTemplate,app.knowledge.id,{sides:6});app.state.structureInstances.push(nested);bindTarget(instance,app.template,'L2','structure',nested.id);
  addContainerContent(instance,'L2',{id:'qa-definition',type:'content',content:{title:'拉格朗日定理',summary:'有限群子群阶的整除性质。',body:'# 拉格朗日定理\n\n若 $H\\le G$，则群的阶满足：\n\n$$|H|\\mid |G|$$\n\n这是一段用于阅读页验证的正文。',contentType:'theorem',tags:['群论','定理']}},definition);
  addContainerContent(instance,'L2',{id:'qa-formula',type:'formula',content:{title:'阶数公式',body:'$$|G|=[G:H]|H|$$',contentType:'custom'}},definition);
  app.scheduleSave('qa:seed');app.renderAll();
});
await page.waitForTimeout(160);

const l2=page.locator('.scene-node[data-slot-id="L2"]');
const nodeState={label:await l2.locator('.node-label').textContent(),count:await l2.locator('.node-content-count').textContent(),edgeOpacity:await page.locator('.scene-edge').first().evaluate(element=>getComputedStyle(element).opacity||'1'),fontSize:await l2.locator('.node-label').evaluate(element=>parseFloat(getComputedStyle(element).fontSize))};
await page.screenshot({path:'outputs/v4.2-canvas.png',fullPage:true});
await l2.click();await page.waitForTimeout(120);
const container={visible:await page.locator('#containerDocument').isVisible(),title:await page.locator('.container-document-header h1').textContent(),cards:await page.locator('.container-document-item').count(),persistentSection:await page.locator('.container-content-main').count(),dynamicSection:await page.locator('.container-dynamic-section').count(),oldWords:(await page.locator('#containerDocument').innerText()).match(/runtime|instance|persistent/gi)??[]};
container.excerpt=await page.locator('[data-container-item-id="qa-definition"] .content-card-excerpt').textContent();container.formulaRendered=await page.locator('[data-container-item-id="qa-formula"] .math-typeset').count();
const beforeDraft=await page.evaluate(()=>lmnWorkspace.instance.containers.L2.children.length);await page.locator('.container-document-header .primary').click();await page.locator('#contextMenu button',{hasText:'正文'}).click();await page.waitForTimeout(60);await page.locator('.document-editor-top button[title="返回"]').click();await page.waitForTimeout(80);container.draftDiscarded=(await page.evaluate(()=>lmnWorkspace.instance.containers.L2.children.length))===beforeDraft;

await page.locator('[data-container-item-id="qa-definition"]').click();await page.waitForTimeout(100);
const content={readingVisible:await page.locator('#contentDocument').isVisible(),title:await page.locator('.reading-header h1').textContent(),paper:await page.locator('.reading-page').isVisible(),formula:await page.locator('.reading-page .math-typeset').count(),breadcrumbs:await page.locator('#breadcrumbs .crumb').allTextContents()};
await page.screenshot({path:'outputs/v4.2-reading-wide.png',fullPage:true});
await page.locator('.reading-header button',{hasText:'编辑'}).click();await page.waitForTimeout(70);content.modes=await page.locator('.document-editor-top button').evaluateAll(nodes=>nodes.map(node=>node.textContent).filter(label=>['编辑','预览','分屏'].includes(label)));await page.locator('.document-editor-top button',{hasText:'分屏'}).click();await page.waitForTimeout(50);content.split=await page.locator('.document-editor-shell.mode-split').isVisible();content.formCount=await page.locator('.document-editor-page').count();if(!content.formCount)throw new Error(`Document editor missing: ${JSON.stringify({errors,document:await page.evaluate(()=>lmnWorkspace.document),html:(await page.locator('#contentDocumentContent').innerHTML()).slice(0,1200)})}`);const titleInput=page.locator('.document-title-input');await titleInput.fill('拉格朗日定理（已校订）');await page.locator('.document-editor-top button[title="返回"]').click();await page.waitForTimeout(90);content.savedTitle=await page.locator('.reading-header h1').textContent();

await page.locator('#backBtn').click();await page.waitForTimeout(100);const historyResult={afterBackDocument:await page.evaluate(()=>lmnWorkspace.document)};await page.locator('#forwardBtn').click();await page.waitForTimeout(100);historyResult.afterForwardDocument=await page.evaluate(()=>lmnWorkspace.document);historyResult.browserState=await page.evaluate(()=>history.state?.lmnLocation?.document??null);

await page.locator('.document-tab',{hasText:'LMN'}).first().click();await page.waitForTimeout(100);await page.evaluate(()=>document.querySelector('.scene-edge-hit')?.dispatchEvent(new MouseEvent('click',{bubbles:true})));await page.waitForTimeout(70);
const relation={selected:await page.locator('.scene-edge-group.selected').count(),panel:await page.locator('#floatingPanel').isVisible(),type:await page.locator('#panelContent input[list]').inputValue(),directionDisabled:await page.locator('#panelContent select').first().isDisabled()};await page.locator('#panelTabs button',{hasText:'线型'}).click();relation.appearanceFields=await page.locator('#panelContent .field').count();await page.locator('#panelTabs button',{hasText:'关系'}).click();await page.locator('#panelContent button',{hasText:'打开关系正文'}).click();await page.waitForTimeout(70);relation.readingEditor=await page.locator('.content-editor-shell').isVisible();relation.modes=await page.locator('.content-editor-modes button').allTextContents();

await page.locator('#moreBtn').click();const globalMenu=await page.locator('#contextMenu').innerText();await page.locator('#contextMenu button',{hasText:'高清晰度'}).click();const clarity=await page.locator('#appShell').getAttribute('data-high-clarity');
await page.locator('#moreBtn').click();await page.locator('#contextMenu button',{hasText:'导出 / 备份'}).click();const exportPreview={visible:await page.locator('#exportPreview').isVisible(),text:await page.locator('#exportPreview').innerText()};await page.locator('#exportDialog .dialog-close').click();
await page.setViewportSize({width:760,height:720});const responsive={breadcrumbs:await page.locator('#breadcrumbs').isVisible(),more:await page.locator('#moreBtn').isVisible(),content:await page.locator('#contentDocument').isVisible()};await page.screenshot({path:'outputs/v4.2-content-reading.png',fullPage:true});

await page.evaluate(()=>{const app=lmnWorkspace;app.activateDocument(`structure:${app.currentInstanceId}`);app.removeContainerItem('L2','qa-definition')});await page.waitForTimeout(80);const undo={visible:await page.locator('#undoBanner').isVisible(),label:await page.locator('#undoBannerText').textContent()};await page.locator('#undoDeleteAction').click();await page.waitForTimeout(80);undo.restored=await page.evaluate(()=>lmnWorkspace.instance.containers.L2.children.some(item=>item.id==='qa-definition'));

const result={baseline,nodeState,container,content,history:historyResult,relation,globalMenu,clarity,exportPreview,responsive,undo,errors};console.log(JSON.stringify(result,null,2));await browser.close();
if(errors.length||baseline.version!=='V4.2.1 RC'||baseline.nodes!==9||baseline.oldSystems!==0||nodeState.edgeOpacity!=='1'||nodeState.fontSize<12||!container.visible||container.cards!==4||container.persistentSection!==1||container.dynamicSection!==0||container.oldWords.length||!/有限群子群阶/.test(container.excerpt)||container.formulaRendered<1||!container.draftDiscarded||!content.readingVisible||!content.paper||content.formula<1||content.modes.length!==3||!content.split||content.savedTitle!=='拉格朗日定理（已校订）'||!historyResult.afterBackDocument.startsWith('content-edit:')||!historyResult.afterForwardDocument.startsWith('content:')||historyResult.browserState!==historyResult.afterForwardDocument||relation.selected!==1||!relation.panel||!relation.type||!relation.directionDisabled||relation.appearanceFields<5||!relation.readingEditor||relation.modes.length!==3||globalMenu.includes('删除知识')||globalMenu.includes('删除结构')||!globalMenu.includes('偏好设置')||clarity!=='true'||!exportPreview.visible||!exportPreview.text.includes('Knowledge')||!exportPreview.text.includes('Content')||!responsive.breadcrumbs||!responsive.more||!responsive.content||!undo.visible||undo.label!=='正文或引用已删除'||!undo.restored)process.exitCode=1;
