import {createRequire} from 'node:module';
import fs from 'node:fs';

const require=createRequire(import.meta.url),{chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('outputs',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1536,height:960}}),errors=[];
page.on('pageerror',error=>errors.push(error.stack||error.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))errors.push(message.text())});
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});await page.evaluate(()=>new Promise(resolve=>{localStorage.clear();const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=resolve;request.onblocked=resolve}));await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.lmnWorkspace);

await page.evaluate(async()=>{const[{createKnowledge},{createStructureInstance},{setLocalDisplayTitle}]=await Promise.all([import('/packages/domain/core.js'),import('/packages/structure-engine/model.js'),import('/packages/domain/identity.js')]),app=lmnWorkspace,knowledge=createKnowledge('V4.2.1 RC 浏览器验收');app.state.knowledge.push(knowledge);const ids=['builtin:mod-n','builtin:boolean-algebra','builtin:poset-hasse','builtin:venn-3','builtin:directed-graph'];for(const id of ids){const template=app.state.structureTemplates.find(item=>item.id===id),parameters=id==='builtin:mod-n'?{modulus:12}:id==='builtin:boolean-algebra'?{rank:4}:id==='builtin:poset-hasse'?{starter:'diamond'}:{};app.state.structureInstances.push(createStructureInstance(template,knowledge.id,parameters))}app.currentKnowledgeId=knowledge.id;app.currentInstanceId=app.state.structureInstances[0].id;app.document=`structure:${app.currentInstanceId}`;app.path=[];const mod=app.instance;mod.variables=[{id:'hour_internal',label:'时',displayName:'时',kind:'input',type:'integer',value:10,showOnCanvas:false},{id:'wenchang_internal',label:'文昌',displayName:'文昌',kind:'derived',type:'integer',formula:'hour_internal + 2',expression:{op:'add',args:[{var:'hour_internal'},{value:2}]},showOnCanvas:true,resultSpace:mod.resultSpace},{id:'wenqu_internal',label:'文曲',displayName:'文曲',kind:'derived',type:'integer',formula:'hour_internal + 4',expression:{op:'add',args:[{var:'hour_internal'},{value:4}]},showOnCanvas:true,resultSpace:mod.resultSpace}];mod.runtimeState.variables.hour_internal=10;setLocalDisplayTitle(mod,'mod-0','零元位置');app.fitPending=true;app.renderAll()});await page.waitForTimeout(220);

const noEdit={button:await page.locator('#editModeButton').count(),shortcut:(await page.locator('body').innerText()).includes('拓扑编辑')};
const modStructure={nodes:await page.locator('.scene-node').count(),tokens:await page.locator('.scene-token').count()};
const residue=page.locator('.scene-node[data-slot-id="mod-0"]');await residue.focus();await page.waitForTimeout(500);modStructure.preview=await residue.locator('.node-hover-tooltip').innerText();modStructure.previewVisible=await residue.locator('.node-hover-tooltip').evaluate(element=>Number.parseFloat(getComputedStyle(element).opacity)>0);modStructure.renamed=await residue.locator('.node-label').textContent();

await page.evaluate(()=>{const app=lmnWorkspace;app.openPanel('structure',app.currentInstanceId,'view')});await page.waitForTimeout(80);await page.locator('#panelContent .field',{hasText:'显示模式'}).locator('select').selectOption('chart');await page.waitForTimeout(220);
const chart={tokens:await page.locator('.scene-token').allTextContents(),whiteDots:await page.locator('.scene-token').evaluateAll(nodes=>nodes.filter(node=>getComputedStyle(node).borderRadius==='50%').length),list:await page.locator('#modularVariableList button[data-variable-id]').allTextContents()};
if(await page.locator('.scene-token').count()){const token=page.locator('.scene-token').first();await token.hover();chart.hoverLinked=await page.locator('#modularVariableList button.active').count();await token.click();await page.waitForTimeout(60);chart.detail=await page.locator('.variable-detail').isVisible()}
await page.screenshot({path:'outputs/v4.2.1-modular-chart.png',fullPage:true});

const structureResults={};for(const id of['builtin:boolean-algebra','builtin:poset-hasse','builtin:venn-3','builtin:directed-graph']){await page.evaluate(templateId=>{const app=lmnWorkspace,instance=app.state.structureInstances.find(item=>item.templateId===templateId);app.openInstance(instance.id)},id);await page.waitForTimeout(180);const nodes=page.locator('.scene-node'),boxes=await nodes.evaluateAll(items=>items.map(item=>{const r=item.getBoundingClientRect();return[Math.round(r.x),Math.round(r.y),Math.round(r.width),Math.round(r.height)]}));structureResults[id]={nodes:await nodes.count(),visualKinds:[...new Set(await nodes.evaluateAll(items=>items.map(item=>item.dataset.visualKind)))],uniqueBoxes:new Set(boxes.map(item=>item.join(':'))).size,edges:await page.locator('.scene-edge').count()};if(id==='builtin:venn-3')await page.screenshot({path:'outputs/v4.2.1-venn.png',fullPage:true})}

await page.locator('#insertStructure').click();const graphAddMenu=await page.locator('#contextMenu').innerText();await page.keyboard.press('Escape');
await page.evaluate(()=>{const app=lmnWorkspace;app.selection=new Set([...app.currentDefinition.edges.slice(0,2).map(edge=>`edge:${edge.id}`)]);app.openPanel('structure',app.currentInstanceId,'relations')});await page.waitForTimeout(80);const color=page.locator('#panelContent .field',{hasText:'颜色'}).locator('input');await color.fill('#d14f45');await color.blur();await page.waitForTimeout(120);const relationStyle={preview:await page.evaluate(()=>Object.values(lmnWorkspace.instance.relationStyles.edgeOverrides).map(item=>item.color))};await page.locator('.relation-style-actions button',{hasText:'应用'}).click();await page.waitForTimeout(80);relationStyle.applied=await page.evaluate(()=>Object.keys(lmnWorkspace.instance.relationStyles.edgeOverrides).length);await page.evaluate(()=>lmnWorkspace.undo());relationStyle.afterUndo=await page.evaluate(()=>Object.keys(lmnWorkspace.instance.relationStyles.edgeOverrides).length);

await page.evaluate(()=>{const app=lmnWorkspace;app.openPanel('structure',app.currentInstanceId,'info')});await page.locator('#panelSource').click();await page.waitForTimeout(160);const source={visible:await page.locator('#sourceWorkbench').isVisible(),lines:await page.locator('#sourceLineNumbers').innerText(),initialValid:await page.locator('.source-valid').isVisible()};const editor=page.locator('#structureSourceEditor'),initial=await editor.inputValue(),next=initial.replace('container A {','container A {\n    local-title "源代码节点 A"');await editor.fill(next);await page.waitForTimeout(380);source.draftStatus=await page.locator('#sourceDraftStatus').textContent();source.previewLabel=await page.locator('#sourcePreviewCanvas').innerText().catch(()=>null);source.applyEnabled=await page.locator('#sourceApply').isEnabled();await page.locator('#sourceApply').click();await page.waitForTimeout(120);await page.locator('#sourceBack').click();await page.waitForTimeout(160);source.canvasTitle=await page.locator('.scene-node[data-slot-id="A"] .node-label').textContent();await page.evaluate(()=>lmnWorkspace.openStructureSource(lmnWorkspace.currentInstanceId));await page.waitForTimeout(100);await page.locator('#structureSourceEditor').fill((await page.locator('#structureSourceEditor').inputValue())+'\n???');await page.waitForTimeout(380);source.invalidDiagnostic=await page.locator('.source-diagnostic.error').count();await page.screenshot({path:'outputs/v4.2.1-source-workbench.png',fullPage:true});await page.locator('#sourceBack').click();

await page.evaluate(()=>{const app=lmnWorkspace;app.libraryFilter='variables';app.openLibrary()});await page.waitForTimeout(80);const schemes={sections:await page.locator('.template-section-title').allTextContents(),cards:await page.locator('.variable-scheme-card').count(),importAction:await page.locator('.scheme-import-card').isVisible()};await page.locator('.variable-scheme-card .scheme-card-menu').first().click();schemes.builtinMenu=await page.locator('#contextMenu').innerText();await page.keyboard.press('Escape');await page.locator('#structureLibrary .dialog-close').click();

const tab=page.locator('.document-tab').filter({hasText:'Graph'}).first();if(await tab.count()){await tab.click({button:'right'});source.tabMenu=await page.locator('#contextMenu').innerText();await page.keyboard.press('Escape')}
await page.setViewportSize({width:760,height:720});await page.waitForTimeout(80);const responsive={sourceLayout:await page.locator('#sourceWorkbench').count(),toolbar:await page.locator('.topbar').isVisible(),overflow:await page.locator('#openDocumentsButton').isVisible()};

const result={noEdit,modStructure,chart,structureResults,graphAddMenu,relationStyle,source,schemes,responsive,errors};console.log(JSON.stringify(result,null,2));await browser.close();
const kinds=structureResults,failed=errors.length||noEdit.button||noEdit.shortcut||modStructure.nodes!==12||modStructure.tokens!==0||!modStructure.previewVisible||!/位置 0|零元位置/.test(modStructure.preview)||!/文昌/.test(modStructure.preview)||/hour_internal|\+ 2/.test(modStructure.preview)||modStructure.renamed!=='零元位置'||chart.tokens.length<2||chart.whiteDots||chart.hoverLinked<1||!chart.detail||kinds['builtin:boolean-algebra'].nodes!==16||!kinds['builtin:boolean-algebra'].visualKinds.includes('boolean-node')||kinds['builtin:poset-hasse'].nodes!==4||!kinds['builtin:poset-hasse'].visualKinds.includes('hasse-node')||kinds['builtin:venn-3'].nodes!==7||!kinds['builtin:venn-3'].visualKinds.includes('venn-region')||kinds['builtin:directed-graph'].nodes!==3||!/添加节点|添加关系/.test(graphAddMenu)||relationStyle.applied!==2||relationStyle.afterUndo!==0||!source.visible||!source.initialValid||!source.applyEnabled||source.canvasTitle!=='源代码节点 A'||source.invalidDiagnostic<1||schemes.cards<5||!schemes.importAction||!/复制为我的方案|隐藏/.test(schemes.builtinMenu)||!/关闭其他|关闭右侧/.test(source.tabMenu??'')||!responsive.toolbar;if(failed)process.exitCode=1;
