import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('outputs',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});
await page.evaluate(()=>new Promise(resolve=>{const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=resolve;request.onblocked=resolve}));await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(400);if(!await page.evaluate(()=>!!globalThis.lmnWorkspace)){console.error(JSON.stringify({startup:await page.locator('#runtimeStatus').textContent(),errors},null,2));await browser.close();process.exit(2)}
await page.locator('[data-welcome="knowledge"]').click();await page.locator('#quickCreateInput').fill('群论');await page.locator('#quickCreateInput').press('Enter');await page.waitForTimeout(350);
const lmn={nodes:await page.locator('.scene-node').count(),edges:await page.locator('.scene-edge').count(),columns:await page.locator('.scene-node[data-slot-id^="L"],.scene-node[data-slot-id^="M"],.scene-node[data-slot-id^="N"]').count()};
for(const zoom of[.25,.5,1,1.5,2.5]){await page.evaluate(value=>lmnWorkspace.setZoom(value),zoom);await page.waitForTimeout(30);const geometry=await page.evaluate(()=>({zoom:lmnWorkspace.view.zoom,node:lmnWorkspace.currentScene.nodes[0],edge:lmnWorkspace.currentScene.edges[0],transform:getComputedStyle(document.querySelector('#sceneRoot')).transform}));if(!geometry.edge.path||!geometry.transform)errors.push(`missing geometry at zoom ${zoom}`)}
await page.setViewportSize({width:1100,height:720});await page.waitForTimeout(250);const resized=await page.evaluate(()=>({nodes:lmnWorkspace.currentScene.nodes.length,finite:lmnWorkspace.currentScene.edges.every(edge=>Number.isFinite(edge.start.x)&&Number.isFinite(edge.end.y))}));await page.evaluate(()=>lmnWorkspace.fit());await page.waitForTimeout(80);
await page.locator('.scene-node[data-slot-id="L2"]').dblclick();await page.locator('#pickerNewKnowledge').click();await page.locator('#quickCreateInput').fill('对称群');await page.locator('#quickCreateInput').press('Enter');await page.waitForTimeout(300);const recursive={crumbs:await page.locator('.crumb').allTextContents(),depth:await page.evaluate(()=>lmnWorkspace.path.length),parentBound:await page.evaluate(()=>lmnWorkspace.state.structureInstances.find(item=>item.ownerKnowledgeId===lmnWorkspace.state.knowledge.find(k=>k.title==='群论').id).bindings.some(binding=>binding.slotId==='L2'))};
await page.evaluate(()=>lmnWorkspace.goHistory(-1));await page.waitForTimeout(180);await page.locator('#insertStructure').click();await page.locator('.template-card',{hasText:'Boolean Algebra'}).click();await page.waitForTimeout(320);const boolean={nodes:await page.locator('.scene-node').count(),edges:await page.locator('.scene-edge').count()};
await page.locator('[data-mode="edit"]').click();await page.locator('.scene-node').first().click({button:'right'});const nodeMenu=await page.locator('#contextMenu').isVisible();await page.keyboard.press('Escape');
await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.currentInstanceId,'parameters'));const rankInput=page.locator('#panelContent input').first();await rankInput.fill('3');await rankInput.blur();await page.waitForTimeout(300);const booleanAfterRank=await page.locator('.scene-node').count();
await page.locator('#insertStructure').click();await page.locator('.template-card',{hasText:'Zi Wei'}).click();await page.waitForTimeout(300);const ziwei={nodes:await page.locator('.scene-node').count(),tokens:await page.locator('.scene-token').evaluateAll(nodes=>nodes.map(node=>node.title))};await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.currentInstanceId,'parameters'));const hourInput=page.locator('#panelContent input').nth(1);await hourInput.fill('10');await hourInput.blur();await page.waitForTimeout(280);ziwei.afterHour10=await page.locator('.scene-token').evaluateAll(nodes=>nodes.map(node=>node.title));
await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>lmnWorkspace.fit());await page.screenshot({path:'outputs/v4-desktop.png',fullPage:true});
const result={lmn,resized,recursive,boolean,booleanAfterRank,nodeMenu,ziwei,errors};console.log(JSON.stringify(result,null,2));await browser.close();if(errors.length||lmn.nodes!==9||lmn.edges!==10||!resized.finite||!recursive.parentBound||boolean.nodes!==16||booleanAfterRank!==8||ziwei.nodes!==12||ziwei.tokens.length!==2)process.exitCode=1;
