import {createRequire} from 'node:module';
import fs from 'node:fs';

const require=createRequire(import.meta.url),{chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('outputs',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),context=await browser.newContext({viewport:{width:1536,height:960},serviceWorkers:'block'}),page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.stack||error.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))errors.push(message.text())});
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});await page.evaluate(()=>new Promise(resolve=>{localStorage.clear();const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=resolve;request.onblocked=resolve}));await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.lmnWorkspace);

await page.evaluate(async()=>{const[{createKnowledge},{createStructureInstance,bindTarget},{addContainerContent}]=await Promise.all([import('/packages/domain/core.js'),import('/packages/structure-engine/model.js'),import('/packages/domain/semantic-container.js')]),app=lmnWorkspace,knowledge=createKnowledge('V4.2.2 浏览器验收'),reference=createKnowledge('可复用知识 A');app.state.knowledge.push(knowledge,reference);const create=(id,parameters={})=>{const template=app.state.structureTemplates.find(item=>item.id===id),instance=createStructureInstance(template,knowledge.id,parameters);app.state.structureInstances.push(instance);return instance},graph=create('builtin:directed-graph'),coordinate=create('builtin:coordinate-plane',{dimension:'2d',scale:40}),poset=create('builtin:poset-hasse',{starter:'relation-text',relationText:'a < b < c'}),boolean=create('builtin:boolean-algebra',{rank:3}),venn=create('builtin:venn-2');const graphTemplate=app.state.structureTemplates.find(item=>item.id===graph.templateId),definition=(await import('/packages/structure-engine/model.js')).materializeInstanceDefinition(graphTemplate,graph),content=addContainerContent(graph,'A',{type:'content',content:{title:'统一正文',body:'正文 $x^2$ 与 **Markdown**',summary:'统一编辑器',contentType:'note'}},definition);bindTarget(venn,app.state.structureTemplates.find(item=>item.id===venn.templateId),'intersection','knowledge',reference.id,{placementMode:'reference'});bindTarget(graph,graphTemplate,'B','knowledge',reference.id,{placementMode:'construct'});app.__qa={knowledgeId:knowledge.id,referenceId:reference.id,graphId:graph.id,coordinateId:coordinate.id,posetId:poset.id,booleanId:boolean.id,vennId:venn.id,contentId:content.id};app.currentKnowledgeId=knowledge.id;app.currentInstanceId=graph.id;app.document='notes';app.path=[];app.dismissedEmpty.add(knowledge.id);app.renderAll()});await page.waitForTimeout(180);

const result={version:await page.locator('.brand em').textContent(),errors};
result.plusCount={navigator:await page.locator('#newKnowledge,#openLibrary').count(),tabs:await page.locator('.document-tab.add').count(),top:await page.locator('#insertStructure').count()};
await page.locator('#insertStructure').click();result.newTab={visible:await page.locator('#newTabPage').isVisible(),actions:await page.locator('[data-new-tab-action]').count()};await page.screenshot({path:'outputs/v4.2.2-new-tab.png',fullPage:true});await page.locator('[data-new-tab-action="notes"]').click();await page.waitForTimeout(80);
result.notes={editor:await page.locator('#notesEditorHost .document-editor-page').count(),latex:await page.locator('#notesEditorHost .document-format-toolbar button',{hasText:'∑'}).count()};await page.locator('#notesEditorHost .document-body-editor').fill('# Notes\n\n$E=mc^2$');await page.locator('#notesEditorHost .document-editor-top button',{hasText:'分屏'}).click();await page.waitForTimeout(80);result.notes.preview=await page.locator('#notesEditorHost .katex').count();await page.screenshot({path:'outputs/v4.2.2-editor.png',fullPage:true});

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.graphId);app.openContentDocument('A',app.__qa.contentId)});await page.waitForTimeout(80);result.content={editor:await page.locator('#contentDocument .document-editor-page').count(),body:await page.locator('#contentDocument .document-body-editor').inputValue()};await page.evaluate(()=>{const app=lmnWorkspace,instance=app.state.structureInstances.find(item=>item.id===app.__qa.graphId),template=app.state.structureTemplates.find(item=>item.id===instance.templateId);app.openInstance(instance.id);app.openRelationDocument(template.edges[0].id)});await page.waitForTimeout(80);result.relation={editor:await page.locator('#contentDocument .document-editor-page').count(),formulaField:await page.locator('#contentDocument .document-properties-grid label',{hasText:'显示公式'}).count()};

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.graphId);app.openStructureSource(app.__qa.graphId)});await page.waitForTimeout(120);await page.locator('#sourceFind').click();await page.locator('#sourceSearchInput').fill('container');await page.waitForTimeout(40);result.source={searchVisible:await page.locator('#sourceSearchBar').isVisible(),matches:await page.locator('#sourceSearchCount').textContent()};const canvasBox=await page.locator('#sourcePreviewCanvas').boundingBox(),svgBox=await page.locator('#sourcePreviewCanvas svg').boundingBox();result.source.centered=Math.abs((canvasBox.x+canvasBox.width/2)-(svgBox.x+svgBox.width/2))<3&&Math.abs((canvasBox.y+canvasBox.height/2)-(svgBox.y+svgBox.height/2))<3;await page.locator('#sourceReplaceInput').fill('container');await page.locator('#sourceReplaceOne').click();result.source.replaceWorked=(await page.locator('#structureSourceEditor').inputValue()).includes('container');await page.evaluate(()=>{const app=lmnWorkspace;app.sourceSession.diagnostics=Array.from({length:40},(_,index)=>({line:index+1,column:1,severity:'error',message:`诊断 ${index+1}`}));app.renderSourceDiagnostics()});await page.locator('#sourceDiagnostics').hover();await page.mouse.wheel(0,650);await page.waitForTimeout(50);result.source.diagnosticsScrolled=await page.locator('#sourceDiagnostics').evaluate(element=>element.scrollTop>0);

result.source.layout=await page.evaluate(()=>Object.fromEntries(['sourceWorkbench','sourceSearchBar','sourceWorkbenchSplit','sourcePreviewCanvas','sourceDiagnostics'].map(id=>{const element=document.getElementById(id),box=element.getBoundingClientRect();return[id,{top:box.top,height:box.height,display:getComputedStyle(element).display,position:getComputedStyle(element).position}]})));await page.screenshot({path:'outputs/v4.2.2-source.png',fullPage:true});await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.graphId);app.renameContainerDisplayLabel('A')});await page.locator('#textPromptInput').fill('重命名节点 A');await page.locator('#textPromptConfirm').click();await page.waitForTimeout(100);result.rename={dialogClosed:!(await page.locator('#textPromptDialog').isVisible()),label:await page.locator('.scene-node[data-slot-id="A"] .node-label').textContent()};

await page.evaluate(()=>lmnWorkspace.renameStructureInstance(lmnWorkspace.__qa.graphId));await page.locator('#textPromptInput').fill('可视结构图');await page.locator('#textPromptConfirm').click();await page.waitForTimeout(80);result.rename.structure=await page.evaluate(()=>lmnWorkspace.state.structureInstances.find(item=>item.id===lmnWorkspace.__qa.graphId).displayTitle);await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.coordinateId);app.openPanel('structure',app.__qa.coordinateId,'plot')});await page.waitForTimeout(80);result.plot={workbench:await page.locator('.plot-workbench').count(),legacyVisible:await page.locator('#templateGrid',{hasText:'Vector Space Basis'}).count()};await page.locator('.plot-presets button',{hasText:'心形线'}).click();await page.locator('.plot-expression-form .primary').click();await page.waitForTimeout(130);result.plot.curves=await page.locator('#backgroundLayer .coordinate-curve').count();await page.locator('.plot-dimension button',{hasText:'三维'}).click();await page.waitForTimeout(130);result.plot.zAxis=await page.locator('#backgroundLayer .coordinate-z-axis').count();await page.locator('.plot-object-form').first().locator('input[name="x"]').fill('2');await page.locator('.plot-object-form').first().locator('input[name="y"]').fill('1');await page.locator('.plot-object-form').first().locator('input[name="z"]').fill('3');await page.locator('.plot-object-form').first().locator('button').click();await page.waitForTimeout(80);result.plot.pointAdded=await page.evaluate(()=>lmnWorkspace.currentDefinition.slots.some(slot=>slot.semanticCoordinate?.z===3));

await page.screenshot({path:'outputs/v4.2.2-plot.png',fullPage:true});await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.posetId));await page.waitForTimeout(100);result.poset={nodes:await page.locator('.scene-node').count(),edges:await page.locator('.scene-edge').count()};await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.booleanId));await page.waitForTimeout(100);result.boolean={edges:await page.locator('.scene-edge').count(),labels:await page.locator('.edge-label').count()};await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.vennId));await page.waitForTimeout(100);const venn=page.locator('.scene-node[data-slot-id="intersection"]');result.venn={label:await venn.locator('.node-label').textContent(),summary:await venn.locator('.node-summary').textContent(),width:await venn.evaluate(element=>Number.parseFloat(element.style.width))};

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.graphId);app.openContainer('B');app.navigatorMode='outline';app.renderNavigator()});await page.waitForTimeout(80);result.navigator={title:await page.locator('#navigatorTitle').textContent(),active:await page.locator('.nav-structure-row.active').count(),constructText:(await page.locator('#navigatorContent').innerText()).includes('可复用知识 A')};
const widths=await page.locator('.document-tab:not(.add)').evaluateAll(nodes=>nodes.map(node=>Math.round(node.getBoundingClientRect().width)));result.tabs={widths,uniform:new Set(widths).size<=1};await page.screenshot({path:'outputs/v4.2.2-qa.png',fullPage:true});
if(result.rename.structure!=='可视结构图')errors.push('结构重命名未持久化');console.log(JSON.stringify(result,null,2));await browser.close();
const failed=errors.length||result.version!=='V4.2.2 RC'||result.plusCount.navigator!==0||result.plusCount.tabs!==1||result.plusCount.top!==1||!result.newTab.visible||result.newTab.actions!==6||result.notes.editor!==1||result.notes.latex!==1||result.notes.preview<1||result.content.editor!==1||!result.content.body.includes('x^2')||result.relation.editor!==1||result.relation.formulaField!==1||!result.source.searchVisible||!/\d+ \/ \d+/.test(result.source.matches)||!result.source.centered||!result.source.replaceWorked||!result.source.diagnosticsScrolled||!result.rename.dialogClosed||result.rename.label!=='重命名节点 A'||result.plot.workbench!==1||result.plot.curves<1||result.plot.zAxis<1||!result.plot.pointAdded||result.poset.nodes!==3||result.poset.edges!==2||result.boolean.edges!==12||result.boolean.labels!==0||result.venn.label!=='A∩B'||!result.venn.summary.includes('可复用知识 A')||result.venn.width<150||result.navigator.title!=='知识导航'||!result.navigator.active||!result.navigator.constructText||!result.tabs.uniform;if(failed)process.exitCode=1;
