import {createRequire} from 'node:module';

const require=createRequire(import.meta.url),{chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),context=await browser.newContext({viewport:{width:1536,height:960},serviceWorkers:'block'}),page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.stack||error.message));
page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))errors.push(message.text())});
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});
await page.evaluate(()=>new Promise(resolve=>{localStorage.clear();const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=resolve;request.onblocked=resolve}));
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.lmnWorkspace);

await page.evaluate(async()=>{
  const[{createKnowledge},{createStructureInstance,bindTarget}]=await Promise.all([import('/packages/domain/core.js'),import('/packages/structure-engine/model.js')]),app=lmnWorkspace,alpha=createKnowledge('Alpha'),beta=createKnowledge('Beta');
  app.state.knowledge.push(alpha,beta);
  const create=(id,parameters={})=>{const template=app.state.structureTemplates.find(item=>item.id===id),instance=createStructureInstance(template,alpha.id,parameters);app.state.structureInstances.push(instance);return instance};
  const lmn=create('builtin:lmn-432'),polygon=create('builtin:regular-polygon',{n:5}),coordinate=create('builtin:coordinate-plane',{dimension:'3d',scale:40}),poset=create('builtin:poset-hasse',{starter:'numeric'}),graph=create('builtin:directed-graph'),proof=create('builtin:proof-tree'),timeline=create('builtin:timeline'),modular=create('builtin:mod-n',{modulus:12}),legacy=create('builtin:vector-space',{dimension:'3d'}),matrix=create('builtin:matrix-grid',{rows:3,columns:4,cellPrefix:'m'});
  coordinate.plotExpressions=[{id:'wide',label:'全视域正弦',source:'y=sin(x)',rangeMode:'viewport',color:'#2f7658'},{id:'surface',label:'曲面',source:'paraboloid(a=.18)',rangeMode:'viewport',color:'#c8922e'}];
  coordinate.motionPoints=[{id:'motion',plotId:'wide',label:'M',start:-4,end:4,current:0,mode:'pingpong',duration:4,playing:false}];
  modular.variables=[{id:'hour',label:'时辰',type:'integer',kind:'derived',formula:'2',showOnCanvas:true,icon:'星',color:'#7657a8'}];bindTarget(lmn,app.state.structureTemplates.find(item=>item.id==='builtin:lmn-432'),'L1','structure',legacy.id,{placementMode:'construct'});
  app.__qa={alpha:alpha.id,beta:beta.id,lmn:lmn.id,polygon:polygon.id,coordinate:coordinate.id,poset:poset.id,graph:graph.id,proof:proof.id,timeline:timeline.id,modular:modular.id,legacy:legacy.id,matrix:matrix.id};app.currentKnowledgeId=alpha.id;app.openInstance(lmn.id,false);
});
await page.waitForTimeout(180);

const result={errors,version:await page.locator('.brand em').textContent(),topCommand:await page.locator('#globalSearch span').textContent(),topNewHidden:await page.locator('#insertStructure').evaluate(element=>element.hidden||getComputedStyle(element).display==='none'),navigatorModes:await page.locator('[data-navigator]').count(),tabPlus:await page.locator('.document-tab.add').evaluate(element=>({radius:getComputedStyle(element).borderRadius,weight:getComputedStyle(element).fontWeight}))};

result.lmn=await page.evaluate(()=>{const app=lmnWorkspace,edges=app.currentDefinition.edges.filter(edge=>['e8','e10'].includes(edge.id));app.instance.relationStyles.structureDefault={color:'#123456',width:2.5,routing:'bezier',arrow:'both',labelPosition:'center'};app.renderScene();return{directions:edges.map(edge=>[edge.sourceSlotId,edge.targetSlotId])}});
await page.waitForTimeout(80);result.lmn.markers=await page.locator('.scene-edge').first().evaluate(element=>({start:element.getAttribute('marker-start'),end:element.getAttribute('marker-end'),stroke:element.style.stroke}));

await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.polygon));await page.waitForTimeout(100);
result.polygon={edges:await page.locator('.scene-edge').count(),arrows:await page.locator('.scene-edge[marker-end]').count()};

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.poset);app.instance.structureView.arrangement='horizontal';app.renderScene()});await page.waitForTimeout(80);
result.poset=await page.evaluate(()=>{const nodes=Object.fromEntries(lmnWorkspace.currentScene.nodes.map(node=>[node.id,node.x]));return{nodes,relationText:lmnWorkspace.instance.parameters.relationText}});

await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.coordinate));await page.waitForTimeout(80);await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.__qa.coordinate,'variables'));await page.waitForTimeout(120);
result.coordinate={tabs:await page.locator('#panelTabs button').allTextContents(),variables:await page.locator('.coordinate-variable-row').count(),visibility:await page.locator('.coordinate-variable-row .visibility-toggle').count(),surfaces:await page.locator('.coordinate-surface-mesh').count()};
await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.__qa.coordinate,'plot'));await page.waitForTimeout(80);
result.coordinate.operation={switches:await page.locator('.coordinate-operation-switch button').allTextContents(),geometry:await page.locator('.coordinate-operation-section').count()};
await page.evaluate(()=>{lmnWorkspace.coordinateOperationMode='algebra';lmnWorkspace.renderPanel()});await page.waitForTimeout(50);result.coordinate.operation.algebra=(await page.locator('.coordinate-operation-section').allTextContents()).join('\n');
await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.__qa.coordinate,'settings'));await page.waitForTimeout(50);result.coordinate.projections=await page.locator('#panelContent select').allTextContents();
result.coordinate.camera={labels:await page.locator('.camera-angle-control>span').allTextContents(),before:await page.evaluate(()=>{const node=lmnWorkspace.currentScene.nodes.find(item=>item.id==='P');return[node.x,node.y]})};await page.locator('.camera-angle-control input[type="range"]').first().fill('91');await page.waitForTimeout(160);result.coordinate.camera.after=await page.evaluate(()=>{const node=lmnWorkspace.currentScene.nodes.find(item=>item.id==='P');return[node.x,node.y]});
result.coordinate.fixedObjects={displayOnly:await page.locator('.scene-node.display-only-node').count(),contentIndicators:await page.locator('.scene-node.display-only-node .node-content-indicators').count(),draggable:await page.locator('.scene-node.display-only-node[draggable="true"]').count()};
result.coordinate.motion={before:await page.evaluate(()=>lmnWorkspace.instance.motionPoints.find(item=>item.id==='motion').current)};await page.evaluate(()=>lmnWorkspace.toggleMotionPoint('motion'));await page.waitForTimeout(260);result.coordinate.motion.after=await page.evaluate(()=>lmnWorkspace.instance.motionPoints.find(item=>item.id==='motion').current);await page.evaluate(()=>lmnWorkspace.toggleMotionPoint('motion'));

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.proof);app.instance.structureView.arrangement='horizontal-forward';app.renderScene()});await page.waitForTimeout(90);result.proof=await page.evaluate(()=>Object.fromEntries(lmnWorkspace.currentScene.nodes.map(node=>[node.role,node.x])));
await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.matrix));await page.waitForTimeout(90);result.matrix={nodes:await page.locator('.scene-node.visual-matrix-cell').count(),brackets:await page.locator('.matrix-bracket').count(),labels:await page.locator('.matrix-axis-label').count()};

await page.locator('[data-navigator="search"]').click();await page.waitForTimeout(80);result.search={modes:await page.locator('.search-mode-switch button').allTextContents()};
await page.getByRole('button',{name:'结构检索'}).click();await page.waitForTimeout(80);result.search.workbench=await page.locator('#searchWorkbench:not(.hidden)').count();
await page.evaluate(()=>lmnWorkspace.addStructureQuery('builtin:lmn-432'));await page.waitForTimeout(60);result.search.queryCards=await page.locator('.search-query-ast-card').count();result.search.visualNodes=await page.locator('.query-visual-stage .scene-node').count();result.search.inspector=await page.locator('.query-visual-inspector').count();result.search.results=await page.locator('.search-result-card').count();
await page.locator('#cognitiveGoal').fill('理解 Alpha');await page.locator('#cognitiveDomain').fill('哲学');await page.locator('#runCognitiveAuto').click();await page.waitForTimeout(80);result.cognitive={autoButton:await page.getByRole('button',{name:/自动组织/}).count(),summaryCards:await page.locator('.cognitive-summary-card').count(),recommendation:await page.locator('.cognitive-summary-card.wide').first().textContent(),runtimeError:await page.locator('#cognitiveActivationResults .search-navigation-error').count()};
await page.locator('[data-navigator="library"]').click();await page.waitForTimeout(60);result.library={newStructure:await page.getByRole('button',{name:'＋ 新建结构'}).count(),cards:await page.locator('.nav-library-card').count(),bilingual:await page.locator('.nav-library-card b').evaluateAll(nodes=>nodes.filter(node=>node.textContent.includes(' · ')).length)};await page.getByRole('button',{name:/新建结构/}).click();await page.waitForTimeout(50);result.library.builder={open:await page.locator('#quickBuilderDialog[open]').count(),nodes:await page.locator('#builderVisualCanvas .visual-builder-node').count(),lklButton:await page.getByRole('button',{name:/LKL 1/}).count()};await page.locator('#quickBuilderDialog .dialog-close').first().click();

await page.locator('#globalSearch').click();await page.waitForTimeout(50);await page.locator('#commandInput').fill('Alpha');await page.waitForTimeout(50);result.command={placeholder:await page.locator('#commandInput').getAttribute('placeholder'),knowledgeLeak:await page.locator('#commandResults').getByRole('button',{name:/Alpha/}).count(),rows:await page.locator('#commandResults .command-row').count()};await page.keyboard.press('Escape');
result.tabs=await page.evaluate(()=>{const app=lmnWorkspace;app.activateDocument('notes',false,app.__qa.alpha);app.activateDocument('notes',false,app.__qa.beta);app.openNewTab();app.openNewTab();const labels=app.openTabs.map(tab=>app.describeOpenTab(tab)?.label),newTabs=app.openTabs.filter(tab=>tab.id.startsWith('new-tab')),before=app.openTabs.length,closing=app.activeTabKey;app.closeDocument(closing);return{labels,newTabs:newTabs.length,unique:new Set(newTabs.map(tab=>tab.key)).size,before,after:app.openTabs.length,closed:!app.openTabs.some(tab=>tab.key===closing),boardAction:document.querySelectorAll('[data-new-tab-action="board"]').length,boardWorkspace:document.querySelectorAll('#boardWorkspace').length}});

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.timeline);app.navExpanded().add(`structure:${app.__qa.timeline}`);app.renderNavigator();app.openInstance(app.__qa.legacy)});await page.waitForTimeout(100);result.knowledge={title:await page.locator('#navigatorTitle').textContent(),activeStructures:await page.locator('#navigatorContent .nav-structure-row.active').count(),currentLabel:await page.locator('#navigatorContent .nav-structure-row.active .nav-structure-open span').first().textContent(),timelineCollapsed:await page.evaluate(()=>!lmnWorkspace.navExpanded().has(`structure:${lmnWorkspace.__qa.timeline}`)),otherCollapsed:await page.locator('.nav-other-knowledge.collapsed').count(),rootGroups:await page.locator('#navigatorContent>.nav-group').count(),resizer:await page.locator('#navigatorResizer').count(),overflowX:await page.locator('#navigatorContent').evaluate(element=>getComputedStyle(element).overflowX)};

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.modular);app.openPanel('structure',app.__qa.modular,'variables');app.openVariableDetail('hour')});await page.waitForTimeout(80);result.modular={detailLabels:await page.locator('.variable-detail .field>label').allTextContents()};

await page.evaluate(()=>lmnWorkspace.openGlobalSettings());await page.waitForTimeout(60);const theme=page.locator('[data-global-pref="theme"]'),fontSize=page.locator('[data-global-pref="fontSize"]');await theme.selectOption('paper');await fontSize.fill('18');await page.waitForTimeout(70);result.preferences=await page.evaluate(()=>({theme:document.documentElement.dataset.theme,fontSize:getComputedStyle(document.querySelector('#appShell')).fontSize,accent:getComputedStyle(document.documentElement).getPropertyValue('--green').trim()}));

console.log(JSON.stringify(result,null,2));
const checks=[
  ['no runtime errors',!errors.length],['V4.3.2 version',result.version==='V4.3.2'],['command top bar',result.topCommand==='命令行'&&result.topNewHidden],['three global modules',result.navigatorModes===3],['prominent tab plus',result.tabPlus.radius==='50%'&&Number(result.tabPlus.weight)>=700],
  ['LMN corrected directions',JSON.stringify(result.lmn.directions)===JSON.stringify([['N1','M2'],['N2','M3']])],['double-ended SVG arrows',!!result.lmn.markers.start&&!!result.lmn.markers.end&&['#123456','rgb(18, 52, 86)'].includes(result.lmn.markers.stroke)],['polygon arrows',result.polygon.edges===5&&result.polygon.arrows===5],
  ['horizontal poset order',result.poset.nodes.n0<result.poset.nodes.n1&&result.poset.nodes.n1<result.poset.nodes.n2&&result.poset.nodes.n2<result.poset.nodes.n3],['poset text sync',result.poset.relationText==='0 < 1\n1 < 2\n2 < 3'],
  ['unified coordinate variables',result.coordinate.tabs.includes('变量')&&result.coordinate.tabs.includes('操作')&&result.coordinate.variables>=5&&result.coordinate.visibility===result.coordinate.variables],['coordinate surfaces',result.coordinate.surfaces>10],['fixed coordinate objects',result.coordinate.fixedObjects.displayOnly>=3&&result.coordinate.fixedObjects.contentIndicators===0&&result.coordinate.fixedObjects.draggable===0],['motion point advances',Number.isFinite(result.coordinate.motion.after)&&result.coordinate.motion.after!==result.coordinate.motion.before],['algebra and geometry operations',result.coordinate.operation.switches.includes('代数')&&result.coordinate.operation.switches.includes('几何')&&/极限/.test(result.coordinate.operation.algebra)&&/积分/.test(result.coordinate.operation.algebra)&&/级数/.test(result.coordinate.operation.algebra)],['plane projections',result.coordinate.projections.some(text=>text.includes('xOy')&&text.includes('yOz')&&text.includes('xOz')&&text.includes('自由'))],['live aligned camera controls',JSON.stringify(result.coordinate.camera.labels)===JSON.stringify(['水平方位角','垂直俯仰角'])&&JSON.stringify(result.coordinate.camera.before)!==JSON.stringify(result.coordinate.camera.after)],['proof forward order',result.proof.premise<result.proof.inference&&result.proof.inference<result.proof.conclusion],['real matrix grid',result.matrix.nodes===12&&result.matrix.brackets===2&&result.matrix.labels===7],
  ['three search modes',JSON.stringify(result.search.modes)===JSON.stringify(['结构检索','全文检索','LKL 检索'])],['native visual structure workbench',result.search.workbench===1&&result.search.queryCards===1&&result.search.visualNodes===9&&result.search.inspector===1&&result.search.results>=1],['structure library create',result.library.newStructure===1&&result.library.cards>10&&result.library.bilingual>10],['visual structure builder',result.library.builder.open===1&&result.library.builder.nodes===3&&result.library.builder.lklButton>=1],['command/search separation',result.command.knowledgeLeak===0],['browser tab instances',result.tabs.newTabs===2&&result.tabs.unique===2&&result.tabs.after===result.tabs.before-1&&result.tabs.closed&&result.tabs.labels.some(label=>label==='Alpha · Notes')&&result.tabs.labels.some(label=>label==='Beta · Notes')],['board UI retired',result.tabs.boardAction===0&&result.tabs.boardWorkspace===0],['tracked knowledge tree',result.knowledge.title==='知识库'&&result.knowledge.activeStructures>=1&&/(Vector Space Basis|向量空间基)/.test(result.knowledge.currentLabel)&&result.knowledge.timelineCollapsed&&result.knowledge.otherCollapsed>=1&&result.knowledge.rootGroups>=2&&result.knowledge.resizer===1&&['auto','scroll'].includes(result.knowledge.overflowX)],['modular detail removes ineffective appearance duplication',!result.modular.detailLabels.some(label=>/显示公式|图标|颜色|显示在结构中/.test(label))],['live theme and font preferences',result.preferences.theme==='paper'&&result.preferences.fontSize==='18px'&&result.preferences.accent==='#326f91']
  ,['visible cognitive compilation',result.cognitive.autoButton===1&&result.cognitive.summaryCards>=4&&/知识与关系视图/.test(result.cognitive.recommendation)&&result.cognitive.runtimeError===0]
];
for(const[name,ok]of checks)if(!ok)errors.push(`FAILED: ${name}`);
if(errors.length){console.error(errors.join('\n'));process.exitCode=1}
await browser.close();
