import {createRequire} from 'node:module';

const require=createRequire(import.meta.url),{chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),context=await browser.newContext({viewport:{width:1536,height:960},serviceWorkers:'block'}),page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.stack||error.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('favicon'))errors.push(message.text())});
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});await page.evaluate(()=>new Promise(resolve=>{localStorage.clear();const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=resolve;request.onblocked=resolve}));await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!globalThis.lmnWorkspace);

await page.evaluate(async()=>{const[{createKnowledge},{createStructureInstance}]=await Promise.all([import('/packages/domain/core.js'),import('/packages/structure-engine/model.js')]),app=lmnWorkspace,alpha=createKnowledge('Alpha'),beta=createKnowledge('Beta');app.state.knowledge.push(alpha,beta);const create=(id,parameters={})=>{const template=app.state.structureTemplates.find(item=>item.id===id),instance=createStructureInstance(template,alpha.id,parameters);app.state.structureInstances.push(instance);return instance},lmn=create('builtin:lmn-432'),polygon=create('builtin:regular-polygon',{n:5}),coordinate=create('builtin:coordinate-plane',{dimension:'3d',scale:40}),timeline=create('builtin:timeline');app.__qa={alpha:alpha.id,beta:beta.id,lmn:lmn.id,polygon:polygon.id,coordinate:coordinate.id,timeline:timeline.id};app.currentKnowledgeId=alpha.id;app.openInstance(lmn.id,false)});await page.waitForTimeout(150);

const result={version:await page.locator('.brand em').textContent(),errors};
await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.__qa.lmn,'settings'));await page.waitForTimeout(60);result.settings={tabs:await page.locator('#panelTabs button').allTextContents(),labels:await page.locator('#panelContent label span').allTextContents()};
await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.__qa.lmn,'design'));await page.waitForTimeout(60);result.design={node:await page.locator('.design-node-controls').count(),edge:await page.locator('.design-edge-controls').count(),apply:await page.getByRole('button',{name:'应用到全部'}).count()};await page.locator('.design-node-controls input[type="color"]').first().fill('#778899');await page.locator('.design-node-controls input[type="color"]').first().dispatchEvent('change');await page.locator('.design-edge-controls input[type="color"]').first().fill('#334455');await page.locator('.design-edge-controls input[type="color"]').first().dispatchEvent('change');await page.getByRole('button',{name:'应用到全部'}).click();await page.waitForTimeout(80);result.design.applied=await page.evaluate(()=>({node:lmnWorkspace.instance.designStyles.nodeDefault.fill,relation:lmnWorkspace.instance.relationStyles.structureDefault.color,typeOverrides:Object.keys(lmnWorkspace.instance.relationStyles.typeOverrides).length,edgeOverrides:Object.keys(lmnWorkspace.instance.relationStyles.edgeOverrides).length,scene:[...new Set(lmnWorkspace.currentScene.edges.map(edge=>edge.visual.color))]}));
await page.evaluate(()=>lmnWorkspace.openInstance(lmnWorkspace.__qa.polygon));await page.evaluate(()=>lmnWorkspace.openPanel('structure',lmnWorkspace.__qa.polygon,'settings'));result.polygonLabels=await page.locator('#panelContent label span').allTextContents();

await page.evaluate(()=>lmnWorkspace.openStructureConfiguration('builtin:poset-hasse',false,true));await page.waitForTimeout(60);result.defaults={lkl:await page.locator('.template-default-lkl').count(),containsRelationText:(await page.locator('.template-default-lkl').inputValue()).includes('relationText')};await page.evaluate(()=>structureConfigDialog.close());

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.coordinate);app.openPanel('structure',app.__qa.coordinate,'plot');app.addPlotExpression('sphere(cx=0, cy=0, cz=0, r=2)')});await page.waitForTimeout(180);result.coordinate={surfaces:await page.locator('.coordinate-surface-mesh').count(),ticks:await page.locator('.coordinate-tick-3d').count(),deleteCurve:await page.getByRole('button',{name:'删除曲线 / 曲面'}).count(),tabs:await page.locator('#panelTabs button').allTextContents()};
await page.evaluate(()=>{const app=lmnWorkspace;app.removePlotExpression(app.instance.plotExpressions[0].id);app.addPlotExpression('circle(cx=0, cy=0, r=2)')});await page.waitForTimeout(80);await page.evaluate(()=>{const app=lmnWorkspace,plot=app.instance.plotExpressions[0];app.addMotionPoint(plot.id,{label:'M',start:0,end:Math.PI*2,mode:'pingpong',duration:2});app.openPanel('structure',app.currentInstanceId,'plot');app.selection=new Set([`plot:${plot.id}`]);app.renderPanel()});await page.waitForTimeout(60);result.coordinate.motion=await page.locator('.motion-point-row').count();

await page.evaluate(()=>lmnWorkspace.openStructureSource(lmnWorkspace.__qa.coordinate));await page.waitForTimeout(80);await page.locator('#sourcePreviewIn').click();result.preview={zoom:await page.locator('#sourcePreviewZoom').textContent(),scrollable:await page.locator('#sourcePreviewCanvas').evaluate(element=>getComputedStyle(element).overflow)};

await page.evaluate(()=>{const app=lmnWorkspace;app.openInstance(app.__qa.timeline);const before=app.currentDefinition.edges.length;app.addTimelineNode();app.__qa.timelineBefore=before});await page.waitForTimeout(100);result.timeline=await page.evaluate(()=>({before:lmnWorkspace.__qa.timelineBefore,after:lmnWorkspace.currentDefinition.edges.length,last:lmnWorkspace.currentDefinition.edges.at(-1)}));

await page.evaluate(()=>lmnWorkspace.openKnowledge(lmnWorkspace.__qa.alpha));await page.waitForTimeout(80);result.knowledge={title:await page.locator('#navigatorTitle').textContent(),options:await page.locator('.nav-knowledge-switcher option').count(),menu:await page.locator('.nav-knowledge-switcher .nav-row-menu').count()};await page.locator('.nav-knowledge-switcher .nav-row-menu').click();result.knowledge.menuText=await page.locator('#contextMenu').innerText();

console.log(JSON.stringify(result,null,2));
const failed=errors.length||result.version!=='V4.2.4 RC'||!result.settings.tabs.includes('设置')||!result.settings.tabs.includes('设计')||!result.settings.labels.includes('排列方式')||result.settings.labels.includes('旋转角度')||!result.polygonLabels.includes('旋转角度')||result.design.node!==1||result.design.edge!==1||result.design.apply!==1||result.design.applied.node!=='#778899'||result.design.applied.relation!=='#334455'||result.design.applied.typeOverrides||result.design.applied.edgeOverrides||result.design.applied.scene.length!==1||result.design.applied.scene[0]!=='#334455'||result.defaults.lkl!==1||!result.defaults.containsRelationText||result.coordinate.surfaces<20||result.coordinate.ticks<5||result.coordinate.deleteCurve!==1||result.coordinate.motion!==1||result.preview.zoom!=='125%'||result.preview.scrollable!=='auto'||result.timeline.after!==result.timeline.before+1||result.timeline.last.label!=='演化'||result.timeline.last.visual?.labelPosition!=='center'||result.knowledge.title!=='知识库'||result.knowledge.options!==2||result.knowledge.menu!==1||!result.knowledge.menuText.includes('删除知识');if(failed)process.exitCode=1;
await browser.close();
