import {createRequire} from 'node:module';
import path from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/magni/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:4174/apps/web/',{waitUntil:'networkidle'});
await page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.deleteDatabase('lmn-knowledge-system');request.onsuccess=resolve;request.onerror=()=>reject(request.error);request.onblocked=resolve}));
await page.reload({waitUntil:'networkidle'});
await page.locator('[data-welcome="knowledge"]').click();
await page.waitForTimeout(100);
const knowledgeOnly=await page.evaluate(async()=>({instances:(await new Promise((resolve,reject)=>{const request=indexedDB.open('lmn-knowledge-system',3);request.onsuccess=()=>{const read=request.result.transaction('structureInstances').objectStore('structureInstances').getAll();read.onsuccess=()=>resolve(read.result);read.onerror=()=>reject(read.error)};request.onerror=()=>reject(request.error)})).length,title:document.querySelector('#workspaceTitle').textContent}));
await page.locator('#insertStructure').click();
await page.locator('.template-card',{hasText:'Regular n-gon'}).click();
await page.waitForTimeout(150);
const polygon6=await page.locator('.polygon-slot').count();
await page.locator('.inspector-tabs [data-tab="rules"]').click();
const nInput=page.locator('.parameter-row input').first();await nInput.fill('5');await nInput.press('Enter');await nInput.blur();await page.waitForTimeout(150);
const polygon5=await page.locator('.polygon-slot').count();
await page.locator('#insertStructure').click();await page.locator('.template-card',{hasText:'Modular Ring'}).click();await page.waitForTimeout(150);
const modular={slots:await page.locator('.radial-slot').count(),variables:await page.locator('.variable-token').evaluateAll(nodes=>nodes.map(node=>node.title))};
await page.locator('.inspector-tabs [data-tab="rules"]').click();const aInput=page.locator('.parameter-row input').nth(1);await aInput.fill('5');await aInput.press('Enter');await aInput.blur();await page.waitForTimeout(150);modular.afterA5=await page.locator('.variable-token').evaluateAll(nodes=>nodes.map(node=>node.title));
await page.locator('#insertStructure').click();await page.locator('.template-card',{hasText:'LMN 4–3–2'}).click();await page.waitForTimeout(150);
const lmn={columns:await page.locator('.slot-column').count(),slots:await page.locator('.slot-card').count()};
await page.locator('.slot-card[data-slot-id="L2"]').click();await page.locator('#pickerNewKnowledge').click();await page.waitForTimeout(150);
const knowledgeBinding=await page.evaluate(()=>{const instance=lmnWorkspace.instance(lmnWorkspace.currentInstanceId);return instance.bindings.find(binding=>binding.slotId==='L2')});
await page.locator('.slot-card[data-slot-id="L3"]').click();await page.locator('#pickerNestedStructure').click();await page.locator('.template-card',{hasText:'Poset / Hasse'}).click();await page.waitForTimeout(150);
const nesting=await page.evaluate(()=>{const parent=lmnWorkspace.state.structureInstances.find(instance=>instance.templateId==='builtin:lmn-432');return{instanceCount:lmnWorkspace.state.structureInstances.length,binding:parent.bindings.find(binding=>binding.slotId==='L3')}});
const downloadPromise=page.waitForEvent('download');await page.locator('#exportBtn').click();const download=await downloadPromise,bundlePath=path.resolve('outputs/v3-browser-roundtrip.json');await download.saveAs(bundlePath);
const beforeRoundTrip=await page.evaluate(()=>({knowledge:lmnWorkspace.state.knowledge.length,instances:lmnWorkspace.state.structureInstances.length,bindings:lmnWorkspace.state.structureInstances.reduce((sum,instance)=>sum+instance.bindings.length,0)}));
await page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('lmn-knowledge-system',3);request.onsuccess=()=>{const db=request.result,stores=['knowledge','relations','representations','structureTemplates','structureInstances'],tx=db.transaction(stores,'readwrite');stores.forEach(store=>tx.objectStore(store).clear());tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)};request.onerror=()=>reject(request.error)}));
await page.reload({waitUntil:'networkidle'});await page.locator('#fileInput').setInputFiles(bundlePath);await page.locator('#confirmImport').click();await page.waitForTimeout(200);
const afterRoundTrip=await page.evaluate(()=>({knowledge:lmnWorkspace.state.knowledge.length,instances:lmnWorkspace.state.structureInstances.length,bindings:lmnWorkspace.state.structureInstances.reduce((sum,instance)=>sum+instance.bindings.length,0)}));
await page.screenshot({path:'outputs/v3-desktop.png',fullPage:true});
console.log(JSON.stringify({knowledgeOnly,polygon6,polygon5,modular,lmn,knowledgeBinding,nesting,beforeRoundTrip,afterRoundTrip,errors},null,2));
await browser.close();
