import test from 'node:test';
import assert from 'node:assert/strict';
import {createKnowledge,createRelation,createRepresentation} from '../packages/domain/core.js';
import {analyzeCyclicElement} from '../packages/structure-engine/cyclic-group.js';
import {getBuiltinTemplate,materializeTemplate} from '../packages/structure-engine/templates.js';
import {applyVariableScheme,createVariableScheme,ZI_WEI_BASIC_SCHEME} from '../packages/structure-engine/variable-schemes.js';
import {createStructureInstance,duplicateVariable,moveVariable,removeVariable,updateVariable,variableDeletionImpact} from '../packages/structure-engine/model.js';
import {runInstance} from '../packages/structure-engine/evaluator.js';
import {deleteKnowledgeObject,deleteStructureObject,deleteUserTemplateObject,knowledgeDeletionImpact,structureDeletionImpact,userTemplateDeletionImpact} from '../packages/domain/object-management.js';
import {cycleReferenceLabel,semanticNavigatorSearch,structureNavigatorSummary} from '../packages/navigation/navigator-model.js';
import {isParameterizedTemplate,libraryEntries,librarySection} from '../packages/ui/library-model.js';
import {migrateV3ToV4} from '../packages/structure-engine/migration.js';
import {parseFormula} from '../packages/structure-engine/formula.js';

test('Cyclic Group is parameterized and reports generators without rejecting other elements',()=>{
  const template=getBuiltinTemplate('builtin:cyclic-group'),c8=materializeTemplate(template,{n:8,generator:3,notation:'cyclic'}),generator=analyzeCyclicElement(8,3),nonGenerator=analyzeCyclicElement(8,2),c12=materializeTemplate(template,{n:12,generator:5});
  assert.equal(isParameterizedTemplate(template),true);assert.equal(c8.slots.length,8);assert.equal(c12.slots.length,12);assert.deepEqual(generator,{...generator,isGenerator:true,gcd:1,order:8,subgroupSize:8,orbitCount:1});assert.equal(nonGenerator.isGenerator,false);assert.equal(nonGenerator.order,4);assert.equal(nonGenerator.subgroupSize,4);assert.deepEqual(nonGenerator.subgroup,[0,2,4,6]);assert.deepEqual(nonGenerator.validGenerators,[1,3,5,7]);
});

test('Zi Wei is a variable scheme on Modular Ring and every formula follows modulus',()=>{
  const template=getBuiltinTemplate('builtin:mod-n'),instance=createStructureInstance(template,null,{modulus:12});applyVariableScheme(instance,ZI_WEI_BASIC_SCHEME);instance.runtimeState.variables.hour=10;let result=runInstance(instance,materializeTemplate(template,instance.parameters));assert.deepEqual(result.results,{wenchang:0,wenqu:2});instance.parameters.modulus=10;result=runInstance(instance,materializeTemplate(template,instance.parameters));assert.deepEqual(result.results,{wenchang:8,wenqu:4});assert.ok(instance.variables.every(variable=>!variable.formula||!/,\s*12\s*\)/.test(variable.formula)));const saved=createVariableScheme('Calendar',instance);assert.equal(saved.variables.length,6);assert.equal(saved.parameters.modulus,10);assert.equal('bindings'in saved,false);
});

test('legacy Mod-12 migration reparses formulas against the modulus parameter',()=>{
  const legacyTemplate=getBuiltinTemplate('builtin:mod-12'),legacy=createStructureInstance(legacyTemplate,null,{modulus:12});legacy.variables=[{id:'hour',label:'时',kind:'input',type:'integer',value:8},{id:'legacyStar',label:'旧星位',kind:'derived',type:'integer',formula:'mod(hour + 4, 12)',expression:parseFormula('mod(hour + 4, 12)')}];legacy.runtimeState.variables.hour=8;const migrated=migrateV3ToV4({schemaVersion:3,knowledge:[],relations:[],representations:[],structureTemplates:[legacyTemplate],structureInstances:[legacy]});const instance=migrated.structureInstances[0],template=getBuiltinTemplate('builtin:mod-n');instance.parameters.modulus=10;const result=runInstance(instance,materializeTemplate(template,instance.parameters));assert.equal(instance.id,legacy.id);assert.equal(instance.templateId,'builtin:mod-n');assert.equal(instance.variables[1].formula,'mod(hour + 4, modulus)');assert.equal(result.results.legacyStar,2);
});

test('Variable CRUD supports rename, duplicate, reorder, visibility, dependency impact and delete',()=>{
  const template=getBuiltinTemplate('builtin:mod-n'),instance=createStructureInstance(template);applyVariableScheme(instance,ZI_WEI_BASIC_SCHEME);updateVariable(instance,'hour',{id:'clock',label:'时钟',showOnCanvas:true});assert.ok(instance.variables.find(item=>item.id==='wenchang').formula.includes('clock'));const copy=duplicateVariable(instance,'clock');assert.ok(copy.id.startsWith('clock_copy'));assert.equal(moveVariable(instance,copy.id,-1),true);updateVariable(instance,copy.id,{showOnCanvas:false});assert.equal(instance.variables.find(item=>item.id===copy.id).showOnCanvas,false);const impact=variableDeletionImpact(instance,'clock');assert.deepEqual(impact.map(item=>item.id).sort(),['wenchang','wenqu']);removeVariable(instance,copy.id);assert.equal(instance.variables.some(item=>item.id===copy.id),false);
});

test('Knowledge and Structure deletion expose impact and preserve unrelated Knowledge',()=>{
  const a=createKnowledge('A'),b=createKnowledge('B'),template=getBuiltinTemplate('builtin:directed-graph'),owned=createStructureInstance(template,a.id),external=createStructureInstance(template,b.id);external.bindings.push({id:'bind-a',instanceId:external.id,slotId:'A',targetType:'knowledge',targetId:a.id});external.bindings.push({id:'bind-structure',instanceId:external.id,slotId:'B',targetType:'structure',targetId:owned.id});const state={knowledge:[a,b],relations:[createRelation(a.id,b.id)],representations:[createRepresentation(a.id,'structure',{instanceId:owned.id})],structureTemplates:[template],structureInstances:[owned,external]};const impact=knowledgeDeletionImpact(state,a.id);assert.equal(impact.ownedStructures.length,1);assert.equal(impact.externalBindings.length,1);assert.equal(impact.nestedReferences.length,1);assert.equal(impact.relations.length,1);const snapshot=structuredClone(state);deleteKnowledgeObject(state,a.id);assert.deepEqual(state.knowledge.map(item=>item.title),['B']);assert.equal(state.structureInstances.length,1);assert.equal(external.bindings.length,0);Object.assign(state,snapshot);const structureImpact=structureDeletionImpact(state,owned.id);assert.equal(structureImpact.references.length,1);deleteStructureObject(state,owned.id);assert.equal(state.knowledge.length,2);assert.equal(state.structureInstances.length,1);
});

test('custom template deletion reports instances and removes only dependent structure objects',()=>{
  const knowledge=createKnowledge('Workspace'),base=getBuiltinTemplate('builtin:directed-graph'),custom={...structuredClone(base),id:'custom:temporary',name:'Temporary',builtin:false},owned=createStructureInstance(custom,knowledge.id),reference=createStructureInstance(base,knowledge.id);reference.bindings.push({id:'nested-custom',instanceId:reference.id,slotId:'A',targetType:'structure',targetId:owned.id});const state={knowledge:[knowledge],relations:[],representations:[createRepresentation(knowledge.id,'structure',{instanceId:owned.id})],structureTemplates:[base,custom],structureInstances:[owned,reference]};const impact=userTemplateDeletionImpact(state,custom.id);assert.equal(impact.instances.length,1);assert.equal(impact.references.length,1);deleteUserTemplateObject(state,custom.id);assert.equal(state.knowledge.length,1);assert.deepEqual(state.structureInstances.map(item=>item.id),[reference.id]);assert.equal(reference.bindings.length,0);assert.equal(state.structureTemplates.some(item=>item.id===custom.id),false);assert.throws(()=>deleteUserTemplateObject(state,base.id),/Built-in templates/);
});

test('Navigator summaries suppress large cell lists and semantic search keeps ancestry',()=>{
  const knowledge=createKnowledge('紫微斗数'),tableTemplate=getBuiltinTemplate('builtin:operation-table'),table=createStructureInstance(tableTemplate,knowledge.id,{n:4}),tableDefinition=materializeTemplate(tableTemplate,table.parameters),tableSummary=structureNavigatorSummary(tableTemplate,table,tableDefinition);assert.deepEqual(tableSummary.rows.map(item=>item.label),['元素','运算','表格']);assert.equal(tableSummary.rows.some(item=>item.children?.length===16),false);const booleanTemplate=getBuiltinTemplate('builtin:boolean-algebra'),boolean=createStructureInstance(booleanTemplate,knowledge.id,{rank:4}),booleanSummary=structureNavigatorSummary(booleanTemplate,boolean,materializeTemplate(booleanTemplate,boolean.parameters));assert.equal(booleanSummary.rows.length,5);const modular=getBuiltinTemplate('builtin:mod-n'),ring=createStructureInstance(modular,knowledge.id);applyVariableScheme(ring,ZI_WEI_BASIC_SCHEME);const state={knowledge:[knowledge],structureTemplates:[tableTemplate,booleanTemplate,modular],structureInstances:[table,boolean,ring]};const search=semanticNavigatorSearch(state,'文昌');assert.equal(search[0].path.join(' › '),'紫微斗数 › 模结构 Modular Ring · ℤ/nℤ › 派生变量 › 文昌');assert.equal(cycleReferenceLabel('群'),'↻ 引用：群');
});

test('Library hides legacy Zi Wei template and separates parameterized, completed, and custom entries',()=>{
  const templates=[getBuiltinTemplate('builtin:mod-12'),getBuiltinTemplate('builtin:cyclic-group'),getBuiltinTemplate('builtin:function-mapping'),{...getBuiltinTemplate('builtin:directed-graph'),id:'custom:graph',name:'My Graph',builtin:false}],state={structureTemplates:templates};const entries=libraryEntries(state);assert.equal(entries.some(item=>item.id==='builtin:mod-12'),false);assert.equal(librarySection(templates[1]),'parameterized');assert.equal(librarySection(templates[2]),'ready');assert.equal(librarySection(templates[3]),'my');assert.equal(getBuiltinTemplate('builtin:operation-table').name,'有限运算表 Finite Operation Table');
});
