import test from 'node:test';
import assert from 'node:assert/strict';
import {booleanComplement,booleanJoin,booleanMeet,generateBooleanAlgebra} from '../packages/structure-engine/boolean-algebra.js';
import {BUILTIN_TEMPLATES,getBuiltinTemplate,materializeTemplate} from '../packages/structure-engine/templates.js';
import {addInstanceEdge,addInstanceSlot,createStructureInstance,materializeInstanceDefinition,removeInstanceEdge,removeInstanceSlot,updateInstanceSlot} from '../packages/structure-engine/model.js';
import {runInstance} from '../packages/structure-engine/evaluator.js';
import {exportV4Bundle,importV4Bundle} from '../packages/structure-engine/bundle.js';

test('Boolean B4 generates 16 elements and only Hasse cover edges',()=>{const generated=generateBooleanAlgebra(4);assert.equal(generated.slots.length,16);assert.equal(generated.edges.length,32);assert.equal(booleanMeet(10,12),8);assert.equal(booleanJoin(10,5),15);assert.equal(booleanComplement(10,4),5);assert.equal(generated.slots.find(slot=>slot.id==='b15').semanticCoordinate.rank,4)});
test('Boolean template clamps rank to 8 and materializes compact B8',()=>{const template=getBuiltinTemplate('builtin:boolean-algebra'),resolved=materializeTemplate(template,{rank:12,displayMode:'bitset'});assert.equal(resolved.slots.length,256);assert.match(resolved.runtimeMetadata.warning,/256/)});
test('instance-local dynamic graph overrides add, rename, remove and persist 10 nodes / 15 edges',()=>{const template=getBuiltinTemplate('builtin:empty-custom'),instance=createStructureInstance(template);for(let index=0;index<10;index++)addInstanceSlot(instance,{id:`n${index}`,label:`Node ${index}`});for(let index=0;index<15;index++)addInstanceEdge(instance,`n${index%10}`,`n${(index+1)%10}`,{id:`e${index}`,relationType:'depends-on'});updateInstanceSlot(instance,'n0',{label:'Origin',role:'source'});removeInstanceEdge(instance,'e14');addInstanceEdge(instance,'n4','n9',{id:'e14b'});let resolved=materializeInstanceDefinition(template,instance);assert.equal(resolved.slots.length,10);assert.equal(resolved.edges.length,15);assert.equal(resolved.slots[0].label,'Origin');const state={knowledge:[],relations:[],representations:[],structureTemplates:BUILTIN_TEMPLATES,structureInstances:[instance]},roundTrip=importV4Bundle(exportV4Bundle(state),{knowledge:[],relations:[],representations:[],structureTemplates:[],structureInstances:[]});resolved=materializeInstanceDefinition(roundTrip.state.structureTemplates.find(item=>item.id===template.id),roundTrip.state.structureInstances[0]);assert.equal(resolved.slots.length,10);assert.equal(resolved.edges.length,15);removeInstanceSlot(instance,'n9');assert.equal(materializeInstanceDefinition(template,instance).slots.length,9)});
test('generic Mod-N and Zi Wei variables evaluate without A/B hardcoding',()=>{const generic=getBuiltinTemplate('builtin:mod-n'),ring=materializeTemplate(generic,{modulus:7});assert.equal(ring.slots.length,7);assert.equal(ring.edges.at(-1).targetSlotId,'mod-0');const ziwei=getBuiltinTemplate('builtin:mod-12'),instance=createStructureInstance(ziwei),initial=runInstance(instance,materializeInstanceDefinition(ziwei,instance));assert.deepEqual(initial.results,{wenchang:3,wenqu:11});instance.parameters.hour=10;const moved=runInstance(instance,materializeInstanceDefinition(ziwei,instance));assert.deepEqual(moved.results,{wenchang:0,wenqu:2})});
