import test from 'node:test';
import assert from 'node:assert/strict';
import {buildNavigatorIndex,flattenNavigator,revealNavigatorTarget,searchNavigatorIndex,navigatorObjectKey} from '../packages/navigation/location-index.js';
import {BUILTIN_TEMPLATES} from '../packages/structure-engine/templates.js';
import {createStructureInstance,bindTarget,addInstanceEdge,appendStructureNode} from '../packages/structure-engine/model.js';
import {structureCreateActions,edgeCapabilities} from '../packages/structure-engine/interaction-adapters.js';
const template=BUILTIN_TEMPLATES.find(t=>t.id==='builtin:directed-graph');
function fixture(){const root={id:'k:根',title:'根',content:'根正文'},child={id:'k:子',title:'子',content:'深层正文'},a=createStructureInstance(template,root.id),b=createStructureInstance(template,child.id);a.id='s:A:1';b.id='s:B:2';bindTarget(a,template,'A','knowledge',child.id,{placementMode:'construct'});bindTarget(a,template,'B','knowledge',child.id,{placementMode:'reference'});return{knowledge:[root,child],structureInstances:[a,b],structureTemplates:[template],placements:[{id:'p1',targetType:'structure',targetId:a.id,parentType:'knowledge',parentId:root.id,mode:'construct'},{id:'p2',targetType:'knowledge',targetId:child.id,parentType:'structure',parentId:a.id,path:'A',mode:'construct'}],knowledgePackages:[{rootKnowledgeId:root.id}],contentObjects:[{id:'orphan:content',title:'独立正文',body:'待归属'}]}}
test('one location index deduplicates construct records and preserves alternate reference appearances',()=>{const state=fixture(),index=buildNavigatorIndex(state),target=index.find({kind:'knowledge',id:'k:子'}),path=index.pathFor(target);assert.deepEqual(path.map(s=>s.id),['k:根','s:A:1','A','k:子']);const expanded=new Set(index.objects.keys()),rows=flattenNavigator(index,{expanded});assert.equal(rows.filter(e=>e.key===target.key&&!e.reference).length,1);assert.equal(rows.filter(e=>e.key===target.key&&e.reference).length,1);assert.equal(index.roots.some(e=>e.id==='orphan:content'),true);assert.equal(new Set(rows.map(e=>e.rowKey)).size,rows.length)});
test('search returns the same canonical deep address and reveal does not mutate state',()=>{const state=fixture(),before=JSON.stringify(state),index=buildNavigatorIndex(state),hit=searchNavigatorIndex(index,'深层正文')[0],expanded=new Set();assert.equal(hit.id,'k:子');assert.deepEqual(revealNavigatorTarget(index,hit,expanded),index.pathFor(hit));assert.equal(expanded.size,4);expanded.delete(index.find({kind:'structure',id:'s:A:1'}).key);assert.equal(flattenNavigator(index,{expanded}).some(e=>e.id==='k:子'),false);assert.equal(JSON.stringify(state),before)});
test('tuple keys avoid delimiter collisions and cycle recovery keeps every object reachable',()=>{assert.notEqual(navigatorObjectKey({kind:'slot',instanceId:'a:b',id:'c'}),navigatorObjectKey({kind:'slot',instanceId:'a',id:'b:c'}));const state=fixture();bindTarget(state.structureInstances[1],template,'A','knowledge','k:根',{placementMode:'construct'});const index=buildNavigatorIndex(state),rows=flattenNavigator(index,{expanded:new Set(index.objects.keys())});assert.ok(index.diagnostics.some(d=>d.type==='ownership-cycle'));for(const key of index.objects.keys())assert.ok(rows.some(r=>r.key===key))});
test('parameter families expose growth actions while mathematical canonical relations remain protected',()=>{const graph=createStructureInstance(template);assert.ok(edgeCapabilities(template,template.edges[0],graph).canChangeEndpoints);const center=BUILTIN_TEMPLATES.find(t=>t.id==='builtin:n-center'),instance=createStructureInstance(center);assert.ok(structureCreateActions(center).some(a=>a.id==='add-node'));appendStructureNode(instance,center);assert.equal(instance.parameters.nodeCount,5);const boolean=BUILTIN_TEMPLATES.find(t=>t.id==='builtin:boolean-algebra');assert.equal(edgeCapabilities(boolean,{id:'canonical'},createStructureInstance(boolean)).canChangeEndpoints,false);const e1=addInstanceEdge(graph,'A','B',{label:'r1'},{template}),e2=addInstanceEdge(graph,'A','B',{label:'r2'},{template});assert.notEqual(e1.id,e2.id)});

