const last=(block,key)=>block.statements.filter(item=>item.key===key).at(-1)??null;
const all=(block,key)=>block.statements.filter(item=>item.key===key);
const simple=statement=>{if(!statement)return undefined;const values=statement.values;if(values.length===1)return values[0];if(values.length===2&&['markdown','latex'].includes(values[0]))return{format:values[0],value:values[1]};return values};
const text=value=>String(value??'');
const reference=statement=>statement?.values?.length>=2?{type:text(statement.values[0]),id:text(statement.values[1])}:statement?.values?.length?{type:null,id:text(statement.values[0])}:null;
const provided=block=>[...new Set(block.statements.map(item=>item.key))];

function localizedFields(block,fallback=''){return{'zh-CN':text(simple(last(block,'name-zh-CN'))||simple(last(block,'title-zh-CN'))||fallback),en:text(simple(last(block,'name-en'))||simple(last(block,'title-en'))||fallback)}}
function compileKnowledge(block){const body=simple(last(block,'body')),aliases=simple(last(block,'aliases'))??all(block,'alias').map(value=>simple(value)),title=text(simple(last(block,'title'))||block.id);return{stableId:block.id,id:text(simple(last(block,'id'))||block.id),title,nameI18n:localizedFields(block,title),aliases:Array.isArray(aliases)?aliases:[aliases].filter(Boolean),summary:text(simple(last(block,'summary'))),body:text(body?.value??body),bodyFormat:body?.format??'markdown',tags:Array.isArray(simple(last(block,'tags')))?simple(last(block,'tags')):[],sources:all(block,'source').map(item=>simple(item)),provided:provided(block),loc:block.loc}}
function compileContent(block){const body=simple(last(block,'body')),latex=simple(last(block,'latex'));return{stableId:block.id,type:text(simple(last(block,'type'))||'note'),title:text(simple(last(block,'title'))||block.id),summary:text(simple(last(block,'summary'))),body:text(body?.value??body),bodyFormat:body?.format??'markdown',latex:text(latex?.value??latex),tags:Array.isArray(simple(last(block,'tags')))?simple(last(block,'tags')):[],sources:all(block,'source').map(item=>simple(item)),provided:provided(block),loc:block.loc}}
function compileContainer(block){return{slotId:block.id,title:text(simple(last(block,'title'))),localDisplayTitle:text(simple(last(block,'local-title'))),knowledgeRefs:all(block,'knowledge').map(item=>text(simple(item))),contentRefs:all(block,'content').map(item=>text(simple(item))),structureRefs:all(block,'structure').map(item=>text(simple(item))),variableRefs:all(block,'variable').map(item=>text(simple(item))),provided:provided(block),loc:block.loc}}
function compileVariable(block){const label=text(simple(last(block,'label'))||simple(last(block,'display-name'))||block.id);return{stableId:block.id,ownerRef:text(simple(last(block,'for'))||simple(last(block,'owner'))),label,displayName:text(simple(last(block,'display-name'))||label),nameI18n:localizedFields(block,label),group:text(simple(last(block,'group'))||'未分组'),order:Number(simple(last(block,'order'))??0)||0,kind:text(simple(last(block,'kind'))||'input'),type:text(simple(last(block,'type'))||'number'),value:simple(last(block,'value')),expression:text(simple(last(block,'expression'))||simple(last(block,'formula'))),displayFormula:text(simple(last(block,'display-formula'))),showOnCanvas:simple(last(block,'show'))!==false,provided:provided(block),loc:block.loc}}
function compileVariableScheme(block){const parameters={};for(const item of all(block,'parameter'))if(item.values.length>=2)parameters[text(item.values[0])]=item.values.at(-1);let viewDefaults={};try{viewDefaults=JSON.parse(text(simple(last(block,'view-defaults')))||'{}')}catch{}return{id:block.id,title:text(simple(last(block,'title'))||block.id),name:text(simple(last(block,'title'))||block.id),description:text(simple(last(block,'description'))),category:text(simple(last(block,'category'))||'mine'),builtin:simple(last(block,'builtin'))===true,parameters,variables:block.children.filter(item=>item.kind==='variable').map(variable=>{const compiled=compileVariable(variable);return{id:compiled.stableId,label:compiled.label,displayName:compiled.displayName,kind:compiled.kind,type:compiled.type,value:compiled.value,formula:compiled.expression,displayFormula:compiled.displayFormula,showOnCanvas:compiled.showOnCanvas}}),viewDefaults,favorite:simple(last(block,'favorite'))===true,hidden:simple(last(block,'hidden'))===true,createdAt:simple(last(block,'createdAt')),updatedAt:simple(last(block,'updatedAt')),loc:block.loc}}
function compileInstance(block){const parameters={};for(const item of all(block,'parameter'))if(item.values.length>=2)parameters[text(item.values[0])]=item.values.at(-1);const containers=block.children.filter(item=>item.kind==='container').map(compileContainer),variables=block.children.filter(item=>item.kind==='variable').map(compileVariable);let runtime={};try{runtime=JSON.parse(text(simple(last(block,'runtime')))||'{}')}catch{}return{stableId:block.id,templateRef:text(simple(last(block,'using'))),ownerRef:text(simple(last(block,'owner'))),title:text(simple(last(block,'title'))),parameters,containers,variables,runtime,provided:provided(block),loc:block.loc}}
function compileRelation(block){const body=simple(last(block,'body'));return{stableId:block.id,from:reference(last(block,'from')),to:reference(last(block,'to')),type:text(simple(last(block,'type'))||'related'),label:text(simple(last(block,'label'))),body:text(body?.value??body),bodyFormat:body?.format??'markdown',provided:provided(block),loc:block.loc}}
function compileOrientation(block){return{zeroAnchor:text(simple(last(block,'zero'))||simple(last(block,'zeroAnchor'))||'top'),direction:text(simple(last(block,'direction'))||'clockwise'),rotationAngle:Number(String(simple(last(block,'rotation'))??0).replace(/deg$/,''))||0}}
function compileView(block){const orientation=block.children.find(item=>item.kind==='orientation'),cameraBlock=block.children.find(item=>item.kind==='camera');let visibility={};try{visibility=JSON.parse(text(simple(last(block,'object-visibility')))||'{}')}catch{}return{stableId:block.id,forRef:text(simple(last(block,'for'))),focus:reference(last(block,'focus')),layout:text(simple(last(block,'layout'))),displayMode:text(simple(last(block,'mode'))||'structure'),orientation:compileOrientation(orientation??{statements:[]}),camera:{projection:text(simple(last(cameraBlock??{statements:[]},'projection'))||'free'),yaw:Number(simple(last(cameraBlock??{statements:[]},'yaw'))??42),pitch:Number(simple(last(cameraBlock??{statements:[]},'pitch'))??28)},previewPolicy:text(simple(last(block,'preview-policy'))||'compact'),objectVisibility:visibility,manualPositions:Object.fromEntries(block.children.filter(item=>item.kind==='position').map(item=>[item.id,{x:Number(simple(last(item,'x')))||0,y:Number(simple(last(item,'y')))||0}])),zoomPolicy:text(simple(last(block,'zoom-policy'))||'semantic'),semanticZoom:simple(last(block,'semantic-zoom'))!==false,savedZoom:simple(last(block,'zoom')),defaultFocus:text(simple(last(block,'default-focus'))),provided:provided(block),loc:block.loc}}
function compileEntry(block){const statement=block.statements.find(item=>['knowledge','structure','content','board'].includes(item.key));return{stableId:block.id,title:text(simple(last(block,'title'))||block.id),target:statement?{type:statement.key,id:text(simple(statement))}:null,loc:block.loc}}
function compileFrame(block){return{stableId:block.id,instanceRef:text(simple(last(block,'instance'))||simple(last(block,'structure'))),x:Number(simple(last(block,'x'))??0),y:Number(simple(last(block,'y'))??0),width:Number(simple(last(block,'width'))??520),height:Number(simple(last(block,'height'))??360),zIndex:Number(simple(last(block,'z-index'))??1),order:Number(simple(last(block,'order'))??0),previewPolicy:text(simple(last(block,'preview-policy'))||'detailed'),loc:block.loc}}
function compileBoard(block){return{stableId:block.id,title:text(simple(last(block,'title'))||block.id),description:text(simple(last(block,'description'))),ownerRef:text(simple(last(block,'owner'))),width:Number(simple(last(block,'width'))??1600),height:Number(simple(last(block,'height'))??1000),frames:block.children.filter(item=>item.kind==='frame').map(compileFrame),provided:provided(block),loc:block.loc}}
function compilePlacement(block){return{stableId:block.id,target:reference(last(block,'target')),parent:reference(last(block,'parent')),mode:text(simple(last(block,'mode'))||'construct'),order:Number(simple(last(block,'order'))??0),path:text(simple(last(block,'path'))),provided:provided(block),loc:block.loc}}
function compileTemplate(block){return{
  stableId:block.id,
  name:text(simple(last(block,'title'))||simple(last(block,'name'))||block.id),
  description:text(simple(last(block,'description'))),
  layout:{type:text(simple(last(block,'layout'))||'grid')},
  parameters:[],
  variables:[],
  constraints:[],
  rules:[],
  visual:{accent:'#557c91'},
  slots:block.children.filter(item=>item.kind==='slot').map(item=>({id:item.id,label:text(simple(last(item,'title'))||simple(last(item,'label'))||item.id),role:text(simple(last(item,'role'))||'custom'),semanticCoordinate:{order:Number(simple(last(item,'order')))||0},accepts:['knowledge','structure','value','variable'],cardinality:'many'})),
  edges:block.children.filter(item=>item.kind==='edge').map(item=>({id:item.id,sourceSlotId:text(simple(last(item,'from'))),targetSlotId:text(simple(last(item,'to'))),direction:text(simple(last(item,'direction'))||'directed'),relationType:text(simple(last(item,'type'))||'related')})),
  provided:provided(block),loc:block.loc
}}

export function compileLkl2Ast(ast){
  const packageBlock=ast.declarations.find(item=>item.kind==='package');if(!packageBlock)throw Object.assign(new Error('LKL 2 requires one package declaration'),{line:1,column:1,objectId:null,field:'package'});
  const declarations=[...ast.declarations,...packageBlock.children.filter(item=>item.kind!=='orientation')],packageId=text(simple(last(packageBlock,'id'))||packageBlock.id),root=reference(last(packageBlock,'root')),defaultEntry=text(simple(last(packageBlock,'default-view'))||simple(last(packageBlock,'defaultEntry'))||simple(last(packageBlock,'entry')));
  return{lklVersion:2,package:{stableId:packageId,title:text(simple(last(packageBlock,'title'))||packageBlock.id),description:text(simple(last(packageBlock,'description'))),version:text(simple(last(packageBlock,'version'))||'1.0'),migrationVersion:text(simple(last(packageBlock,'migrationVersion'))||simple(last(packageBlock,'migration-version'))||'4'),suggestedTheme:text(simple(last(packageBlock,'suggestedTheme'))||simple(last(packageBlock,'suggested-theme'))),createdAt:simple(last(packageBlock,'createdAt')),updatedAt:simple(last(packageBlock,'updatedAt')),language:simple(last(packageBlock,'language')),authors:simple(last(packageBlock,'authors'))??[],tags:simple(last(packageBlock,'tags'))??[],root,defaultEntry,loc:packageBlock.loc},knowledge:declarations.filter(item=>item.kind==='knowledge').map(compileKnowledge),contents:declarations.filter(item=>item.kind==='content').map(compileContent),structureTemplates:declarations.filter(item=>item.kind==='structure-template').map(compileTemplate),structureInstances:declarations.filter(item=>item.kind==='structure-instance').map(compileInstance),relations:declarations.filter(item=>item.kind==='relation').map(compileRelation),variables:declarations.filter(item=>item.kind==='variable').map(compileVariable),variableSchemes:declarations.filter(item=>item.kind==='variable-scheme').map(compileVariableScheme),views:declarations.filter(item=>item.kind==='view').map(compileView),boards:declarations.filter(item=>item.kind==='board').map(compileBoard),placements:declarations.filter(item=>item.kind==='placement').map(compilePlacement),entries:declarations.filter(item=>item.kind==='entry').map(compileEntry),sources:declarations.filter(item=>item.kind==='source').map(block=>({stableId:block.id,title:text(simple(last(block,'title'))||block.id),url:text(simple(last(block,'url'))),body:text(simple(last(block,'body'))),attachment:text(simple(last(block,'attachment'))),mediaType:text(simple(last(block,'media-type'))),size:Number(simple(last(block,'size'))??0)||0,loc:block.loc}))};
}
