import {createContainerContentItem,normalizeObjectContent} from '../domain/semantic-container.js';
import {normalizeStructureView} from '../structure-engine/structure-view.js';
import {createBoard,createBoardFrame,normalizeBoard} from '../structure-engine/board.js';
import {resolveStructureTemplate} from './validator.js';

const clone=value=>structuredClone(value),now=()=>new Date().toISOString();
const hash=value=>{let result=2166136261;for(const char of String(value)){result^=char.charCodeAt(0);result=Math.imul(result,16777619)}return(result>>>0).toString(36)};
const internalId=(kind,external)=>`lkl2:${kind}:${hash(external)}`;
const externalId=(packageId,kind,stableId)=>`${packageId}/${kind}:${stableId}`;
const blankState=state=>({knowledge:[],relations:[],representations:[],structureTemplates:[],structureInstances:[],variableSchemes:[],knowledgePackages:[],contentObjects:[],structureViews:[],boards:[],placements:[],settings:[],...clone(state)});
const mergeDefined=(existing,incoming,provided=[])=>{const next={...existing};for(const key of provided)if(key in incoming)next[key]=clone(incoming[key]);return{...next,id:existing.id,externalStableId:existing.externalStableId,packageId:existing.packageId,updatedAt:now()}};

export function buildImportPlan(model,state,{strategy='merge',strict=true,copyNamespace=null}={}){
  const next=blankState(state),errors=[],warnings=[],creates=[],updates=[],conflicts=[],originalPackageId=model.package.stableId,packageId=strategy==='copy'?(copyNamespace??`${originalPackageId}:copy-${hash(Date.now())}`):originalPackageId;
  const validation=model.validation,templateErrors=model.structureInstances.filter(item=>!resolveStructureTemplate(item.templateRef,{packageTemplates:model.structureTemplates,installedTemplates:state.structureTemplates??[]})).map(item=>({severity:'error',message:`Unknown structure template reference: ${item.templateRef}`,line:item.loc?.line??1,column:item.loc?.column??1,objectId:item.stableId,field:'using',suggestion:'Install the required LKL 1 Structure Template first, or declare it inside the LKL 2 Package.'})),preflightErrors=[...(validation?.errors??[])];for(const error of templateErrors)if(!preflightErrors.some(item=>item.objectId===error.objectId&&item.field===error.field))preflightErrors.push(error);if(templateErrors.length||strict&&validation?.errors?.length)return{strategy,packageId,creates,updates,conflicts,warnings:[...(validation?.warnings??[])],errors:preflightErrors,counts:countModel(model),previewTree:previewTree(model),nextState:clone(state),rootTarget:null,committable:false};
  const objectMap=new Map(),findExisting=(list,external)=>list.find(item=>item.externalStableId===external),upsert=(store,kind,stableId,incoming,provided=[])=>{const ext=externalId(packageId,kind,stableId),list=next[store],existing=findExisting(list,ext),record={...clone(incoming),id:existing?.id??internalId(kind,ext),externalStableId:ext,packageId,stableId,updatedAt:now(),createdAt:existing?.createdAt??now()};objectMap.set(`${kind}:${stableId}`,record.id);if(existing&&strategy==='merge'){const index=list.indexOf(existing);list[index]=mergeDefined(existing,record,provided.length?provided:Object.keys(record));updates.push({store,kind,stableId,id:existing.id});conflicts.push({kind,stableId,action:'merge'})}else{if(existing){list.splice(list.indexOf(existing),1);updates.push({store,kind,stableId,id:record.id});conflicts.push({kind,stableId,action:'replace'})}else creates.push({store,kind,stableId,id:record.id});list.push(record)}return record};
  if(strategy==='replace'){for(const key of['knowledge','relations','structureTemplates','structureInstances','variableSchemes','knowledgePackages','contentObjects','structureViews','boards','placements'])next[key]=(next[key]??[]).filter(item=>item.packageId!==packageId)}
  const packageRecord=upsert('knowledgePackages','package',packageId,{title:model.package.title,description:model.package.description,version:model.package.version,migrationVersion:model.package.migrationVersion,root:model.package.root,defaultEntry:model.package.defaultEntry,entries:clone(model.entries),sources:clone(model.sources??[]),language:model.package.language,authors:clone(model.package.authors),tags:clone(model.package.tags),suggestedTheme:model.package.suggestedTheme},[...Object.keys(model.package),'entries','sources']);
  for(const item of model.knowledge)upsert('knowledge','knowledge',item.stableId,{title:item.title,nameI18n:clone(item.nameI18n),aliases:clone(item.aliases),summary:item.summary,content:item.body,tags:clone(item.tags),sources:clone(item.sources),objectContent:normalizeObjectContent({title:item.title,summary:item.summary,body:item.body,tags:item.tags,sources:item.sources,externalKey:externalId(packageId,'knowledge',item.stableId),contentType:'note'})},item.provided);
  for(const item of model.contents)upsert('contentObjects','content',item.stableId,{type:item.type,title:item.title,summary:item.summary,body:item.body,latex:item.latex,tags:clone(item.tags),sources:clone(item.sources),objectContent:normalizeObjectContent({title:item.title,summary:item.summary,body:item.body||item.latex,displayFormula:item.latex,tags:item.tags,sources:item.sources,externalKey:externalId(packageId,'content',item.stableId),contentType:item.type})},item.provided);
  for(const item of model.variableSchemes??[])upsert('variableSchemes','variable-scheme',item.id,{title:item.title,name:item.name,description:item.description,category:item.category,builtin:item.builtin,parameters:clone(item.parameters),variables:clone(item.variables),viewDefaults:clone(item.viewDefaults),favorite:item.favorite,hidden:item.hidden,createdAt:item.createdAt,updatedAt:item.updatedAt},Object.keys(item));
  for(const item of model.structureTemplates)upsert('structureTemplates','structure-template',item.stableId,{name:item.name,description:item.description,version:1,category:'custom',builtin:false,nestable:true,computable:false,slots:clone(item.slots),edges:clone(item.edges),parameters:[],variables:[],constraints:[],rules:[],layout:clone(item.layout),visual:{accent:'#557c91'}},item.provided);
  const packageTemplates=model.structureTemplates.map(item=>next.structureTemplates.find(template=>template.id===objectMap.get(`structure-template:${item.stableId}`))).filter(Boolean),resolveTemplateId=ref=>resolveStructureTemplate(ref,{packageTemplates,installedTemplates:next.structureTemplates})?.id??null;
  for(const item of model.structureInstances){const templateId=resolveTemplateId(item.templateRef);upsert('structureInstances','structure-instance',item.stableId,{templateId,templateStableRef:item.templateRef,displayTitle:item.title||undefined,objectContent:item.title?normalizeObjectContent({title:item.title,contentType:'custom'}):undefined,ownerKnowledgeStableRef:item.ownerRef,ownerKnowledgeId:null,bindings:[],parameters:clone(item.parameters),variables:[],runtimeState:{variables:{},results:{},errors:{}},geometryPrimitives:clone(item.geometries??[]),containers:{},overrides:{addedSlots:[],removedSlotIds:[],addedEdges:[],removedEdgeIds:[],slotPatches:{},edgePatches:{}},layoutState:{visualOffsets:{},nodePositions:{},collapsedSlots:[]},objectHistory:[]},[...item.provided,'geometryPrimitives'])}
  for(const item of model.structureInstances){const record=findExisting(next.structureInstances,externalId(packageId,'structure-instance',item.stableId)),runtime=item.runtime??{};record.templateId=resolveTemplateId(item.templateRef);if(item.title){record.displayTitle=item.title;record.objectContent=normalizeObjectContent({title:item.title,contentType:'custom'})}record.ownerKnowledgeId=item.ownerRef?objectMap.get(`knowledge:${item.ownerRef}`)??findExisting(next.knowledge,externalId(packageId,'knowledge',item.ownerRef))?.id:null;record.variables=[...item.variables.map(variable=>variableRecord(variable,item.stableId,'instance')),...model.variables.filter(variable=>variable.ownerRef===item.stableId).map(variable=>variableRecord(variable,item.stableId,'global'))];record.runtimeState=clone(runtime.runtimeState??runtime);record.runtimeState.variables??={};record.runtimeState.results??={};record.runtimeState.errors??={};record.plotExpressions=clone(runtime.plotExpressions??[]);record.motionPoints=clone(runtime.motionPoints??[]);record.objectVisibility=clone(runtime.objectVisibility??{});record.designStyles=clone(runtime.designStyles??{nodeDefault:{}});record.relationStyles=clone(runtime.relationStyles??{structureDefault:{},typeOverrides:{},edgeOverrides:{}});record.containers={};record.bindings=[];for(const container of item.containers){const stored={id:container.slotId,label:container.title||'',role:'',semanticCoordinate:{},localDisplayTitle:container.localDisplayTitle||undefined,content:normalizeObjectContent({title:container.title}),children:[],visual:{}};for(const ref of container.knowledgeRefs){const targetId=objectMap.get(`knowledge:${ref}`)??findExisting(next.knowledge,externalId(packageId,'knowledge',ref))?.id;stored.children.push(referenceItem('knowledge',targetId,stored.children.length));record.bindings.push(binding(record.id,container.slotId,'knowledge',targetId))}for(const ref of container.contentRefs){const target=findExisting(next.contentObjects,externalId(packageId,'content',ref)),itemType=target?.type==='formula'?'formula':'content';stored.children.push(createContainerContentItem(itemType,{id:`lkl2-content:${hash(`${record.id}:${container.slotId}:${ref}`)}`,targetId:target?.id,content:target?.objectContent,order:stored.children.length,metadata:{externalStableId:target?.externalStableId}}))}for(const ref of container.structureRefs){const targetId=objectMap.get(`structure-instance:${ref}`)??findExisting(next.structureInstances,externalId(packageId,'structure-instance',ref))?.id;stored.children.push(referenceItem('structure',targetId,stored.children.length));record.bindings.push(binding(record.id,container.slotId,'structure',targetId))}for(const ref of container.variableRefs)stored.children.push(referenceItem('variable',ref,stored.children.length));record.containers[container.slotId]=stored}}
  for(const item of model.views){const targetId=objectMap.get(`structure-instance:${item.forRef}`)??findExisting(next.structureInstances,externalId(packageId,'structure-instance',item.forRef))?.id,view=upsert('structureViews','view',item.stableId,{instanceId:targetId,focus:item.focus?{type:item.focus.type,id:resolveTyped(item.focus)}:null,layout:item.layout,displayMode:item.displayMode,arrangement:item.arrangement,orientation:clone(item.orientation),camera:clone(item.camera),previewPolicy:item.previewPolicy,objectVisibility:clone(item.objectVisibility),manualPositions:clone(item.manualPositions),zoomPolicy:item.zoomPolicy,semanticZoom:item.semanticZoom,defaultFocus:item.defaultFocus,savedZoom:item.savedZoom},item.provided);const instance=next.structureInstances.find(value=>value.id===targetId);if(instance){instance.structureView=normalizeStructureView(view);instance.objectVisibility=clone(item.objectVisibility??instance.objectVisibility??{});instance.layoutState.nodePositions=clone(instance.structureView.manualPositions)}}
  for(const item of model.boards??[]){const ownerKnowledgeId=objectMap.get(`knowledge:${item.ownerRef}`)??findExisting(next.knowledge,externalId(packageId,'knowledge',item.ownerRef))?.id,record=upsert('boards','board',item.stableId,{...createBoard(ownerKnowledgeId,item.title),description:item.description,width:item.width,height:item.height,frames:[]},item.provided);record.ownerKnowledgeId=ownerKnowledgeId;record.frames=(item.frames??[]).map(frame=>createBoardFrame(objectMap.get(`structure-instance:${frame.instanceRef}`)??findExisting(next.structureInstances,externalId(packageId,'structure-instance',frame.instanceRef))?.id,{id:internalId('frame',externalId(packageId,'frame',frame.stableId)),...frame}));normalizeBoard(record)}
  for(const item of model.placements??[]){const targetId=resolveTyped(item.target),parentId=resolveTyped(item.parent),mode=item.mode==='reference'?'reference':'construct';upsert('placements','placement',item.stableId,{targetType:item.target?.type,targetId,parentType:item.parent?.type,parentId,mode,order:item.order,path:item.path},item.provided);materializePlacement(item,targetId,parentId,mode)}
  for(const item of model.relations){const from=resolveTyped(item.from),to=resolveTyped(item.to);upsert('relations','relation',item.stableId,{sourceId:from,targetId:to,type:item.type,label:item.label,body:item.body,objectContent:normalizeObjectContent({title:item.label,body:item.body,contentType:'custom'})},item.provided)}
  const rootTarget=resolveTyped(model.package.root),rootEntry=model.entries.find(item=>item.stableId===model.package.defaultEntry);packageRecord.rootInternalId=rootEntry?.target?resolveTyped(rootEntry.target):rootTarget;packageRecord.rootKnowledgeId=model.package.root?.type==='knowledge'?rootTarget:null;packageRecord.defaultBoardId=rootEntry?.target?.type==='board'?objectMap.get(`board:${rootEntry.target.id}`)??findExisting(next.boards,externalId(packageId,'board',rootEntry.target.id))?.id:null;
  for(const conflict of conflicts){const change=updates.find(item=>item.kind===conflict.kind&&item.stableId===conflict.stableId),store=change?.store,ext=externalId(packageId,conflict.kind,conflict.stableId),localRecord=(state[store]??[]).find(item=>item.externalStableId===ext),importedRecord=(next[store]??[]).find(item=>item.externalStableId===ext),title=record=>record?.title??record?.name??record?.label??record?.stableId??'未命名';Object.assign(conflict,{store,localTitle:title(localRecord),importTitle:title(importedRecord)})}
  return{strategy,packageId,creates,updates,conflicts,warnings:[...(validation?.warnings??[]),...warnings],errors:[...(validation?.errors??[]),...errors],counts:countModel(model),previewTree:previewTree(model),nextState:next,rootTarget:{type:rootEntry?.target?.type??model.package.root?.type,id:packageRecord.rootInternalId},committable:!errors.length&&!(strict&&validation?.errors?.length)};

  function resolveTyped(ref){if(!ref)return null;const kind=ref.type==='structure'?'structure-instance':ref.type,store=ref.type==='knowledge'?next.knowledge:ref.type==='content'?next.contentObjects:ref.type==='board'?next.boards:next.structureInstances;return objectMap.get(`${kind}:${ref.id}`)??findExisting(store,externalId(packageId,kind,ref.id))?.id??null}
  function materializePlacement(item,targetId,parentId,mode){
    if(!targetId||!parentId)return;
    if(item.parent?.type==='knowledge'&&item.target?.type==='structure'&&mode==='construct'){
      const target=next.structureInstances.find(value=>value.id===targetId);if(target)target.ownerKnowledgeId=parentId;return;
    }
    if(item.parent?.type!=='structure')return;
    const parent=next.structureInstances.find(value=>value.id===parentId),slotId=String(item.path??'').trim();
    if(!parent||!slotId){warnings.push({severity:'warning',message:`Placement "${item.stableId}" cannot be materialized without a structure container path`,objectId:item.stableId,field:'path'});return}
    const stored=parent.containers[slotId]??(parent.containers[slotId]={id:slotId,label:slotId,role:'',semanticCoordinate:{},localDisplayTitle:undefined,content:normalizeObjectContent({title:slotId}),children:[],visual:{}}),order=Number(item.order??stored.children.length),targetType=item.target?.type;
    if(targetType==='knowledge'||targetType==='structure'){
      let child=stored.children.find(value=>value.type===targetType&&value.targetId===targetId);if(!child){child=referenceItem(targetType,targetId,order);stored.children.push(child)}child.order=order;child.metadata={...(child.metadata??{}),placementMode:mode,placementStableId:item.stableId};
      let linked=parent.bindings.find(value=>value.slotId===slotId&&value.targetType===targetType&&value.targetId===targetId);if(!linked){linked=binding(parent.id,slotId,targetType,targetId);parent.bindings.push(linked)}linked.metadata={...(linked.metadata??{}),placementMode:mode,order,placementStableId:item.stableId};return;
    }
    if(targetType==='content'){
      const target=next.contentObjects.find(value=>value.id===targetId);if(!target||stored.children.some(value=>value.type!=='knowledge'&&value.type!=='structure'&&value.targetId===targetId))return;const contentType=target.type==='formula'?'formula':'content';stored.children.push(createContainerContentItem(contentType,{id:`lkl2-content:${hash(`${parent.id}:${slotId}:${item.stableId}`)}`,targetId,content:target.objectContent,order,metadata:{externalStableId:target.externalStableId,placementMode:mode,placementStableId:item.stableId}}))
    }
  }
  function variableRecord(item,ownerRef,declarationScope){return{id:item.stableId,label:item.label,displayName:item.displayName,nameI18n:clone(item.nameI18n),group:item.group,order:item.order,kind:item.kind,type:item.type,value:item.value,formula:item.expression,displayFormula:item.displayFormula,showOnCanvas:item.showOnCanvas,externalStableId:externalId(packageId,'variable',item.stableId),ownerStableRef:ownerRef,declarationScope}}
}

const binding=(instanceId,slotId,targetType,targetId)=>({id:`lkl2-binding:${hash(`${instanceId}:${slotId}:${targetType}:${targetId}`)}`,instanceId,slotId,targetType,targetId,metadata:{imported:true},createdAt:now(),updatedAt:now()});
const referenceItem=(type,targetId,order)=>createContainerContentItem(type,{id:`lkl2-ref:${hash(`${type}:${targetId}:${order}`)}`,targetId,order,metadata:{compatibilitySource:'binding'}});
export function countModel(model){return{knowledge:model.knowledge.length,content:model.contents.length,structures:model.structureInstances.length,templates:model.structureTemplates.length,containers:model.structureInstances.reduce((sum,item)=>sum+item.containers.length,0),relations:model.relations.length,variables:model.variables.length+model.structureInstances.reduce((sum,item)=>sum+item.variables.length,0),views:model.views.length,boards:(model.boards??[]).length,frames:(model.boards??[]).reduce((sum,item)=>sum+item.frames.length,0),placements:(model.placements??[]).length,entries:model.entries.length}}
export function previewTree(model){return{label:model.package.title||model.package.stableId,kind:'package',children:[{label:'知识',kind:'group',children:model.knowledge.map(item=>({label:item.title,stableId:item.stableId,kind:'knowledge'}))},{label:'结构',kind:'group',children:model.structureInstances.map(item=>({label:item.title||item.stableId,stableId:item.stableId,kind:'structure',children:item.containers.map(container=>({label:container.slotId,kind:'container'}))}))},{label:'组合页面',kind:'group',children:(model.boards??[]).map(item=>({label:item.title,stableId:item.stableId,kind:'board',children:item.frames.map(frame=>({label:frame.instanceRef,kind:'frame'}))}))}]}}
export async function commitImportPlan(plan,{persist=null}={}){if(!plan?.committable||plan.errors?.length)throw new Error(plan?.errors?.[0]?.message??'Import plan is not committable');const committed=clone(plan.nextState);if(persist)await persist(committed);return committed}
