const quote=value=>`"${String(value??'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,'\\n')}"`;
const multiline=value=>`"""${String(value??'')}"""`;
const ident=value=>String(value??'').trim();
const array=values=>`[${(values??[]).map(quote).join(', ')}]`;
const lines=[];
const field=(name,value,indent='  ',format=null)=>{if(value===undefined||value===null||value===''||Array.isArray(value)&&!value.length)return;if(format||String(value).includes('\n'))lines.push(`${indent}${name}${format?` ${format}`:''} ${multiline(value)}`);else if(Array.isArray(value))lines.push(`${indent}${name} ${array(value)}`);else if(typeof value==='number'||typeof value==='boolean')lines.push(`${indent}${name} ${value}`);else lines.push(`${indent}${name} ${quote(value)}`)};
const block=(kind,id,writer,indent='')=>{lines.push(`${indent}${kind}${id?` ${ident(id)}`:''} {`);writer(`${indent}  `);lines.push(`${indent}}`,'')};
const typedRef=(name,ref,indent)=>{if(ref)lines.push(`${indent}${name} ${ref.type??'knowledge'} ${ident(ref.id)}`)};

export function serializeKnowledgePackage(model){
  lines.length=0;lines.push('lkl 2','');block('package',model.package.stableId,indent=>{field('id',model.package.stableId,indent);field('title',model.package.title,indent);field('description',model.package.description,indent);field('version',model.package.version,indent);field('migrationVersion',model.package.migrationVersion,indent);field('createdAt',model.package.createdAt,indent);field('updatedAt',model.package.updatedAt,indent);field('language',model.package.language,indent);field('authors',model.package.authors,indent);field('tags',model.package.tags,indent);field('suggestedTheme',model.package.suggestedTheme,indent);typedRef('root',model.package.root,indent);field('defaultEntry',model.package.defaultEntry,indent)});
  for(const item of model.knowledge??[])block('knowledge',item.stableId,indent=>{field('id',item.id&&item.id!==item.stableId?item.id:null,indent);field('title',item.title,indent);field('name-zh-CN',item.nameI18n?.['zh-CN'],indent);field('name-en',item.nameI18n?.en,indent);field('aliases',item.aliases,indent);field('summary',item.summary,indent);field('body',item.body,indent,item.bodyFormat??'markdown');field('tags',item.tags,indent);for(const source of item.sources??[])field('source',typeof source==='string'?source:JSON.stringify(source),indent)});
  for(const item of model.contents??[])block('content',item.stableId,indent=>{field('type',item.type,indent);field('title',item.title,indent);field('summary',item.summary,indent);if(item.body)field('body',item.body,indent,item.bodyFormat??'markdown');if(item.latex)field('latex',item.latex,indent,'latex');field('tags',item.tags,indent);for(const source of item.sources??[])field('source',typeof source==='string'?source:JSON.stringify(source),indent)});
  for(const item of model.structureTemplates??[])block('structure-template',item.stableId,indent=>{field('title',item.name,indent);field('description',item.description,indent);field('layout',item.layout?.type,indent);for(const slot of item.slots??[])block('slot',slot.id,inner=>{field('title',slot.label,inner);field('role',slot.role,inner);field('order',slot.semanticCoordinate?.order,inner)},indent);for(const edge of item.edges??[])block('edge',edge.id,inner=>{field('from',edge.sourceSlotId,inner);field('to',edge.targetSlotId,inner);field('direction',edge.direction,inner);field('type',edge.relationType,inner)},indent)});
  for(const item of model.structureInstances??[])block('structure-instance',item.stableId,indent=>{lines.push(`${indent}using ${ident(item.templateRef)}`);if(item.ownerRef)lines.push(`${indent}owner ${ident(item.ownerRef)}`);field('title',item.title,indent);field('runtime',Object.keys(item.runtime??{}).length?JSON.stringify(item.runtime):'',indent);for(const[key,value]of Object.entries(item.parameters??{}))lines.push(`${indent}parameter ${ident(key)} = ${typeof value==='string'?quote(value):value}`);for(const variable of item.variables??[])writeVariable(variable,indent);for(const container of item.containers??[])block('container',container.slotId,inner=>{field('title',container.title,inner);field('local-title',container.localDisplayTitle,inner);for(const ref of container.knowledgeRefs??[])lines.push(`${inner}knowledge ${ident(ref)}`);for(const ref of container.contentRefs??[])lines.push(`${inner}content ${ident(ref)}`);for(const ref of container.structureRefs??[])lines.push(`${inner}structure ${ident(ref)}`);for(const ref of container.variableRefs??[])lines.push(`${inner}variable ${ident(ref)}`)},indent)});
  for(const item of model.variables??[])writeVariable(item,'');
  for(const item of model.variableSchemes??[])block('variable-scheme',item.id,indent=>{field('title',item.title??item.name,indent);field('description',item.description,indent);field('category',item.category,indent);field('builtin',!!item.builtin,indent);field('favorite',!!item.favorite,indent);field('hidden',!!item.hidden,indent);field('createdAt',item.createdAt,indent);field('updatedAt',item.updatedAt,indent);for(const[key,value]of Object.entries(item.parameters??{}))lines.push(`${indent}parameter ${ident(key)} = ${typeof value==='string'?quote(value):value}`);field('view-defaults',JSON.stringify(item.viewDefaults??{}),indent);for(const variable of item.variables??[])writeVariable({...variable,stableId:variable.id,expression:variable.formula},indent)});
  for(const item of model.relations??[])block('relation',item.stableId,indent=>{typedRef('from',item.from,indent);typedRef('to',item.to,indent);field('type',item.type,indent);field('label',item.label,indent);field('body',item.body,indent,item.bodyFormat??'markdown')});
  for(const item of model.views??[])block('view',item.stableId,indent=>{if(item.forRef)lines.push(`${indent}for ${ident(item.forRef)}`);field('layout',item.layout,indent);field('mode',item.displayMode,indent);block('orientation',null,inner=>{field('zero',item.orientation?.zeroAnchor,inner);field('direction',item.orientation?.direction,inner);field('rotation',`${Number(item.orientation?.rotationAngle??0)}deg`,inner)},indent);block('camera',null,inner=>{field('projection',item.camera?.projection,inner);field('yaw',item.camera?.yaw,inner);field('pitch',item.camera?.pitch,inner)},indent);field('preview-policy',item.previewPolicy,indent);field('object-visibility',JSON.stringify(item.objectVisibility??{}),indent);field('zoom-policy',item.zoomPolicy,indent);field('semantic-zoom',item.semanticZoom,indent);field('zoom',item.savedZoom,indent);field('default-focus',item.defaultFocus,indent);for(const[id,point]of Object.entries(item.manualPositions??{}))block('position',id,inner=>{field('x',point.x,inner);field('y',point.y,inner)},indent)});
  for(const item of model.boards??[])block('board',item.stableId,indent=>{field('title',item.title,indent);field('description',item.description,indent);field('owner',item.ownerRef,indent);field('width',item.width,indent);field('height',item.height,indent);for(const frame of item.frames??[])block('frame',frame.stableId??frame.id,inner=>{field('instance',frame.instanceRef,inner);field('x',frame.x,inner);field('y',frame.y,inner);field('width',frame.width,inner);field('height',frame.height,inner);field('z-index',frame.zIndex,inner);field('order',frame.order,inner);field('preview-policy',frame.previewPolicy,inner)},indent)});
  for(const item of model.placements??[])block('placement',item.stableId,indent=>{typedRef('target',item.target,indent);typedRef('parent',item.parent,indent);field('mode',item.mode,indent);field('order',item.order,indent);field('path',item.path,indent)});
  for(const item of model.entries??[])block('entry',item.stableId,indent=>{field('title',item.title,indent);if(item.target)lines.push(`${indent}${item.target.type} ${ident(item.target.id)}`)});
  for(const item of model.sources??[])block('source',item.stableId,indent=>{field('title',item.title,indent);field('url',item.url,indent);field('body',item.body,indent,'markdown');field('attachment',item.attachment,indent);field('media-type',item.mediaType,indent);field('size',item.size,indent)});
  return lines.join('\n').trimEnd()+'\n';
}

function writeVariable(item,indent){block('variable',item.stableId,inner=>{if(item.ownerRef)lines.push(`${inner}for ${ident(item.ownerRef)}`);field('label',item.label,inner);field('display-name',item.displayName,inner);field('name-zh-CN',item.nameI18n?.['zh-CN'],inner);field('name-en',item.nameI18n?.en,inner);field('group',item.group,inner);field('order',item.order,inner);field('kind',item.kind,inner);field('type',item.type,inner);field('value',item.value,inner);field('expression',item.expression,inner);field('display-formula',item.displayFormula,inner);field('show',item.showOnCanvas,inner)},indent)}

const strip=value=>{if(Array.isArray(value))return value.map(strip);if(value&&typeof value==='object'){const result={};for(const key of Object.keys(value).sort())if(!['loc','provided','createdAt','updatedAt','runtimeState','id','validation','diagnostics','errors','warnings'].includes(key)&&value[key]!==undefined)result[key]=strip(value[key]);return result}return value};
export function semanticEquivalent(left,right){return JSON.stringify(strip(left))===JSON.stringify(strip(right))}
