import {parseLkl2} from './parser.js';
import {parseFormula} from '../structure-engine/formula.js';
import {materializeInstanceDefinition,normalizeInstance} from '../structure-engine/model.js';

const clone=value=>structuredClone(value);
const quote=value=>`"${String(value??'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,'\\n')}"`;
const json=value=>`"""${JSON.stringify(value??{},null,2)}"""`;
const field=(name,value,indent='  ')=>`${indent}${name} ${typeof value==='number'||typeof value==='boolean'?value:quote(value)}`;

export function serializeStructureInstance(template,instance){
  normalizeInstance(instance);const definition=materializeInstanceDefinition(template,instance),lines=['lkl 2','',`structure-instance ${instance.id} {`,field('using',template.id),field('title',instance.objectContent?.title??template.name)];
  if(instance.resultSpace)lines.push(`  result-space ${json(instance.resultSpace)}`);
  for(const[key,value]of Object.entries(instance.parameters??{}))lines.push(`  parameter ${key} = ${typeof value==='number'||typeof value==='boolean'?value:quote(value)}`);
  for(const slot of definition.slots){const container=instance.containers?.[slot.id];lines.push(`  container ${slot.id} {`);if(container?.localDisplayTitle)lines.push(field('local-title',container.localDisplayTitle,'    '));if(container?.content?.title&&container.content.title!==slot.label)lines.push(field('title',container.content.title,'    '));lines.push('  }')}
  for(const variable of instance.variables??[]){lines.push(`  variable ${variable.id} {`,field('label',variable.label??variable.id,'    '),field('display-name',variable.displayName??variable.label??variable.id,'    '),field('kind',variable.kind??'input','    '),field('type',variable.type??'number','    '));if(variable.value!=null)lines.push(field('value',variable.value,'    '));if(variable.formula)lines.push(field('expression',variable.formula,'    '));if(variable.displayFormula)lines.push(field('display-formula',variable.displayFormula,'    '));lines.push(field('show',variable.showOnCanvas!==false,'    '));if(variable.resultSpace)lines.push(`    result-space ${json(variable.resultSpace)}`);lines.push('  }')}
  for(const geometry of instance.geometryPrimitives??[]){lines.push(`  geometry ${geometry.id} {`,field('type',geometry.kind,'    '));for(const ref of geometry.pointRefs??[])lines.push(`    point ${ref.type} ${ref.id}`);lines.push(field('visible',geometry.visible!==false,'    '));if(geometry.style?.color)lines.push(field('stroke',geometry.style.color,'    '));if(geometry.style?.width!=null)lines.push(field('width',geometry.style.width,'    '));if(geometry.style?.fill)lines.push(field('fill',geometry.style.fill,'    '));lines.push('  }')}
  const addedIds=new Set(instance.overrides?.addedEdges?.map(item=>item.id));for(const edge of definition.edges){lines.push(`  relation ${edge.id} {`,field('from',edge.sourceSlotId,'    '),field('to',edge.targetSlotId,'    '),field('direction',edge.direction??'directed','    '),field('type',edge.relationType??'related','    '));if(edge.displayLabel??edge.label)lines.push(field('label',edge.displayLabel??edge.label,'    '));if(edge.routing)lines.push(field('routing',edge.routing,'    '));if(edge.visual&&Object.keys(edge.visual).length)lines.push(`    style ${json(edge.visual)}`);lines.push(field('canonical',!addedIds.has(edge.id),'    '),'  }')}
  lines.push(`  layout-state ${json(instance.layoutState)}`,`  view-state ${json(instance.structureView)}`,`  design-styles ${json(instance.designStyles)}`,`  relation-styles ${json(instance.relationStyles)}`,`  object-visibility ${json(instance.objectVisibility)}`,`  plot-expressions ${json(instance.plotExpressions)}`,`  motion-points ${json(instance.motionPoints)}`,`  topology-overrides ${json(instance.overrides)}`,'}','');return lines.join('\n')
}

export function serializeStructureTemplateDefaults(template){
  const lines=['lkl 2','',`structure-template ${template.id} {`,field('title',template.name),field('description',template.description)];
  for(const parameter of template.parameters??[])lines.push(`  parameter ${parameter.id} = ${typeof parameter.defaultValue==='number'||typeof parameter.defaultValue==='boolean'?parameter.defaultValue:quote(parameter.defaultValue)}`);
  lines.push(`  visual-defaults ${json(template.visual??{})}`,`  view-capability ${json(template.viewCapability??{})}`,'}','');return lines.join('\n');
}

export function parseStructureTemplateDefaultsSource(source,{template}={}){
  try{
    const ast=parseLkl2(source),block=ast.declarations.find(item=>item.kind==='structure-template');if(!block)throw diagnosticError('Default source requires one structure-template block',{line:1,column:1},'structure-template');
    if(String(block.id)!==String(template.id))throw diagnosticError('Changing the built-in template identity is not supported',block.loc,'structure-template');
    const draft=clone(template),statements=groupStatements(block.statements),title=first(statements,'title'),description=first(statements,'description');if(title!==undefined)draft.name=String(title);if(description!==undefined)draft.description=String(description);
    const defaults=new Map((draft.parameters??[]).map(item=>[item.id,item]));for(const statement of statements.get('parameter')??[]){const[key,value]=statement.values;if(!defaults.has(String(key)))throw diagnosticError(`Unknown default parameter ${key}`,statement.loc,'parameter');defaults.get(String(key)).defaultValue=value}
    const visual=parseJsonField(statements,'visual-defaults',draft.visual??{}),capability=parseJsonField(statements,'view-capability',draft.viewCapability??{});if(visual!==undefined)draft.visual=visual;if(capability!==undefined)draft.viewCapability=capability;
    return{valid:true,draft,diagnostics:[],ast};
  }catch(error){return{valid:false,draft:null,diagnostics:[{severity:'error',message:error.message,line:Number(error.line??1),column:Number(error.column??1),field:error.field??null}],error}}
}

export function parseStructureInstanceSource(source,{template,instance}={}){
  try{
    const ast=parseLkl2(source),block=ast.declarations.find(item=>item.kind==='structure-instance');if(!block)throw diagnosticError('Structure source requires one structure-instance block',{line:1,column:1},'structure-instance');
    const draft=clone(instance);normalizeInstance(draft);const statements=groupStatements(block.statements),using=first(statements,'using');if(using&&String(using)!==String(template.id))throw diagnosticError('Changing the template reference is not supported in this workbench',statementLoc(statements,'using'),'template');
    const resultSpace=parseJsonField(statements,'result-space',draft.resultSpace??null);if(resultSpace!==undefined)draft.resultSpace=resultSpace;
    for(const statement of statements.get('parameter')??[]){const[key,value]=statement.values;if(key==null||value===undefined)throw diagnosticError('parameter requires a name and value',statement.loc,'parameter');draft.parameters[String(key)]=value}
    for(const child of block.children.filter(item=>item.kind==='container')){draft.containers[child.id]??={id:child.id,children:[]};const fields=groupStatements(child.statements),localTitle=first(fields,'local-title'),title=first(fields,'title');if(localTitle!==undefined){if(String(localTitle).trim())draft.containers[child.id].localDisplayTitle=String(localTitle).trim();else delete draft.containers[child.id].localDisplayTitle}if(title!==undefined){draft.containers[child.id].content??={};draft.containers[child.id].content.title=String(title)}}
    draft.variables=block.children.filter(item=>item.kind==='variable').map(child=>parseVariable(child,draft.resultSpace));
    const sourceMotions=parseJsonField(statements,'motion-points',draft.motionPoints);if(sourceMotions!==undefined)draft.motionPoints=sourceMotions;const slotIds=new Set(materializeInstanceDefinition(template,draft).slots.map(item=>item.id)),motionIds=new Set((draft.motionPoints??[]).map(item=>item.id));draft.geometryPrimitives=block.children.filter(item=>item.kind==='geometry').map(child=>parseGeometry(child,{slotIds,motionIds}));
    const definition=materializeInstanceDefinition(template,draft),definitionEdges=new Map(definition.edges.map(edge=>[edge.id,edge])),addedIds=new Set(draft.overrides.addedEdges.map(edge=>edge.id));for(const child of block.children.filter(item=>item.kind==='relation')){const fields=groupStatements(child.statements),edge=definitionEdges.get(child.id);if(!edge)throw diagnosticError(`Unknown relation ${child.id}`,child.loc,'relation');const patch={sourceSlotId:String(first(fields,'from')??edge.sourceSlotId),targetSlotId:String(first(fields,'to')??edge.targetSlotId),direction:String(first(fields,'direction')??edge.direction),relationType:String(first(fields,'type')??edge.relationType),displayLabel:String(first(fields,'label')??edge.displayLabel??edge.label??''),routing:String(first(fields,'routing')??edge.routing??'straight')},style=parseJsonField(fields,'style',edge.visual??{});if(style!==undefined)patch.visual=style;const canonical=template.builtin&&!addedIds.has(child.id);if(canonical&&(patch.sourceSlotId!==edge.sourceSlotId||patch.targetSlotId!==edge.targetSlotId||patch.direction!==edge.direction||patch.relationType!==edge.relationType))throw diagnosticError(`Canonical relation ${child.id} topology is protected; use relation-styles arrow to control its displayed arrow direction`,child.loc,'relation');draft.overrides.edgePatches[child.id]={...(draft.overrides.edgePatches[child.id]??{}),...patch}}
    const layout=parseJsonField(statements,'layout-state',draft.layoutState),view=parseJsonField(statements,'view-state',draft.structureView),design=parseJsonField(statements,'design-styles',draft.designStyles),styles=parseJsonField(statements,'relation-styles',draft.relationStyles),visibility=parseJsonField(statements,'object-visibility',draft.objectVisibility),plots=parseJsonField(statements,'plot-expressions',draft.plotExpressions),motions=parseJsonField(statements,'motion-points',draft.motionPoints),overrides=parseJsonField(statements,'topology-overrides',draft.overrides);if(layout!==undefined)draft.layoutState=layout;if(view!==undefined)draft.structureView=view;if(design!==undefined)draft.designStyles=design;if(styles!==undefined)draft.relationStyles=styles;if(visibility!==undefined)draft.objectVisibility=visibility;if(plots!==undefined)draft.plotExpressions=plots;if(motions!==undefined)draft.motionPoints=motions;if(overrides!==undefined){if(template.builtin&&((overrides.addedSlots?.length??0)||(overrides.removedSlotIds?.length??0)||(overrides.removedEdgeIds?.length??0)))throw diagnosticError('Built-in canonical topology is protected; duplicate it as a custom template first',statementLoc(statements,'topology-overrides'),'topology-overrides');draft.overrides={...draft.overrides,...overrides}}
    normalizeInstance(draft);return{valid:true,draft,diagnostics:[],ast};
  }catch(error){return{valid:false,draft:null,diagnostics:[{severity:'error',message:error.message,line:Number(error.line??1),column:Number(error.column??1),field:error.field??null}],error}}
}

export function applyStructureInstanceDraft(instance,draft){for(const key of['parameters','variables','resultSpace','containers','overrides','layoutState','structureView','designStyles','relationStyles','objectVisibility','plotExpressions','motionPoints','geometryPrimitives','objectContent'])if(key in draft)instance[key]=clone(draft[key]);instance.updatedAt=new Date().toISOString();normalizeInstance(instance);return instance}
export function formatStructureInstanceSource(source,context){const parsed=parseStructureInstanceSource(source,context);return parsed.valid?{...parsed,source:serializeStructureInstance(context.template,parsed.draft)}:parsed}

function parseVariable(child,defaultResultSpace){const fields=groupStatements(child.statements),formula=String(first(fields,'expression')??''),variable={id:child.id,label:String(first(fields,'label')??child.id),displayName:String(first(fields,'display-name')??first(fields,'label')??child.id),kind:String(first(fields,'kind')??(formula?'derived':'input')),type:String(first(fields,'type')??'number'),value:first(fields,'value'),formula,expression:formula?parseFormula(formula):null,displayFormula:String(first(fields,'display-formula')??''),showOnCanvas:first(fields,'show')!==false,resultSpace:parseJsonField(fields,'result-space',defaultResultSpace)??clone(defaultResultSpace)};return variable}
function parseGeometry(child,{slotIds=new Set(),motionIds=new Set()}={}){const fields=groupStatements(child.statements),kind=String(first(fields,'type')??'line'),minimum={line:2,area:3,volume:4}[kind];if(!minimum)throw diagnosticError(`Unsupported geometry type ${kind}`,child.loc,'geometry.type');const pointRefs=(fields.get('point')??[]).map(statement=>({type:String(statement.values[0]??''),id:String(statement.values[1]??'')}));if(pointRefs.length<minimum)throw diagnosticError(`${kind} requires at least ${minimum} point references`,child.loc,'geometry.point');for(const ref of pointRefs){if(!['slot','motion'].includes(ref.type))throw diagnosticError(`Unsupported geometry point reference ${ref.type}`,child.loc,'geometry.point');if(ref.type==='slot'&&!slotIds.has(ref.id))throw diagnosticError(`Unknown geometry slot ${ref.id}`,child.loc,'geometry.point');if(ref.type==='motion'&&!motionIds.has(ref.id))throw diagnosticError(`Unknown geometry motion ${ref.id}`,child.loc,'geometry.point')}return{id:child.id,kind,pointRefs,visible:first(fields,'visible')!==false,style:{color:String(first(fields,'stroke')??'#355f78'),width:Number(first(fields,'width')??2),fill:String(first(fields,'fill')??'rgba(53,95,120,.14)')}}}
function groupStatements(items=[]){const map=new Map();for(const item of items){if(!map.has(item.key))map.set(item.key,[]);map.get(item.key).push(item)}return map}
function first(group,key){return group.get(key)?.at(-1)?.values?.at(-1)}
function statementLoc(group,key){return group.get(key)?.at(-1)?.loc??{line:1,column:1}}
function parseJsonField(group,key,fallback){const statement=group.get(key)?.at(-1);if(!statement)return fallback;try{return JSON.parse(String(statement.values.at(-1)??'null'))}catch(error){throw diagnosticError(`${key}: ${error.message}`,statement.loc,key)}}
function diagnosticError(message,loc={line:1,column:1},field=null){if(typeof loc==='number')loc={line:loc,column:1};return Object.assign(new Error(message),{line:loc?.line??1,column:loc?.column??1,field})}
