import {getBuiltinTemplate,materializeTemplate} from '../structure-engine/templates.js';
import {formulaDependencies,parseFormula} from '../structure-engine/formula.js';
import {analyzePoset} from '../structure-engine/poset.js';
import {LKL_LIMITS} from './schema.js';

const diagnostic=(severity,message,object={},field=null,suggestion=null)=>({severity,message,line:object.loc?.line??1,column:object.loc?.column??1,objectId:object.stableId??null,field,path:field&&object.stableId?`${object.stableId}.${field}`:field,suggestion});
const nearest=(value,candidates)=>{let best=null,score=Infinity;for(const candidate of candidates){const distance=levenshtein(String(value),String(candidate));if(distance<score){score=distance;best=candidate}}return score<=Math.max(2,Math.floor(String(value).length/3))?best:null};
const levenshtein=(a,b)=>{const rows=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)rows[i][0]=i;for(let j=0;j<=b.length;j++)rows[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)rows[i][j]=Math.min(rows[i-1][j]+1,rows[i][j-1]+1,rows[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return rows[a.length][b.length]};
const refSet=(type,sets)=>type==='knowledge'?sets.knowledge:type==='structure'?sets.structure:type==='content'?sets.content:type==='board'?sets.board:new Set();

export function validateKnowledgePackage(model,{strict=true,templates=[]}={}){
  const diagnostics=[],groups={knowledge:model.knowledge??[],content:model.contents??[],'structure-template':model.structureTemplates??[],'structure-instance':model.structureInstances??[],relation:model.relations??[],variable:model.variables??[],view:model.views??[],board:model.boards??[],placement:model.placements??[],entry:model.entries??[],source:model.sources??[]};
  const declarationCount=Object.values(groups).reduce((sum,items)=>sum+items.length,1);
  if(declarationCount>LKL_LIMITS.maxDeclarations)diagnostics.push(diagnostic('error',`知识包包含 ${declarationCount} 个声明，超过上限 ${LKL_LIMITS.maxDeclarations}`,model.package,'package','拆分知识包后再导入'));
  for(const[kind,objects]of Object.entries(groups)){const seen=new Set();for(const object of objects){if(!object.stableId)diagnostics.push(diagnostic('error',`${kind} requires a stable id`,object,'id','为对象提供包内唯一且稳定的 id'));else if(seen.has(object.stableId))diagnostics.push(diagnostic('error',`Duplicate ${kind} id "${object.stableId}"`,object,'id','重命名重复 id'));seen.add(object.stableId)}}
  if(!model.package?.stableId)diagnostics.push(diagnostic('error','Package requires a stable id',model.package,'id'));
  const sets={knowledge:new Set(groups.knowledge.map(item=>item.stableId)),content:new Set(groups.content.map(item=>item.stableId)),structure:new Set(groups['structure-instance'].map(item=>item.stableId)),board:new Set(groups.board.map(item=>item.stableId))},templateIds=new Set([...templates.map(item=>item.id),...groups['structure-template'].map(item=>item.stableId)]),variableIds=new Set(groups.variable.map(item=>item.stableId));
  const requireRef=(ref,set,object,field,kind)=>{if(!ref)return;if(!set.has(ref)){const suggestion=nearest(ref,[...set]);diagnostics.push(diagnostic('error',`Unknown ${kind} reference "${ref}"`,object,field,suggestion?`是否想引用 ${suggestion}？`:'检查引用类型和稳定 ID'))}};
  const requireTyped=(ref,object,field)=>{if(!ref)return;const set=refSet(ref.type,sets);if(!set.size&&!['knowledge','structure','content','board'].includes(ref.type))diagnostics.push(diagnostic('error',`Unsupported reference type "${ref.type}"`,object,field,'使用 knowledge、structure、content 或 board'));else requireRef(ref.id,set,object,field,ref.type)};
  requireTyped(model.package?.root,model.package,'root');
  for(const entry of groups.entry)requireTyped(entry.target,entry,'target');
  if(groups.board.length>LKL_LIMITS.maxBoards)diagnostics.push(diagnostic('error',`组合页面数量超过 ${LKL_LIMITS.maxBoards}`,model.package,'boards'));

  for(const instance of groups['structure-instance']){
    if(!instance.templateRef)diagnostics.push(diagnostic('error','Structure instance requires using <template>',instance,'using'));else if(!String(instance.templateRef).startsWith('builtin:'))requireRef(instance.templateRef,templateIds,instance,'using','structure-template');else if(!getBuiltinTemplate(instance.templateRef))diagnostics.push(diagnostic('error',`Unknown built-in template "${instance.templateRef}"`,instance,'using'));
    if(instance.ownerRef)requireRef(instance.ownerRef,sets.knowledge,instance,'owner','knowledge');
    const template=getBuiltinTemplate(instance.templateRef)??templates.find(item=>item.id===instance.templateRef)??groups['structure-template'].find(item=>item.stableId===instance.templateRef);let resolved=null;
    try{resolved=template?materializeTemplate(template,instance.parameters):null}catch(error){diagnostics.push(diagnostic('error',`Invalid structure parameters: ${error.message}`,instance,'parameter'))}
    const nodeCount=Math.max(instance.containers?.length??0,resolved?.slots?.length??0);
    if(nodeCount>LKL_LIMITS.maxNodesPerStructure)diagnostics.push(diagnostic('error',`结构节点数 ${nodeCount} 超过上限 ${LKL_LIMITS.maxNodesPerStructure}`,instance,'container','降低结构规模或拆分为嵌套结构'));
    const slotMap=new Map(resolved?.slots?.map(item=>[item.id,item])??[]);
    for(const container of instance.containers??[]){const slot=slotMap.get(container.slotId);if(resolved&&!slot)diagnostics.push(diagnostic('error',`Container "${container.slotId}" does not exist in ${instance.templateRef}`,container,'container'));for(const ref of container.knowledgeRefs)requireRef(ref,sets.knowledge,container,'knowledge','knowledge');for(const ref of container.contentRefs)requireRef(ref,sets.content,container,'content','content');for(const ref of container.structureRefs)requireRef(ref,sets.structure,container,'structure','structure-instance');for(const ref of container.variableRefs){requireRef(ref,new Set([...variableIds,...(instance.variables??[]).map(item=>item.stableId)]),container,'variable','variable');if(slot&&!slot.accepts?.includes('variable'))diagnostics.push(diagnostic('error',`Container "${container.slotId}" does not accept variables`,container,'variable'))}}
    if(instance.templateRef==='builtin:lmn-432'){const canonical=new Set(['L1','L2','L3','L4','M1','M2','M3','N1','N2']);for(const container of instance.containers??[])if(!canonical.has(container.slotId))diagnostics.push(diagnostic('error',`LMN canonical position "${container.slotId}" is invalid`,container,'container'))}
    const modulus=Number(instance.parameters?.modulus);if(instance.templateRef==='builtin:mod-n'&&(modulus<2||modulus>64||!Number.isInteger(modulus)))diagnostics.push(diagnostic('error','modulus must be an integer from 2 to 64',instance,'parameter.modulus'));
    validateVariables([...groups.variable.filter(item=>item.ownerRef===instance.stableId),...(instance.variables??[])],instance,instance.parameters,diagnostics);
  }
  for(const relation of groups.relation){if(relation.from)requireTyped(relation.from,relation,'from');else diagnostics.push(diagnostic('error','Relation requires a from reference',relation,'from'));if(relation.to)requireTyped(relation.to,relation,'to');else diagnostics.push(diagnostic('error','Relation requires a to reference',relation,'to'))}
  for(const view of groups.view){if(view.forRef)requireRef(view.forRef,sets.structure,view,'for','structure-instance');if(!['off','compact','detailed'].includes(view.previewPolicy))diagnostics.push(diagnostic('error',`Unknown preview policy "${view.previewPolicy}"`,view,'preview-policy','使用 off、compact 或 detailed'))}
  for(const board of groups.board){requireRef(board.ownerRef,sets.knowledge,board,'owner','knowledge');if((board.frames??[]).length>LKL_LIMITS.maxFramesPerBoard)diagnostics.push(diagnostic('error',`组合页面 frame 数超过 ${LKL_LIMITS.maxFramesPerBoard}`,board,'frame'));const frameIds=new Set();for(const frame of board.frames??[]){if(frameIds.has(frame.stableId))diagnostics.push(diagnostic('error',`Duplicate frame id "${frame.stableId}"`,frame,'id'));frameIds.add(frame.stableId);requireRef(frame.instanceRef,sets.structure,frame,'instance','structure-instance');if(frame.width<120||frame.height<100)diagnostics.push(diagnostic('warning','frame 尺寸过小，内容可能不可读',frame,'width','增大 frame 尺寸'))}}
  for(const placement of groups.placement){requireTyped(placement.target,placement,'target');requireTyped(placement.parent,placement,'parent');if(!['construct','reference'].includes(placement.mode))diagnostics.push(diagnostic('error',`Unknown placement mode "${placement.mode}"`,placement,'mode','使用 construct 或 reference'))}
  validateNesting(groups['structure-instance'],groups.placement,diagnostics);
  for(const template of groups['structure-template'])if(template.layout?.type==='hasse'){const analysis=analyzePoset(template.slots,template.edges);if(!analysis.valid)for(const message of analysis.errors)diagnostics.push(diagnostic('error',`Invalid Poset: ${message}`,template,'edge'))}
  for(const source of groups.source){if(/^\s*javascript:/i.test(source.url??''))diagnostics.push(diagnostic('error','来源 URL 不允许 javascript: 协议',source,'url','使用 https: 或相对附件引用'));if(Number(source.size??0)>LKL_LIMITS.maxAttachmentBytes)diagnostics.push(diagnostic('error',`附件超过 ${LKL_LIMITS.maxAttachmentBytes} 字节限制`,source,'size'))}
  const errors=diagnostics.filter(item=>item.severity==='error'),warnings=diagnostics.filter(item=>item.severity==='warning');return{valid:strict?!errors.length:true,errors,warnings,diagnostics,limits:LKL_LIMITS};
}

function validateNesting(instances,placements,diagnostics){const graph=new Map(instances.map(item=>[item.stableId,[]]));for(const instance of instances)for(const container of instance.containers??[])for(const child of container.structureRefs??[])graph.get(instance.stableId)?.push(child);for(const placement of placements)if(placement.mode==='construct'&&placement.parent?.type==='structure'&&placement.target?.type==='structure')graph.get(placement.parent.id)?.push(placement.target.id);const visiting=new Set(),memo=new Map();function depth(id){if(memo.has(id))return memo.get(id);if(visiting.has(id))return 0;visiting.add(id);let value=1;for(const child of graph.get(id)??[])value=Math.max(value,1+depth(child));visiting.delete(id);memo.set(id,value);return value}for(const id of graph.keys()){const value=depth(id);if(value>LKL_LIMITS.maxNestingDepth)diagnostics.push(diagnostic('error',`嵌套深度 ${value} 超过上限 ${LKL_LIMITS.maxNestingDepth}`,instances.find(item=>item.stableId===id),'container','拆分或改用 reference 位置'))}}

function validateVariables(variables,owner,parameters,diagnostics){const ids=new Set(variables.map(item=>item.stableId)),scope=new Set([...ids,...Object.keys(parameters??{}),'modulus']);for(const variable of variables){if(!variable.nameI18n?.['zh-CN']||!variable.nameI18n?.en)diagnostics.push(diagnostic('warning',`Variable "${variable.stableId}" 缺少完整中英文名称`,variable,'name','补充 name-zh-CN 与 name-en'));if(!variable.expression)continue;try{const expression=parseFormula(variable.expression);for(const dependency of formulaDependencies(expression))if(!scope.has(dependency))diagnostics.push(diagnostic('error',`Variable "${variable.stableId}" references unknown symbol "${dependency}"`,variable,'expression',nearest(dependency,[...scope])?`是否想引用 ${nearest(dependency,[...scope])}？`:null))}catch(error){diagnostics.push(diagnostic('error',`Invalid formula: ${error.message}`,variable,'expression'))}}}
