import {renderMarkdownDocument} from './math-markup.js';

const contentTypes=['note','definition','theorem','proof','example','counterexample','formula','reference','custom'];
const button=(documentRef,label,title=label)=>{const element=documentRef.createElement('button');element.type='button';element.textContent=label;element.title=title;return element};
const lines=value=>String(value??'').split('\n').map(item=>item.trim()).filter(Boolean);

export function createDocumentEditor(documentRef,{content={},mode='edit',isDraft=false,itemType='content',contextLabel='',onModeChange=()=>{},onChange=()=>{},onDone=()=>{},onCancel=()=>{},onMore=()=>{}}={}){
  let value={title:'',summary:'',body:'',contentType:'note',tags:[],sources:[],links:[],...structuredClone(content)},currentMode=mode;const page=documentRef.createElement('article');page.className='document-editor-page';
  const top=documentRef.createElement('header');top.className='document-editor-top';const back=button(documentRef,'←','返回');back.onclick=()=>isDraft?onCancel(value):onDone(value);top.append(back);if(contextLabel){const context=documentRef.createElement('span');context.className='document-context-label';context.textContent=contextLabel;top.append(context)}for(const[key,label]of[['edit','编辑'],['preview','预览'],['split','分屏']]){const control=button(documentRef,label);control.classList.toggle('active',key===currentMode);control.onclick=()=>onModeChange(key);top.append(control)}const state=documentRef.createElement('span');state.className='document-save-state';state.textContent=isDraft?'输入后自动保存':'已自动保存';const more=button(documentRef,'•••','更多');more.onclick=onMore;top.append(state,more);page.append(top);
  const title=documentRef.createElement('input');title.className='document-title-input';title.placeholder='无标题';title.value=value.title;title.setAttribute('aria-label','标题');page.append(title);const chip=documentRef.createElement('span');chip.className='document-type-chip';chip.textContent=itemType==='formula'?'公式':value.contentType;page.append(chip);
  const toolbar=documentRef.createElement('div');toolbar.className='document-format-toolbar';const formats=[['H','## ',''],['B','**','**'],['I','*','*'],['Code','`','`'],['∑','$','$'],['Link','[','](https://)']];for(const[label,prefix,suffix]of formats){const control=button(documentRef,label);control.onclick=()=>insertAround(body,prefix,suffix);toolbar.append(control)}page.append(toolbar);
  const shell=documentRef.createElement('div');shell.className=`document-editor-shell mode-${currentMode}`;const source=documentRef.createElement('section');source.className='document-editor-source';const body=documentRef.createElement('textarea');body.className='document-body-editor';body.placeholder=itemType==='formula'?'输入 LaTeX 或带公式的 Markdown…':'从正文开始。支持 Markdown 与 LaTeX…';body.value=value.body;source.append(body);const preview=documentRef.createElement('article');preview.className='document-editor-preview markdown-preview';shell.append(source,preview);page.append(shell);
  const properties=documentRef.createElement('details');properties.className='document-properties';const summary=documentRef.createElement('summary');summary.textContent='页面属性';const grid=documentRef.createElement('div');grid.className='document-properties-grid';const summaryControl=field(documentRef,grid,'摘要','textarea',value.summary),type=field(documentRef,grid,'内容类型','select',value.contentType),formula=itemType==='formula'||itemType==='relation'?field(documentRef,grid,'显示公式（LaTeX）','textarea',value.displayFormula??''):null,tags=field(documentRef,grid,'标签（逗号分隔）','input',(value.tags??[]).join(', ')),sources=field(documentRef,grid,'来源（每行一项）','textarea',(value.sources??[]).map(item=>typeof item==='string'?item:item.title??item.url??'').join('\n')),links=field(documentRef,grid,'链接（每行一个 URL）','textarea',(value.links??[]).map(item=>item.url??item).join('\n'));for(const item of contentTypes)type.add(new Option(item,item));type.value=value.contentType;properties.append(summary,grid);page.append(properties);
  const collect=()=>({...value,title:title.value,body:body.value,summary:summaryControl.value,contentType:type.value,...(formula?{displayFormula:formula.value}:{}),tags:tags.value.split(',').map(item=>item.trim()).filter(Boolean),sources:lines(sources.value),links:lines(links.value).map(url=>({url,label:url}))}),previewSource=next=>`${next.body??''}${next.displayFormula?`\n\n$$${next.displayFormula}$$`:''}`,update=()=>{value=collect();chip.textContent=itemType==='formula'?'公式':itemType==='relation'?'关系正文':value.contentType;state.textContent='正在自动保存…';renderMarkdownDocument(preview,previewSource(value)||'*暂无正文预览*');onChange(value);clearTimeout(page.saveTimer);page.saveTimer=setTimeout(()=>state.textContent='已自动保存',320)};
  for(const control of[title,body,summaryControl,formula,tags,sources,links].filter(Boolean))control.addEventListener('input',update);type.addEventListener('change',update);renderMarkdownDocument(preview,previewSource(value)||'*暂无正文预览*');queueMicrotask(()=>{(value.title?body:title).focus()});return page;
}

function field(documentRef,root,label,kind,value){const wrapper=documentRef.createElement('label');wrapper.append(documentRef.createTextNode(label));const control=documentRef.createElement(kind);control.value=value??'';wrapper.append(control);root.append(wrapper);return control}
function insertAround(textarea,prefix,suffix){const start=textarea.selectionStart,end=textarea.selectionEnd,selected=textarea.value.slice(start,end);textarea.setRangeText(`${prefix}${selected}${suffix}`,start,end,'select');textarea.dispatchEvent(new Event('input',{bubbles:true}));textarea.focus()}
