import {translateUI,contentTypeLabel} from './localization.js';
import {imageFileMarkdown} from './portable-media.js';
import {renderMarkdownDocument} from './math-markup.js';

const contentTypes=['note','definition','theorem','proof','example','counterexample','formula','reference','custom'];
const button=(documentRef,label,title=label)=>{const element=documentRef.createElement('button');element.type='button';element.textContent=label;element.title=title;return element};
const lines=value=>String(value??'').split('\n').map(item=>item.trim()).filter(Boolean);

export function createDocumentEditor(documentRef,{content={},mode='edit',isDraft=false,itemType='content',contextLabel='',language='zh-CN',onModeChange=()=>{},onChange=()=>{},onDone=()=>{},onCancel=()=>{},onMore=()=>{}}={}){
  const t=text=>translateUI(text,language);
  let value={title:'',summary:'',body:'',contentType:'note',tags:[],sources:[],links:[],...structuredClone(content)},currentMode=mode;const page=documentRef.createElement('article');page.className='document-editor-page';
  const top=documentRef.createElement('header');top.className='document-editor-top';const back=button(documentRef,'←',t('返回'));back.onclick=()=>isDraft?onCancel(value):onDone(value);top.append(back);if(contextLabel){const context=documentRef.createElement('span');context.className='document-context-label';context.textContent=contextLabel;top.append(context)}for(const[key,label]of[['edit',t('编辑')],['preview',t('预览')],['split',t('分屏')]]){const control=button(documentRef,t(label));control.classList.toggle('active',key===currentMode);control.onclick=()=>onModeChange(key);top.append(control)}const state=documentRef.createElement('span');state.className='document-save-state';state.textContent=isDraft?t('输入后自动保存'):t('已自动保存');const more=button(documentRef,'•••',t('更多'));more.onclick=onMore;top.append(state,more);page.append(top);
  const title=documentRef.createElement('input');title.className='document-title-input';title.placeholder=t('无标题');title.value=value.title;title.setAttribute('aria-label',t('标题'));page.append(title);const chip=documentRef.createElement('span');chip.className='document-type-chip';chip.textContent=itemType==='formula'?t('公式'):contentTypeLabel(value.contentType,language);page.append(chip);
  const toolbar=documentRef.createElement('div');toolbar.className='document-format-toolbar';const formats=[['H','## ',''],['B','**','**'],['I','*','*'],['Code','`','`'],['∑','$','$'],['Link','[','](https://)']];for(const[label,prefix,suffix]of formats){const control=button(documentRef,t(label));control.onclick=()=>insertAround(body,prefix,suffix);toolbar.append(control)}page.append(toolbar);
  const shell=documentRef.createElement('div');shell.className=`document-editor-shell mode-${currentMode}`;const source=documentRef.createElement('section');source.className='document-editor-source';const body=documentRef.createElement('textarea');body.className='document-body-editor';body.placeholder=itemType==='formula'?t('输入 LaTeX 或带公式的 Markdown…'):t('从正文开始。支持 Markdown 与 LaTeX…');body.value=value.body;source.append(body);const preview=documentRef.createElement('article');preview.className='document-editor-preview markdown-preview';shell.append(source,preview);page.append(shell);
  const properties=documentRef.createElement('details');properties.className='document-properties';const summary=documentRef.createElement('summary');summary.textContent=t('页面属性');const grid=documentRef.createElement('div');grid.className='document-properties-grid';const summaryControl=field(documentRef,grid,t('摘要'),'textarea',value.summary),type=field(documentRef,grid,t('内容类型'),'select',value.contentType),formula=itemType==='formula'||itemType==='relation'?field(documentRef,grid,t('显示公式（LaTeX）'),'textarea',value.displayFormula??''):null,tags=field(documentRef,grid,t('标签（逗号分隔）'),'input',(value.tags??[]).join(', ')),sources=field(documentRef,grid,t('来源（每行一项）'),'textarea',(value.sources??[]).map(item=>typeof item==='string'?item:item.title??item.url??'').join('\n')),links=field(documentRef,grid,t('链接（每行一个 URL）'),'textarea',(value.links??[]).map(item=>item.url??item).join('\n'));for(const item of contentTypes)type.add(new Option(contentTypeLabel(item,language),item));type.value=value.contentType;properties.append(summary,grid);page.append(properties);
  const collect=()=>({...value,title:title.value,body:body.value,summary:summaryControl.value,contentType:type.value,...(formula?{displayFormula:formula.value}:{}),tags:tags.value.split(',').map(item=>item.trim()).filter(Boolean),sources:sources.value===(value.sources??[]).map(item=>typeof item==='string'?item:item.title??item.url??'').join('\n')?value.sources:lines(sources.value),links:links.value===(value.links??[]).map(item=>item.url??item).join('\n')?value.links:lines(links.value).map(url=>({url,label:url}))}),previewSource=next=>`${next.body??''}${next.displayFormula?`\n\n$$${next.displayFormula}$$`:''}`,update=()=>{value=collect();chip.textContent=itemType==='formula'?t('公式'):itemType==='relation'?t('关系正文'):contentTypeLabel(value.contentType,language);state.textContent=t('正在自动保存…');renderMarkdownDocument(preview,previewSource(value)||t('*暂无正文预览*'));onChange(value);clearTimeout(page.saveTimer);page.saveTimer=setTimeout(()=>state.textContent=t('已自动保存'),320)};
  const mediaMessage=documentRef.createElement('span');mediaMessage.className='document-media-message';mediaMessage.setAttribute('role','status');
  const imageInput=documentRef.createElement('input');imageInput.type='file';imageInput.accept='image/png,image/jpeg,image/webp,image/gif';imageInput.multiple=true;imageInput.hidden=true;
  const imageButton=button(documentRef,t('图片'),t('插入图片；也可直接粘贴或拖入')),plotButton=button(documentRef,t('绘图'),t('插入可运行的向量空间图形'));
  imageButton.onclick=()=>imageInput.click();
  const insertText=text=>{body.setRangeText('\n'+text+'\n',body.selectionStart,body.selectionEnd,'end');body.dispatchEvent(new Event('input',{bubbles:true}));body.focus()};
  const insertImages=async files=>{for(const file of files){try{mediaMessage.classList.remove('error');mediaMessage.textContent=t('正在插入图片…');insertText(await imageFileMarkdown(file));mediaMessage.textContent=t('图片已嵌入正文，可随 LKL 导出')}catch(error){mediaMessage.classList.add('error');mediaMessage.textContent=t(error.message)}}};
  imageInput.onchange=()=>{insertImages([...imageInput.files]);imageInput.value=''};
  body.addEventListener('paste',event=>{const files=[...(event.clipboardData?.files??[])].filter(file=>file.type.startsWith('image/'));if(files.length){event.preventDefault();insertImages(files)}});
  body.addEventListener('dragover',event=>{if([...event.dataTransfer.items].some(item=>item.kind==='file'))event.preventDefault()});
  body.addEventListener('drop',event=>{const files=[...event.dataTransfer.files].filter(file=>file.type.startsWith('image/'));if(files.length){event.preventDefault();insertImages(files)}});
  plotButton.onclick=()=>{const selected=body.value.slice(body.selectionStart,body.selectionEnd).trim(),fence=String.fromCharCode(96).repeat(3);insertText(fence+'plot\n'+(selected||'y=sin(x)')+'\n'+fence);onModeChange('split')};
  toolbar.append(imageButton,plotButton,imageInput,mediaMessage);
  for(const control of[title,body,summaryControl,formula,tags,sources,links].filter(Boolean))control.addEventListener('input',update);type.addEventListener('change',update);renderMarkdownDocument(preview,previewSource(value)||t('*暂无正文预览*'));queueMicrotask(()=>{(value.title?body:title).focus()});return page;
}

function field(documentRef,root,label,kind,value){const wrapper=documentRef.createElement('label');wrapper.append(documentRef.createTextNode(label));const control=documentRef.createElement(kind);control.value=value??'';wrapper.append(control);root.append(wrapper);return control}
function insertAround(textarea,prefix,suffix){const start=textarea.selectionStart,end=textarea.selectionEnd,selected=textarea.value.slice(start,end);textarea.setRangeText(`${prefix}${selected}${suffix}`,start,end,'select');textarea.dispatchEvent(new Event('input',{bubbles:true}));textarea.focus()}
